/*******************************************************************************
 * C Structs For Tmx QuantumFeed Xmt UdpHeader 1.1 Binary Model
 *******************************************************************************/

/*******************************************************************************
 * Enum Values
 *******************************************************************************/

/*
 * Ack Required Poss Dup Values
 */ 
#define ENUM_ACK_REQUIRED_POSS_DUP_RECEIVER_NEEDS_TO_ACK 'A'
#define ENUM_ACK_REQUIRED_POSS_DUP_POSSIBLE_DUPLICATES 'D'


/*******************************************************************************
 * Structs
 *******************************************************************************/

#pragma pack(push, 1)

/*
 * Structure: Body Header
 */ 
typedef struct {
    uint16_t MsgLength;
    char MsgType[1];
} BodyHeaderT;

/*
 * Structure: Body
 */ 
typedef struct {
    BodyHeaderT BodyHeader;
} BodyT;

/*
 * Structure: Frame Header
 */ 
typedef struct {
    char StartOfFrame;
    char ProtocolName[1];
    char ProtocolVersion[1];
    uint16_t MessageLength;
    uint32_t SessionId;
    char AckRequiredPossDup;
    uint8_t NumBody;
} FrameHeaderT;

/*
 * Structure: Packet
 */ 
typedef struct {
    FrameHeaderT FrameHeader;
} PacketT;

#pragma pack(pop)

/*******************************************************************************

Protocol:
   Organization: Tmx Group
   Version: 1.1
   Date: Tuesday, October 20, 2020

Source:
   Generator: 1.0.0.0
   Compiler: 2.0
   License: MIT No Attribution License
   Authors: Omi Developers

This file was generated by the Open Markets Initiative (Omi).

Information relating to Omi:
https://github.com/Open-Markets-Initiative/Directory

*******************************************************************************/
