/*******************************************************************************
 * C Structs For Eurex Cash T7 Eti 7.1 Binary Model
 *******************************************************************************/

/*******************************************************************************
 * Enum Values
 *******************************************************************************/

/*
 * Alloc Method Values
 */ 
#define ENUM_ALLOC_METHOD_AUTOMATIC_RANDOM 1
#define ENUM_ALLOC_METHOD_MANUAL 3
#define ENUM_ALLOC_METHOD_ALLOC_METHOD_MAXIMUM_VALUE 3
#define ENUM_ALLOC_METHOD_ALLOC_METHOD_MINIMUM_VALUE 1

/*
 * Appl Id Values
 */ 
#define ENUM_APPL_ID_TRADE 1
#define ENUM_APPL_ID_NEWS 2
#define ENUM_APPL_ID_SERVICEAVAILABILITY 3
#define ENUM_APPL_ID_SESSIONDATA 4
#define ENUM_APPL_ID_LISTENERDATA 5
#define ENUM_APPL_ID_RISK_CONTROL 6
#define ENUM_APPL_ID_TES_MAINTENANCE 7
#define ENUM_APPL_ID_TES_TRADE 8
#define ENUM_APPL_ID_SRQS_MAINTENANCE 9
#define ENUM_APPL_ID_SERVICE_AVAILABILITY_MARKET 10
#define ENUM_APPL_ID_APPL_ID_MAXIMUM_VALUE 10
#define ENUM_APPL_ID_APPL_ID_MINIMUM_VALUE 0

/*
 * Appl Id Status Values
 */ 
#define ENUM_APPL_ID_STATUS_OUTBOUNDCONVERSIONERROR 105
#define ENUM_APPL_ID_STATUS_APPL_ID_STATUS_MAXIMUM_VALUE 4294967294
#define ENUM_APPL_ID_STATUS_APPL_ID_STATUS_MINIMUM_VALUE 0

/*
 * Appl Resend Flag Values
 */ 
#define ENUM_APPL_RESEND_FLAG_FALSE 0
#define ENUM_APPL_RESEND_FLAG_TRUE 1
#define ENUM_APPL_RESEND_FLAG_APPL_RESEND_FLAG_MAXIMUM_VALUE 1
#define ENUM_APPL_RESEND_FLAG_APPL_RESEND_FLAG_MINIMUM_VALUE 0

/*
 * Appl Seq Indicator Values
 */ 
#define ENUM_APPL_SEQ_INDICATOR_NO_RECOVERY_REQUIRED 0
#define ENUM_APPL_SEQ_INDICATOR_RECOVERY_REQUIRED 1
#define ENUM_APPL_SEQ_INDICATOR_APPL_SEQ_INDICATOR_MAXIMUM_VALUE 1
#define ENUM_APPL_SEQ_INDICATOR_APPL_SEQ_INDICATOR_MINIMUM_VALUE 0

/*
 * Appl Seq Status Values
 */ 
#define ENUM_APPL_SEQ_STATUS_UNAVAILABLE 0
#define ENUM_APPL_SEQ_STATUS_AVAILABLE 1
#define ENUM_APPL_SEQ_STATUS_APPL_SEQ_STATUS_MAXIMUM_VALUE 1
#define ENUM_APPL_SEQ_STATUS_APPL_SEQ_STATUS_MINIMUM_VALUE 0

/*
 * Appl Usage Orders Values
 */ 
#define ENUM_APPL_USAGE_ORDERS_AUTOMATED 'A'
#define ENUM_APPL_USAGE_ORDERS_MANUAL 'M'
#define ENUM_APPL_USAGE_ORDERS_AUTO_SELECT 'B'
#define ENUM_APPL_USAGE_ORDERS_NONE 'N'

/*
 * Appl Usage Quotes Values
 */ 
#define ENUM_APPL_USAGE_QUOTES_AUTOMATED 'A'
#define ENUM_APPL_USAGE_QUOTES_MANUAL 'M'
#define ENUM_APPL_USAGE_QUOTES_AUTO_SELECT 'B'
#define ENUM_APPL_USAGE_QUOTES_NONE 'N'

/*
 * Crossed Indicator Values
 */ 
#define ENUM_CROSSED_INDICATOR_NOCROSSING 0
#define ENUM_CROSSED_INDICATOR_CROSSREJECTED 1
#define ENUM_CROSSED_INDICATOR_CROSSED_INDICATOR_MAXIMUM_VALUE 1
#define ENUM_CROSSED_INDICATOR_CROSSED_INDICATOR_MINIMUM_VALUE 0

/*
 * Delete Reason Values
 */ 
#define ENUM_DELETE_REASON_NOSPECIALREASON 100
#define ENUM_DELETE_REASON_TAS_CHANGE 101
#define ENUM_DELETE_REASON_INTRADAY_EXPIRATION 102
#define ENUM_DELETE_REASON_RISK_EVENT 103
#define ENUM_DELETE_REASON_STOP_TRADING 104
#define ENUM_DELETE_REASON_DELETE_REASON_MAXIMUM_VALUE 107
#define ENUM_DELETE_REASON_DELETE_REASON_MINIMUM_VALUE 100

/*
 * Delivery Type Values
 */ 
#define ENUM_DELIVERY_TYPE_AKV 1
#define ENUM_DELIVERY_TYPE_GS 2
#define ENUM_DELIVERY_TYPE_STR 3
#define ENUM_DELIVERY_TYPE_WPR 4
#define ENUM_DELIVERY_TYPE_DELIVERY_TYPE_MAXIMUM_VALUE 4
#define ENUM_DELIVERY_TYPE_DELIVERY_TYPE_MINIMUM_VALUE 1

/*
 * Event Type Values
 */ 
#define ENUM_EVENT_TYPE_REDEMPTION 26
#define ENUM_EVENT_TYPE_DELISTING 100
#define ENUM_EVENT_TYPE_EVENT_TYPE_MAXIMUM_VALUE 100
#define ENUM_EVENT_TYPE_EVENT_TYPE_MINIMUM_VALUE 8

/*
 * Ex Destination Type Values
 */ 
#define ENUM_EX_DESTINATION_TYPE_TRADEONEXCHANGEOR_SI 3
#define ENUM_EX_DESTINATION_TYPE_EX_DESTINATION_TYPE_MAXIMUM_VALUE 3
#define ENUM_EX_DESTINATION_TYPE_EX_DESTINATION_TYPE_MINIMUM_VALUE 3

/*
 * Exec Inst Values
 */ 
#define ENUM_EXEC_INST_H 1
#define ENUM_EXEC_INST_Q 2
#define ENUM_EXEC_INST_HQ 3
#define ENUM_EXEC_INST_H6 5
#define ENUM_EXEC_INST_Q6 6
#define ENUM_EXEC_INST_EXEC_INST_MAXIMUM_VALUE 6
#define ENUM_EXEC_INST_EXEC_INST_MINIMUM_VALUE 1

/*
 * Exec Restatement Reason Values
 */ 
#define ENUM_EXEC_RESTATEMENT_REASON_CORPORATE_ACTION 0
#define ENUM_EXEC_RESTATEMENT_REASON_ORDER_BOOK_RESTATEMENT 1
#define ENUM_EXEC_RESTATEMENT_REASON_EXCHANGE_OPTION 8
#define ENUM_EXEC_RESTATEMENT_REASON_ORDER_ADDED 101
#define ENUM_EXEC_RESTATEMENT_REASON_ORDER_MODIFIED 102
#define ENUM_EXEC_RESTATEMENT_REASON_ORDER_CANCELLED 103
#define ENUM_EXEC_RESTATEMENT_REASON_IOC_ORDER_CANCELLED 105
#define ENUM_EXEC_RESTATEMENT_REASON_FOK_ORDER_CANCELLED 107
#define ENUM_EXEC_RESTATEMENT_REASON_BOOK_ORDER_EXECUTED 108
#define ENUM_EXEC_RESTATEMENT_REASON_CHANGEDTO_IOC 114
#define ENUM_EXEC_RESTATEMENT_REASON_INSTRUMENT_STATE_CHANGE 122
#define ENUM_EXEC_RESTATEMENT_REASON_END_OF_DAY_PROCESSING 146
#define ENUM_EXEC_RESTATEMENT_REASON_ORDER_EXPIRATION 148
#define ENUM_EXEC_RESTATEMENT_REASON_CAO_ORDER_ACTIVATED 149
#define ENUM_EXEC_RESTATEMENT_REASON_CAO_ORDER_INACTIVATED 150
#define ENUM_EXEC_RESTATEMENT_REASON_OAO_ORDER_ACTIVATED 151
#define ENUM_EXEC_RESTATEMENT_REASON_OAO_ORDER_INACTIVATED 152
#define ENUM_EXEC_RESTATEMENT_REASON_AAO_ORDER_ACTIVATED 153
#define ENUM_EXEC_RESTATEMENT_REASON_AAO_ORDER_INACTIVATED 154
#define ENUM_EXEC_RESTATEMENT_REASON_IAO_ORDER_ACTIVATED 159
#define ENUM_EXEC_RESTATEMENT_REASON_IAO_ORDER_INACTIVATED 160
#define ENUM_EXEC_RESTATEMENT_REASON_ORDER_REFRESHED 155
#define ENUM_EXEC_RESTATEMENT_REASON_OCO_ORDER_TRIGGERED 164
#define ENUM_EXEC_RESTATEMENT_REASON_STOP_ORDER_TRIGGERED 172
#define ENUM_EXEC_RESTATEMENT_REASON_OWNERSHIP_CHANGED 181
#define ENUM_EXEC_RESTATEMENT_REASON_ORDER_CANCELLATION_PENDING 197
#define ENUM_EXEC_RESTATEMENT_REASON_PENDING_CANCELLATION_EXECUTED 199
#define ENUM_EXEC_RESTATEMENT_REASON_BOC_ORDER_CANCELLED 212
#define ENUM_EXEC_RESTATEMENT_REASON_TRAILING_STOP_UPDATE 213
#define ENUM_EXEC_RESTATEMENT_REASON_EXCEEDS_MAXIMUM_QUANTITY 237
#define ENUM_EXEC_RESTATEMENT_REASON_INVALID_LIMIT_PRICE 238
#define ENUM_EXEC_RESTATEMENT_REASON_USER_DOES_NOT_EXIST 241
#define ENUM_EXEC_RESTATEMENT_REASON_SESSION_DOES_NOT_EXIST 242
#define ENUM_EXEC_RESTATEMENT_REASON_INVALID_STOP_PRICE 243
#define ENUM_EXEC_RESTATEMENT_REASON_INSTRUMENT_DOES_NOT_EXIST 245
#define ENUM_EXEC_RESTATEMENT_REASON_BUSINESS_UNIT_RISK_EVENT 246
#define ENUM_EXEC_RESTATEMENT_REASON_PANIC_CANCEL 261
#define ENUM_EXEC_RESTATEMENT_REASON_DIVIDEND_PAYMENT 292
#define ENUM_EXEC_RESTATEMENT_REASON_LAST_TRADING_DAY 294
#define ENUM_EXEC_RESTATEMENT_REASON_TRADING_PARAMETER_CHANGE 295
#define ENUM_EXEC_RESTATEMENT_REASON_CURRENCY_CHANGE 296
#define ENUM_EXEC_RESTATEMENT_REASON_PRODUCT_ASSIGNMENT_CHANGE 297
#define ENUM_EXEC_RESTATEMENT_REASON_REFERENCE_PRICE_CHANGE 298
#define ENUM_EXEC_RESTATEMENT_REASON_TICK_RULE_CHANGE 300
#define ENUM_EXEC_RESTATEMENT_REASON_EXEC_RESTATEMENT_REASON_MAXIMUM_VALUE 344
#define ENUM_EXEC_RESTATEMENT_REASON_EXEC_RESTATEMENT_REASON_MINIMUM_VALUE 0

/*
 * Exec Type Values
 */ 
#define ENUM_EXEC_TYPE_NEW '0'
#define ENUM_EXEC_TYPE_CANCELED '4'
#define ENUM_EXEC_TYPE_REPLACED '5'
#define ENUM_EXEC_TYPE_PENDING_CANCELE '6'
#define ENUM_EXEC_TYPE_SUSPENDED '9'
#define ENUM_EXEC_TYPE_RESTATED 'D'
#define ENUM_EXEC_TYPE_TRIGGERED 'L'
#define ENUM_EXEC_TYPE_TRADE 'F'

/*
 * Executing Trader Qualifier Values
 */ 
#define ENUM_EXECUTING_TRADER_QUALIFIER_ALGO 22
#define ENUM_EXECUTING_TRADER_QUALIFIER_HUMAN 24
#define ENUM_EXECUTING_TRADER_QUALIFIER_EXECUTING_TRADER_QUALIFIER_MAXIMUM_VALUE 24
#define ENUM_EXECUTING_TRADER_QUALIFIER_EXECUTING_TRADER_QUALIFIER_MINIMUM_VALUE 22

/*
 * Fill Liquidity Ind Values
 */ 
#define ENUM_FILL_LIQUIDITY_IND_ADDED_LIQUIDITY 1
#define ENUM_FILL_LIQUIDITY_IND_REMOVED_LIQUIDITY 2
#define ENUM_FILL_LIQUIDITY_IND_AUCTION 4
#define ENUM_FILL_LIQUIDITY_IND_TRIGGERED_STOP_ORDER 5
#define ENUM_FILL_LIQUIDITY_IND_TRIGGERED_OCO_ORDER 6
#define ENUM_FILL_LIQUIDITY_IND_TRIGGERED_MARKET_ORDER 7
#define ENUM_FILL_LIQUIDITY_IND_FILL_LIQUIDITY_IND_MAXIMUM_VALUE 7
#define ENUM_FILL_LIQUIDITY_IND_FILL_LIQUIDITY_IND_MINIMUM_VALUE 1

/*
 * Last Coupon Deviation Indicator Values
 */ 
#define ENUM_LAST_COUPON_DEVIATION_INDICATOR_NONE 0
#define ENUM_LAST_COUPON_DEVIATION_INDICATOR_SHORTPERIOD 1
#define ENUM_LAST_COUPON_DEVIATION_INDICATOR_LONGPERIOD 2
#define ENUM_LAST_COUPON_DEVIATION_INDICATOR_ONLYONECOUPON 3
#define ENUM_LAST_COUPON_DEVIATION_INDICATOR_SHORTTWOINTERESTPAYMENTSDUE 4
#define ENUM_LAST_COUPON_DEVIATION_INDICATOR_LONGTWOINTERESTPAYMENTSDUE 5
#define ENUM_LAST_COUPON_DEVIATION_INDICATOR_LAST_COUPON_DEVIATION_INDICATOR_MAXIMUM_VALUE 5
#define ENUM_LAST_COUPON_DEVIATION_INDICATOR_LAST_COUPON_DEVIATION_INDICATOR_MINIMUM_VALUE 0

/*
 * Last Fragment Values
 */ 
#define ENUM_LAST_FRAGMENT_NOT_LAST_MESSAGE 0
#define ENUM_LAST_FRAGMENT_LAST_MESSAGE 1
#define ENUM_LAST_FRAGMENT_LAST_FRAGMENT_MAXIMUM_VALUE 1
#define ENUM_LAST_FRAGMENT_LAST_FRAGMENT_MINIMUM_VALUE 0

/*
 * Last Mkt Values
 */ 
#define ENUM_LAST_MKT_XETR 3
#define ENUM_LAST_MKT_XVIE 4
#define ENUM_LAST_MKT_XMAL 6
#define ENUM_LAST_MKT_XBUL 7
#define ENUM_LAST_MKT_XBUD 8
#define ENUM_LAST_MKT_XLJU 9
#define ENUM_LAST_MKT_XPRA 10
#define ENUM_LAST_MKT_XZAG 11
#define ENUM_LAST_MKT_LAST_MKT_MAXIMUM_VALUE 255
#define ENUM_LAST_MKT_LAST_MKT_MINIMUM_VALUE 1

/*
 * List Update Action Values
 */ 
#define ENUM_LIST_UPDATE_ACTION_ADD 'A'
#define ENUM_LIST_UPDATE_ACTION_DELETE 'D'

/*
 * Market Id Values
 */ 
#define ENUM_MARKET_ID_XETR 3
#define ENUM_MARKET_ID_XVIE 4
#define ENUM_MARKET_ID_XMAL 6
#define ENUM_MARKET_ID_XBUL 7
#define ENUM_MARKET_ID_XBUD 8
#define ENUM_MARKET_ID_XLJU 9
#define ENUM_MARKET_ID_XPRA 10
#define ENUM_MARKET_ID_XZAG 11
#define ENUM_MARKET_ID_MARKET_ID_MAXIMUM_VALUE 255
#define ENUM_MARKET_ID_MARKET_ID_MINIMUM_VALUE 1

/*
 * Mass Action Reason Values
 */ 
#define ENUM_MASS_ACTION_REASON_NO_SPECIAL_REASON 0
#define ENUM_MASS_ACTION_REASON_STOP_TRADING 1
#define ENUM_MASS_ACTION_REASON_EMERGENCY 2
#define ENUM_MASS_ACTION_REASON_SESSION_LOSS 6
#define ENUM_MASS_ACTION_REASON_DUPLICATE_SESSION_LOGIN 7
#define ENUM_MASS_ACTION_REASON_CLEARING_RISK_CONTROL 8
#define ENUM_MASS_ACTION_REASON_PRODUCT_STATE_HALT 105
#define ENUM_MASS_ACTION_REASON_PRODUCT_STATE_HOLIDAY 106
#define ENUM_MASS_ACTION_REASON_INSTRUMENT_SUSPENDED 107
#define ENUM_MASS_ACTION_REASON_VOLATILITY_INTERRUPTION 110
#define ENUM_MASS_ACTION_REASON_PRODUCTTEMPORARILYNOTTRADEABLE 111
#define ENUM_MASS_ACTION_REASON_INSTRUMENT_STOPPED 113
#define ENUM_MASS_ACTION_REASON_INSTRUMENT_KNOCK_OUT 115
#define ENUM_MASS_ACTION_REASON_INSTRUMENT_SOLD_OUT 116
#define ENUM_MASS_ACTION_REASON_MASS_ACTION_REASON_MAXIMUM_VALUE 200
#define ENUM_MASS_ACTION_REASON_MASS_ACTION_REASON_MINIMUM_VALUE 0

/*
 * Mass Action Type Values
 */ 
#define ENUM_MASS_ACTION_TYPE_SUSPENDQUOTES 1
#define ENUM_MASS_ACTION_TYPE_RELEASEQUOTES 2
#define ENUM_MASS_ACTION_TYPE_MASS_ACTION_TYPE_MAXIMUM_VALUE 2
#define ENUM_MASS_ACTION_TYPE_MASS_ACTION_TYPE_MINIMUM_VALUE 1

/*
 * Match Sub Type Values
 */ 
#define ENUM_MATCH_SUB_TYPE_OPENING_AUCTION 1
#define ENUM_MATCH_SUB_TYPE_CLOSING_AUCTION 2
#define ENUM_MATCH_SUB_TYPE_INTRADAY_AUCTION 3
#define ENUM_MATCH_SUB_TYPE_CIRCUIT_BREAKER_AUCTION 4
#define ENUM_MATCH_SUB_TYPE_MATCH_SUB_TYPE_MAXIMUM_VALUE 6
#define ENUM_MATCH_SUB_TYPE_MATCH_SUB_TYPE_MINIMUM_VALUE 1

/*
 * Match Type Values
 */ 
#define ENUM_MATCH_TYPE_CONFIRMED_TRADE_REPORT 3
#define ENUM_MATCH_TYPE_AUTOMATCHINCOMING 4
#define ENUM_MATCH_TYPE_CROSS_AUCTION 5
#define ENUM_MATCH_TYPE_CALL_AUCTION 7
#define ENUM_MATCH_TYPE_SYSTEMATIC_INTERNALISER 9
#define ENUM_MATCH_TYPE_AUTOMATCHRESTING 11
#define ENUM_MATCH_TYPE_AUTOMATCHATMIDPOINT 12
#define ENUM_MATCH_TYPE_CONTINOUS_AUCTION 14
#define ENUM_MATCH_TYPE_MATCH_TYPE_MAXIMUM_VALUE 14
#define ENUM_MATCH_TYPE_MATCH_TYPE_MINIMUM_VALUE 0

/*
 * Matching Engine Status Values
 */ 
#define ENUM_MATCHING_ENGINE_STATUS_UNAVAILABLE 0
#define ENUM_MATCHING_ENGINE_STATUS_AVAILABLE 1
#define ENUM_MATCHING_ENGINE_STATUS_MATCHING_ENGINE_STATUS_MAXIMUM_VALUE 1
#define ENUM_MATCHING_ENGINE_STATUS_MATCHING_ENGINE_STATUS_MINIMUM_VALUE 0

/*
 * Md Book Type Values
 */ 
#define ENUM_MD_BOOK_TYPE_TOP_OF_BOOK 1
#define ENUM_MD_BOOK_TYPE_PRICE_DEPTH 2
#define ENUM_MD_BOOK_TYPE_MD_BOOK_TYPE_MAXIMUM_VALUE 2
#define ENUM_MD_BOOK_TYPE_MD_BOOK_TYPE_MINIMUM_VALUE 1

/*
 * Md Sub Book Type Values
 */ 
#define ENUM_MD_SUB_BOOK_TYPE_VOLUME_WEIGHTED_AVERAGE 2
#define ENUM_MD_SUB_BOOK_TYPE_MD_SUB_BOOK_TYPE_MAXIMUM_VALUE 2
#define ENUM_MD_SUB_BOOK_TYPE_MD_SUB_BOOK_TYPE_MINIMUM_VALUE 1

/*
 * Message Event Source Values
 */ 
#define ENUM_MESSAGE_EVENT_SOURCE_BROADCASTTO_INITIATOR 'I'
#define ENUM_MESSAGE_EVENT_SOURCE_BROADCASTTO_APPROVER 'A'
#define ENUM_MESSAGE_EVENT_SOURCE_BROADCASTTO_REQUESTER 'R'
#define ENUM_MESSAGE_EVENT_SOURCE_BROADCASTTO_QUOTE_SUBMITTER 'Q'

/*
 * Number Of Resp Disclosure Instruction Values
 */ 
#define ENUM_NUMBER_OF_RESP_DISCLOSURE_INSTRUCTION_NO 0
#define ENUM_NUMBER_OF_RESP_DISCLOSURE_INSTRUCTION_YES 1
#define ENUM_NUMBER_OF_RESP_DISCLOSURE_INSTRUCTION_NUMBER_OF_RESP_DISCLOSURE_INSTRUCTION_MAXIMUM_VALUE 1
#define ENUM_NUMBER_OF_RESP_DISCLOSURE_INSTRUCTION_NUMBER_OF_RESP_DISCLOSURE_INSTRUCTION_MINIMUM_VALUE 0

/*
 * Ord Status Values
 */ 
#define ENUM_ORD_STATUS_NEW '0'
#define ENUM_ORD_STATUS_PARTIALLYFILLED '1'
#define ENUM_ORD_STATUS_FILLED '2'
#define ENUM_ORD_STATUS_CANCELED '4'
#define ENUM_ORD_STATUS_PENDING_CANCEL '6'
#define ENUM_ORD_STATUS_SUSPENDED '9'

/*
 * Ord Type Values
 */ 
#define ENUM_ORD_TYPE_MARKET 1
#define ENUM_ORD_TYPE_LIMIT 2
#define ENUM_ORD_TYPE_STOP 3
#define ENUM_ORD_TYPE_STOP_LIMIT 4
#define ENUM_ORD_TYPE_ORD_TYPE_MAXIMUM_VALUE 4
#define ENUM_ORD_TYPE_ORD_TYPE_MINIMUM_VALUE 1

/*
 * Order Attribute Liquidity Provision Values
 */ 
#define ENUM_ORDER_ATTRIBUTE_LIQUIDITY_PROVISION_Y 1
#define ENUM_ORDER_ATTRIBUTE_LIQUIDITY_PROVISION_N 0
#define ENUM_ORDER_ATTRIBUTE_LIQUIDITY_PROVISION_ORDER_ATTRIBUTE_LIQUIDITY_PROVISION_MAXIMUM_VALUE 1
#define ENUM_ORDER_ATTRIBUTE_LIQUIDITY_PROVISION_ORDER_ATTRIBUTE_LIQUIDITY_PROVISION_MINIMUM_VALUE 0

/*
 * Order Category Values
 */ 
#define ENUM_ORDER_CATEGORY_ORDER '1'
#define ENUM_ORDER_CATEGORY_QUOTE '2'

/*
 * Order Routing Indicator Values
 */ 
#define ENUM_ORDER_ROUTING_INDICATOR_YES 'Y'
#define ENUM_ORDER_ROUTING_INDICATOR_NO 'N'

/*
 * Ownership Indicator Values
 */ 
#define ENUM_OWNERSHIP_INDICATOR_NO_CHANGEOF_OWNERSHIP 0
#define ENUM_OWNERSHIP_INDICATOR_CHANGETO_EXECUTING_TRADER 1
#define ENUM_OWNERSHIP_INDICATOR_OWNERSHIP_INDICATOR_MAXIMUM_VALUE 1
#define ENUM_OWNERSHIP_INDICATOR_OWNERSHIP_INDICATOR_MINIMUM_VALUE 0

/*
 * Party Action Type Values
 */ 
#define ENUM_PARTY_ACTION_TYPE_HALT_TRADING 1
#define ENUM_PARTY_ACTION_TYPE_REINSTATE 2
#define ENUM_PARTY_ACTION_TYPE_PARTY_ACTION_TYPE_MAXIMUM_VALUE 2
#define ENUM_PARTY_ACTION_TYPE_PARTY_ACTION_TYPE_MINIMUM_VALUE 1

/*
 * Party Detail Role Qualifier Values
 */ 
#define ENUM_PARTY_DETAIL_ROLE_QUALIFIER_TRADER 10
#define ENUM_PARTY_DETAIL_ROLE_QUALIFIER_HEAD_TRADER 11
#define ENUM_PARTY_DETAIL_ROLE_QUALIFIER_SUPERVISOR 12
#define ENUM_PARTY_DETAIL_ROLE_QUALIFIER_PARTY_DETAIL_ROLE_QUALIFIER_MAXIMUM_VALUE 12
#define ENUM_PARTY_DETAIL_ROLE_QUALIFIER_PARTY_DETAIL_ROLE_QUALIFIER_MINIMUM_VALUE 10

/*
 * Party Detail Status Values
 */ 
#define ENUM_PARTY_DETAIL_STATUS_ACTIVE 0
#define ENUM_PARTY_DETAIL_STATUS_SUSPEND 1
#define ENUM_PARTY_DETAIL_STATUS_PARTY_DETAIL_STATUS_MAXIMUM_VALUE 1
#define ENUM_PARTY_DETAIL_STATUS_PARTY_DETAIL_STATUS_MINIMUM_VALUE 0

/*
 * Party Id Entering Firm Values
 */ 
#define ENUM_PARTY_ID_ENTERING_FIRM_PARTICIPANT 1
#define ENUM_PARTY_ID_ENTERING_FIRM_MARKET_SUPERVISION 2
#define ENUM_PARTY_ID_ENTERING_FIRM_PARTY_ID_ENTERING_FIRM_MAXIMUM_VALUE 2
#define ENUM_PARTY_ID_ENTERING_FIRM_PARTY_ID_ENTERING_FIRM_MINIMUM_VALUE 1

/*
 * Party Id Investment Decision Maker Qualifier Values
 */ 
#define ENUM_PARTY_ID_INVESTMENT_DECISION_MAKER_QUALIFIER_ALGO 22
#define ENUM_PARTY_ID_INVESTMENT_DECISION_MAKER_QUALIFIER_HUMAN 24
#define ENUM_PARTY_ID_INVESTMENT_DECISION_MAKER_QUALIFIER_PARTY_ID_INVESTMENT_DECISION_MAKER_QUALIFIER_MAXIMUM_VALUE 24
#define ENUM_PARTY_ID_INVESTMENT_DECISION_MAKER_QUALIFIER_PARTY_ID_INVESTMENT_DECISION_MAKER_QUALIFIER_MINIMUM_VALUE 22

/*
 * Price Validity Check Type Values
 */ 
#define ENUM_PRICE_VALIDITY_CHECK_TYPE_NONE 0
#define ENUM_PRICE_VALIDITY_CHECK_TYPE_MANDATORY 2
#define ENUM_PRICE_VALIDITY_CHECK_TYPE_PRICE_VALIDITY_CHECK_TYPE_MAXIMUM_VALUE 2
#define ENUM_PRICE_VALIDITY_CHECK_TYPE_PRICE_VALIDITY_CHECK_TYPE_MINIMUM_VALUE 0

/*
 * Quote Cancel Type Values
 */ 
#define ENUM_QUOTE_CANCEL_TYPE_CANCEL_ALL_QUOTES 4
#define ENUM_QUOTE_CANCEL_TYPE_QUOTE_CANCEL_TYPE_MAXIMUM_VALUE 4
#define ENUM_QUOTE_CANCEL_TYPE_QUOTE_CANCEL_TYPE_MINIMUM_VALUE 4

/*
 * Quote Entry Reject Reason Values
 */ 
#define ENUM_QUOTE_ENTRY_REJECT_REASON_UNKNOWN_SECURITY 1
#define ENUM_QUOTE_ENTRY_REJECT_REASON_DUPLICATE_QUOTE 6
#define ENUM_QUOTE_ENTRY_REJECT_REASON_INVALID_PRICE 8
#define ENUM_QUOTE_ENTRY_REJECT_REASON_NO_REFERENCE_PRICE_AVAILABLE 16
#define ENUM_QUOTE_ENTRY_REJECT_REASON_NO_SINGLE_SIDED_QUOTES 100
#define ENUM_QUOTE_ENTRY_REJECT_REASON_INVALID_QUOTING_MODEL 103
#define ENUM_QUOTE_ENTRY_REJECT_REASON_INVALID_SIZE 106
#define ENUM_QUOTE_ENTRY_REJECT_REASON_BID_PRICE_NOT_REASONABLE 108
#define ENUM_QUOTE_ENTRY_REJECT_REASON_ASK_PRICE_NOT_REASONABLE 109
#define ENUM_QUOTE_ENTRY_REJECT_REASON_BID_PRICE_EXCEEDS_RANGE 110
#define ENUM_QUOTE_ENTRY_REJECT_REASON_ASK_PRICE_EXCEEDS_RANGE 111
#define ENUM_QUOTE_ENTRY_REJECT_REASON_INSTRUMENT_STATE_FREEZE 115
#define ENUM_QUOTE_ENTRY_REJECT_REASON_DELETION_ALREADY_PENDING 116
#define ENUM_QUOTE_ENTRY_REJECT_REASON_PRE_TRADE_RISK_SESSION_LIMIT_EXCEEDED 117
#define ENUM_QUOTE_ENTRY_REJECT_REASON_PRE_TRADE_RISK_BU_LIMIT_EXCEEDED 118
#define ENUM_QUOTE_ENTRY_REJECT_REASON_BID_VALUE_EXCEEDS_LIMIT 120
#define ENUM_QUOTE_ENTRY_REJECT_REASON_ASK_VALUE_EXCEEDS_LIMIT 121
#define ENUM_QUOTE_ENTRY_REJECT_REASON_NOT_TRADEABLE_FOR_BUSINESS_UNIT 122
#define ENUM_QUOTE_ENTRY_REJECT_REASON_QUANTITY_LIMIT_EXCEEDED 125
#define ENUM_QUOTE_ENTRY_REJECT_REASON_VALUE_LIMIT_EXCEEDED 126
#define ENUM_QUOTE_ENTRY_REJECT_REASON_INVALID_QUOTE_SPREAD 127
#define ENUM_QUOTE_ENTRY_REJECT_REASON_CANT_PROC_IN_CURR_INSTR_STATE 131
#define ENUM_QUOTE_ENTRY_REJECT_REASON_PWT_QUOTENOTALLOWEDINCURRENTSTATE 135
#define ENUM_QUOTE_ENTRY_REJECT_REASON_STANDARD_QUOTENOTALLOWEDINCURRENTSTATE 136
#define ENUM_QUOTE_ENTRY_REJECT_REASON_PWT_QUOTENOTALLOWEDWITHCROSSEDBOOK 137
#define ENUM_QUOTE_ENTRY_REJECT_REASON_ASKSIDEQUOTENOTALLOWED 138
#define ENUM_QUOTE_ENTRY_REJECT_REASON_ASKSIDEQUOTEWITHQTYNOTALLOWED 139
#define ENUM_QUOTE_ENTRY_REJECT_REASON_INVALIDCHANGE_L_PSESSION 140
#define ENUM_QUOTE_ENTRY_REJECT_REASON_ON_BOOK_TRADINGDISABLEDFOR_INSTRUMENT_TYPE 144
#define ENUM_QUOTE_ENTRY_REJECT_REASON_L_PLICENCENOTASSIGNED 145
#define ENUM_QUOTE_ENTRY_REJECT_REASON_S_PLICENCENOTASSIGNED 146
#define ENUM_QUOTE_ENTRY_REJECT_REASON_LIQUIDITYPROVIDERPROTECTIONBIDSIDECANCELLED 147
#define ENUM_QUOTE_ENTRY_REJECT_REASON_LIQUIDITYPROVIDERPROTECTIONASKSIDECANCELLED 148
#define ENUM_QUOTE_ENTRY_REJECT_REASON_QUANTITY_LIMIT_EXCEEDED_INSTRUMENT 149
#define ENUM_QUOTE_ENTRY_REJECT_REASON_VALUE_LIMIT_EXCEEDED_INSTRUMENT 150
#define ENUM_QUOTE_ENTRY_REJECT_REASON_QUOTE_ENTRY_REJECT_REASON_MAXIMUM_VALUE 65535
#define ENUM_QUOTE_ENTRY_REJECT_REASON_QUOTE_ENTRY_REJECT_REASON_MINIMUM_VALUE 0

/*
 * Quote Entry Status Values
 */ 
#define ENUM_QUOTE_ENTRY_STATUS_ACCEPTED 0
#define ENUM_QUOTE_ENTRY_STATUS_REJECTED 5
#define ENUM_QUOTE_ENTRY_STATUS_REMOVEDAND_REJECTED 6
#define ENUM_QUOTE_ENTRY_STATUS_PENDING 10
#define ENUM_QUOTE_ENTRY_STATUS_QUOTE_ENTRY_STATUS_MAXIMUM_VALUE 100
#define ENUM_QUOTE_ENTRY_STATUS_QUOTE_ENTRY_STATUS_MINIMUM_VALUE 0

/*
 * Quote Event Liquidity Ind Values
 */ 
#define ENUM_QUOTE_EVENT_LIQUIDITY_IND_ADDED_LIQUIDITY 1
#define ENUM_QUOTE_EVENT_LIQUIDITY_IND_REMOVED_LIQUIDITY 2
#define ENUM_QUOTE_EVENT_LIQUIDITY_IND_AUCTION 4
#define ENUM_QUOTE_EVENT_LIQUIDITY_IND_QUOTE_EVENT_LIQUIDITY_IND_MAXIMUM_VALUE 4
#define ENUM_QUOTE_EVENT_LIQUIDITY_IND_QUOTE_EVENT_LIQUIDITY_IND_MINIMUM_VALUE 1

/*
 * Quote Event Reason Values
 */ 
#define ENUM_QUOTE_EVENT_REASON_PENDINGCANCELLATIONEXECUTED 14
#define ENUM_QUOTE_EVENT_REASON_INVALIDPRICE 15
#define ENUM_QUOTE_EVENT_REASON_CROSSREJECTED 16
#define ENUM_QUOTE_EVENT_REASON_PLP 18
#define ENUM_QUOTE_EVENT_REASON_PRICENOT_TOPOF_BOOK 19
#define ENUM_QUOTE_EVENT_REASON_RANDOM_SELECTION 20
#define ENUM_QUOTE_EVENT_REASON_MANUAL_SELECTION 21
#define ENUM_QUOTE_EVENT_REASON_QUOTE_EVENT_REASON_MAXIMUM_VALUE 21
#define ENUM_QUOTE_EVENT_REASON_QUOTE_EVENT_REASON_MINIMUM_VALUE 14

/*
 * Quote Event Side Values
 */ 
#define ENUM_QUOTE_EVENT_SIDE_BUY 1
#define ENUM_QUOTE_EVENT_SIDE_SELL 2
#define ENUM_QUOTE_EVENT_SIDE_QUOTE_EVENT_SIDE_MAXIMUM_VALUE 2
#define ENUM_QUOTE_EVENT_SIDE_QUOTE_EVENT_SIDE_MINIMUM_VALUE 1

/*
 * Quote Event Type Values
 */ 
#define ENUM_QUOTE_EVENT_TYPE_MODIFIEDQUOTESIDE 2
#define ENUM_QUOTE_EVENT_TYPE_REMOVEDQUOTESIDE 3
#define ENUM_QUOTE_EVENT_TYPE_PARTIALLYFILLED 4
#define ENUM_QUOTE_EVENT_TYPE_FILLED 5
#define ENUM_QUOTE_EVENT_TYPE_QUOTE_EVENT_TYPE_MAXIMUM_VALUE 5
#define ENUM_QUOTE_EVENT_TYPE_QUOTE_EVENT_TYPE_MINIMUM_VALUE 0

/*
 * Quote Size Type Values
 */ 
#define ENUM_QUOTE_SIZE_TYPE_TOTAL_SIZE 1
#define ENUM_QUOTE_SIZE_TYPE_OPEN_SIZE 2
#define ENUM_QUOTE_SIZE_TYPE_QUOTE_SIZE_TYPE_MAXIMUM_VALUE 2
#define ENUM_QUOTE_SIZE_TYPE_QUOTE_SIZE_TYPE_MINIMUM_VALUE 1

/*
 * Quote Status Values
 */ 
#define ENUM_QUOTE_STATUS_REMOVED 6
#define ENUM_QUOTE_STATUS_EXPIRED 7
#define ENUM_QUOTE_STATUS_ACTIVE 16
#define ENUM_QUOTE_STATUS_QUOTE_STATUS_MAXIMUM_VALUE 17
#define ENUM_QUOTE_STATUS_QUOTE_STATUS_MINIMUM_VALUE 6

/*
 * Quote Type Values
 */ 
#define ENUM_QUOTE_TYPE_TRADEABLE 1
#define ENUM_QUOTE_TYPE_TRADEABLE_MATCHING 101
#define ENUM_QUOTE_TYPE_TRADEABLE_PWT 102
#define ENUM_QUOTE_TYPE_QUOTE_TYPE_MAXIMUM_VALUE 102
#define ENUM_QUOTE_TYPE_QUOTE_TYPE_MINIMUM_VALUE 0

/*
 * Quoting Status Values
 */ 
#define ENUM_QUOTING_STATUS_OPEN_ACTIVE 1
#define ENUM_QUOTING_STATUS_OPEN_IDLE 2
#define ENUM_QUOTING_STATUS_CLOSED_INACTIVE 3
#define ENUM_QUOTING_STATUS_OPEN_NOT_RESPONDED 4
#define ENUM_QUOTING_STATUS_QUOTING_STATUS_MAXIMUM_VALUE 4
#define ENUM_QUOTING_STATUS_QUOTING_STATUS_MINIMUM_VALUE 0

/*
 * Ref Appl Id Values
 */ 
#define ENUM_REF_APPL_ID_TRADE 1
#define ENUM_REF_APPL_ID_NEWS 2
#define ENUM_REF_APPL_ID_SERVICEAVAILABILITY 3
#define ENUM_REF_APPL_ID_SESSIONDATA 4
#define ENUM_REF_APPL_ID_LISTENERDATA 5
#define ENUM_REF_APPL_ID_RISK_CONTROL 6
#define ENUM_REF_APPL_ID_TES_MAINTENANCE 7
#define ENUM_REF_APPL_ID_TES_TRADE 8
#define ENUM_REF_APPL_ID_SRQS_MAINTENANCE 9
#define ENUM_REF_APPL_ID_SERVICE_AVAILABILITY_MARKET 10
#define ENUM_REF_APPL_ID_REF_APPL_ID_MAXIMUM_VALUE 10
#define ENUM_REF_APPL_ID_REF_APPL_ID_MINIMUM_VALUE 0

/*
 * Refinancing Eligibility Indicator Values
 */ 
#define ENUM_REFINANCING_ELIGIBILITY_INDICATOR_NO 0
#define ENUM_REFINANCING_ELIGIBILITY_INDICATOR_YES 1
#define ENUM_REFINANCING_ELIGIBILITY_INDICATOR_REFINANCING_ELIGIBILITY_INDICATOR_MAXIMUM_VALUE 1
#define ENUM_REFINANCING_ELIGIBILITY_INDICATOR_REFINANCING_ELIGIBILITY_INDICATOR_MINIMUM_VALUE 0

/*
 * Requesting Party Id Entering Firm Values
 */ 
#define ENUM_REQUESTING_PARTY_ID_ENTERING_FIRM_PARTICIPANT 1
#define ENUM_REQUESTING_PARTY_ID_ENTERING_FIRM_MARKET_SUPERVISION 2
#define ENUM_REQUESTING_PARTY_ID_ENTERING_FIRM_REQUESTING_PARTY_ID_ENTERING_FIRM_MAXIMUM_VALUE 2
#define ENUM_REQUESTING_PARTY_ID_ENTERING_FIRM_REQUESTING_PARTY_ID_ENTERING_FIRM_MINIMUM_VALUE 1

/*
 * Requesting Party Id Executing System Values
 */ 
#define ENUM_REQUESTING_PARTY_ID_EXECUTING_SYSTEM_T7 2
#define ENUM_REQUESTING_PARTY_ID_EXECUTING_SYSTEM_REQUESTING_PARTY_ID_EXECUTING_SYSTEM_MAXIMUM_VALUE 4294967294
#define ENUM_REQUESTING_PARTY_ID_EXECUTING_SYSTEM_REQUESTING_PARTY_ID_EXECUTING_SYSTEM_MINIMUM_VALUE 0

/*
 * Respondent Type Values
 */ 
#define ENUM_RESPONDENT_TYPE_SPECIFIEDMARKETPARTICIPANTS 2
#define ENUM_RESPONDENT_TYPE_SPECIFIEDAND_SMART_RF_QSELECTEDPARTICIPANTS 100
#define ENUM_RESPONDENT_TYPE_SMART_RF_QSELECTEDPARTICIPANTS 101
#define ENUM_RESPONDENT_TYPE_RESPONDENT_TYPE_MAXIMUM_VALUE 101
#define ENUM_RESPONDENT_TYPE_RESPONDENT_TYPE_MINIMUM_VALUE 2

/*
 * Rfq Publish Indicator Values
 */ 
#define ENUM_RFQ_PUBLISH_INDICATOR_MARKET_DATA 1
#define ENUM_RFQ_PUBLISH_INDICATOR_DESIGNATED_SPONSOR 2
#define ENUM_RFQ_PUBLISH_INDICATOR_MARKET_DATAAND_DESIGNATED_SPONSOR 3
#define ENUM_RFQ_PUBLISH_INDICATOR_MARKET_MAKERAND_DESIGNATED_SPONSOR 4
#define ENUM_RFQ_PUBLISH_INDICATOR_MARKET_DATAAND_MARKET_MAKERAND_DESIGNATED_SPONSOR 5
#define ENUM_RFQ_PUBLISH_INDICATOR_RFQ_PUBLISH_INDICATOR_MAXIMUM_VALUE 5
#define ENUM_RFQ_PUBLISH_INDICATOR_RFQ_PUBLISH_INDICATOR_MINIMUM_VALUE 1

/*
 * Rfq Requester Disclosure Instruction Values
 */ 
#define ENUM_RFQ_REQUESTER_DISCLOSURE_INSTRUCTION_NO 0
#define ENUM_RFQ_REQUESTER_DISCLOSURE_INSTRUCTION_YES 1
#define ENUM_RFQ_REQUESTER_DISCLOSURE_INSTRUCTION_RFQ_REQUESTER_DISCLOSURE_INSTRUCTION_MAXIMUM_VALUE 1
#define ENUM_RFQ_REQUESTER_DISCLOSURE_INSTRUCTION_RFQ_REQUESTER_DISCLOSURE_INSTRUCTION_MINIMUM_VALUE 0

/*
 * Root Party Id Investment Decision Maker Qualifier Values
 */ 
#define ENUM_ROOT_PARTY_ID_INVESTMENT_DECISION_MAKER_QUALIFIER_ALGO 22
#define ENUM_ROOT_PARTY_ID_INVESTMENT_DECISION_MAKER_QUALIFIER_HUMAN 24
#define ENUM_ROOT_PARTY_ID_INVESTMENT_DECISION_MAKER_QUALIFIER_ROOT_PARTY_ID_INVESTMENT_DECISION_MAKER_QUALIFIER_MAXIMUM_VALUE 24
#define ENUM_ROOT_PARTY_ID_INVESTMENT_DECISION_MAKER_QUALIFIER_ROOT_PARTY_ID_INVESTMENT_DECISION_MAKER_QUALIFIER_MINIMUM_VALUE 22

/*
 * Security Status Values
 */ 
#define ENUM_SECURITY_STATUS_KNOCKEDOUT 6
#define ENUM_SECURITY_STATUS_KNOCKOUTREVOKED 7
#define ENUM_SECURITY_STATUS_KNOCKEDOUTANDSUSPEND 12
#define ENUM_SECURITY_STATUS_SECURITY_STATUS_MAXIMUM_VALUE 12
#define ENUM_SECURITY_STATUS_SECURITY_STATUS_MINIMUM_VALUE 6

/*
 * Security Trading Status Values
 */ 
#define ENUM_SECURITY_TRADING_STATUS_MARKET_IMBALANCE_BUY 7
#define ENUM_SECURITY_TRADING_STATUS_MARKET_IMBALANCE_SELL 8
#define ENUM_SECURITY_TRADING_STATUS_SECURITY_TRADING_STATUS_MAXIMUM_VALUE 8
#define ENUM_SECURITY_TRADING_STATUS_SECURITY_TRADING_STATUS_MINIMUM_VALUE 7

/*
 * Selective Request For Quote Service Status Values
 */ 
#define ENUM_SELECTIVE_REQUEST_FOR_QUOTE_SERVICE_STATUS_UNAVAILABLE 0
#define ENUM_SELECTIVE_REQUEST_FOR_QUOTE_SERVICE_STATUS_AVAILABLE 1
#define ENUM_SELECTIVE_REQUEST_FOR_QUOTE_SERVICE_STATUS_SELECTIVE_REQUEST_FOR_QUOTE_SERVICE_STATUS_MAXIMUM_VALUE 1
#define ENUM_SELECTIVE_REQUEST_FOR_QUOTE_SERVICE_STATUS_SELECTIVE_REQUEST_FOR_QUOTE_SERVICE_STATUS_MINIMUM_VALUE 0

/*
 * Session Mode Values
 */ 
#define ENUM_SESSION_MODE_HF 1
#define ENUM_SESSION_MODE_LF 2
#define ENUM_SESSION_MODE_GUI 3
#define ENUM_SESSION_MODE_SESSION_MODE_MAXIMUM_VALUE 3
#define ENUM_SESSION_MODE_SESSION_MODE_MINIMUM_VALUE 1

/*
 * Session Reject Reason Values
 */ 
#define ENUM_SESSION_REJECT_REASON_REQUIRED_TAG_MISSING 1
#define ENUM_SESSION_REJECT_REASON_VALUEISINCORRECT 5
#define ENUM_SESSION_REJECT_REASON_DECRYPTIONPROBLEM 7
#define ENUM_SESSION_REJECT_REASON_INVALID_MSG_ID 11
#define ENUM_SESSION_REJECT_REASON_INCORRECT_NUM_IN_GROUPCOUNT 16
#define ENUM_SESSION_REJECT_REASON_OTHER 99
#define ENUM_SESSION_REJECT_REASON_THROTTLE_LIMIT_EXCEEDED 100
#define ENUM_SESSION_REJECT_REASON_EXPOSURE_LIMIT_EXCEEDED 101
#define ENUM_SESSION_REJECT_REASON_SERVICE_TEMPORARILY_NOT_AVAILABLE 102
#define ENUM_SESSION_REJECT_REASON_SERVICE_NOT_AVAILABLE 103
#define ENUM_SESSION_REJECT_REASON_OUTBOUNDCONVERSIONERROR 105
#define ENUM_SESSION_REJECT_REASON_HEARTBEAT_VIOLATION 152
#define ENUM_SESSION_REJECT_REASON_INTERNALTECHNICALERROR 200
#define ENUM_SESSION_REJECT_REASON_VALIDATION_ERROR 210
#define ENUM_SESSION_REJECT_REASON_USER_ALREADY_LOGGED_IN 211
#define ENUM_SESSION_REJECT_REASON_GATEWAY_IS_STANDBY 216
#define ENUM_SESSION_REJECT_REASON_SESSION_LOGIN_LIMIT_REACHED 217
#define ENUM_SESSION_REJECT_REASON_USER_ENTITLEMENT_DATA_TIMEOUT 223
#define ENUM_SESSION_REJECT_REASON_PS_GATEWAY_SESSION_LIMIT_REACHED 224
#define ENUM_SESSION_REJECT_REASON_USER_LOGIN_LIMIT_REACHED 225
#define ENUM_SESSION_REJECT_REASON_OUTSTANDING_LOGINS_BU_LIMIT_REACHED 226
#define ENUM_SESSION_REJECT_REASON_OUTSTANDING_LOGINS_SESSION_LIMIT_REACHED 227
#define ENUM_SESSION_REJECT_REASON_ORDER_NOT_FOUND 10000
#define ENUM_SESSION_REJECT_REASON_PRICE_NOT_REASONABLE 10001
#define ENUM_SESSION_REJECT_REASON_CLIENT_ORDER_ID_NOT_UNIQUE 10002
#define ENUM_SESSION_REJECT_REASON_QUOTE_ACTIVATION_IN_PROGRESS 10003
#define ENUM_SESSION_REJECT_REASON_BU_BOOK_ORDER_LIMIT_EXCEEDED 10004
#define ENUM_SESSION_REJECT_REASON_SESSION_BOOK_ORDER_LIMIT_EXCEEDED 10005
#define ENUM_SESSION_REJECT_REASON_STOP_BID_PRICE_NOT_REASONABLE 10006
#define ENUM_SESSION_REJECT_REASON_STOP_ASK_PRICE_NOT_REASONABLE 10007
#define ENUM_SESSION_REJECT_REASON_ORDER_NOT_EXECUTABLE_WITHIN_VALIDITY 10008
#define ENUM_SESSION_REJECT_REASON_INVALID_TRADING_RESTRICTION_FOR_INSTRUMENT_STATE 10009
#define ENUM_SESSION_REJECT_REASON_TRANSACTION_NOT_ALLOWED_IN_CURRENT_STATE 10011
#define ENUM_SESSION_REJECT_REASON_SESSION_REJECT_REASON_MAXIMUM_VALUE 4294967294
#define ENUM_SESSION_REJECT_REASON_SESSION_REJECT_REASON_MINIMUM_VALUE 0

/*
 * Session Status Values
 */ 
#define ENUM_SESSION_STATUS_ACTIVE 0
#define ENUM_SESSION_STATUS_LOGOUT 4
#define ENUM_SESSION_STATUS_SESSION_STATUS_MAXIMUM_VALUE 4
#define ENUM_SESSION_STATUS_SESSION_STATUS_MINIMUM_VALUE 0

/*
 * Session Sub Mode Values
 */ 
#define ENUM_SESSION_SUB_MODE_REGULARTRADINGSESSION 0
#define ENUM_SESSION_SUB_MODE_FI_XTRADINGSESSION 1
#define ENUM_SESSION_SUB_MODE_REGULAR_BACK_OFFICESESSION 2
#define ENUM_SESSION_SUB_MODE_SESSION_SUB_MODE_MAXIMUM_VALUE 2
#define ENUM_SESSION_SUB_MODE_SESSION_SUB_MODE_MINIMUM_VALUE 0

/*
 * Side Values
 */ 
#define ENUM_SIDE_BUY 1
#define ENUM_SIDE_SELL 2
#define ENUM_SIDE_SIDE_MAXIMUM_VALUE 2
#define ENUM_SIDE_SIDE_MINIMUM_VALUE 1

/*
 * Side Liquidity Ind Values
 */ 
#define ENUM_SIDE_LIQUIDITY_IND_ADDED_LIQUIDITY 1
#define ENUM_SIDE_LIQUIDITY_IND_REMOVED_LIQUIDITY 2
#define ENUM_SIDE_LIQUIDITY_IND_AUCTION 4
#define ENUM_SIDE_LIQUIDITY_IND_SIDE_LIQUIDITY_IND_MAXIMUM_VALUE 4
#define ENUM_SIDE_LIQUIDITY_IND_SIDE_LIQUIDITY_IND_MINIMUM_VALUE 1

/*
 * Sold Out Indicator Values
 */ 
#define ENUM_SOLD_OUT_INDICATOR_REVERTSOLDOUT 0
#define ENUM_SOLD_OUT_INDICATOR_SOLDOUT 1
#define ENUM_SOLD_OUT_INDICATOR_SOLD_OUT_INDICATOR_MAXIMUM_VALUE 1
#define ENUM_SOLD_OUT_INDICATOR_SOLD_OUT_INDICATOR_MINIMUM_VALUE 0

/*
 * Stop Px Indicator Values
 */ 
#define ENUM_STOP_PX_INDICATOR_DONOTOVERWRITE 0
#define ENUM_STOP_PX_INDICATOR_OVERWRITE 1
#define ENUM_STOP_PX_INDICATOR_STOP_PX_INDICATOR_MAXIMUM_VALUE 1
#define ENUM_STOP_PX_INDICATOR_STOP_PX_INDICATOR_MINIMUM_VALUE 0

/*
 * T 7 Entry Service Rtm Status Values
 */ 
#define ENUM_T7_ENTRY_SERVICE_RTM_STATUS_UNAVAILABLE 0
#define ENUM_T7_ENTRY_SERVICE_RTM_STATUS_AVAILABLE 1
#define ENUM_T7_ENTRY_SERVICE_RTM_STATUS_T7_ENTRY_SERVICE_RTM_STATUS_MAXIMUM_VALUE 1
#define ENUM_T7_ENTRY_SERVICE_RTM_STATUS_T7_ENTRY_SERVICE_RTM_STATUS_MINIMUM_VALUE 0

/*
 * T 7 Entry Service Status Values
 */ 
#define ENUM_T7_ENTRY_SERVICE_STATUS_UNAVAILABLE 0
#define ENUM_T7_ENTRY_SERVICE_STATUS_AVAILABLE 1
#define ENUM_T7_ENTRY_SERVICE_STATUS_T7_ENTRY_SERVICE_STATUS_MAXIMUM_VALUE 1
#define ENUM_T7_ENTRY_SERVICE_STATUS_T7_ENTRY_SERVICE_STATUS_MINIMUM_VALUE 0

/*
 * Time In Force Values
 */ 
#define ENUM_TIME_IN_FORCE_DAY 0
#define ENUM_TIME_IN_FORCE_GTC 1
#define ENUM_TIME_IN_FORCE_IOC 3
#define ENUM_TIME_IN_FORCE_FOK 4
#define ENUM_TIME_IN_FORCE_GTX 5
#define ENUM_TIME_IN_FORCE_GTD 6
#define ENUM_TIME_IN_FORCE_TIME_IN_FORCE_MAXIMUM_VALUE 6
#define ENUM_TIME_IN_FORCE_TIME_IN_FORCE_MINIMUM_VALUE 0

/*
 * Trad Ses Event Values
 */ 
#define ENUM_TRAD_SES_EVENT_STARTOF_SERVICE 101
#define ENUM_TRAD_SES_EVENT_MARKET_RESET 102
#define ENUM_TRAD_SES_EVENT_ENDOF_RESTATEMENT 103
#define ENUM_TRAD_SES_EVENT_ENDOF_DAY_SERVICE 104
#define ENUM_TRAD_SES_EVENT_SERVICE_RESUMED 105
#define ENUM_TRAD_SES_EVENT_TRAD_SES_EVENT_MAXIMUM_VALUE 105
#define ENUM_TRAD_SES_EVENT_TRAD_SES_EVENT_MINIMUM_VALUE 100

/*
 * Trad Ses Mode Values
 */ 
#define ENUM_TRAD_SES_MODE_TESTING 1
#define ENUM_TRAD_SES_MODE_SIMULATED 2
#define ENUM_TRAD_SES_MODE_PRODUCTION 3
#define ENUM_TRAD_SES_MODE_ACCEPTANCE 4
#define ENUM_TRAD_SES_MODE_DISASTER_RECOVERY 5
#define ENUM_TRAD_SES_MODE_TRAD_SES_MODE_MAXIMUM_VALUE 5
#define ENUM_TRAD_SES_MODE_TRAD_SES_MODE_MINIMUM_VALUE 1

/*
 * Trade Alloc Status Values
 */ 
#define ENUM_TRADE_ALLOC_STATUS_PENDING 1
#define ENUM_TRADE_ALLOC_STATUS_APPROVED 2
#define ENUM_TRADE_ALLOC_STATUS_AUTO_APPROVED 3
#define ENUM_TRADE_ALLOC_STATUS_UPLOADED 4
#define ENUM_TRADE_ALLOC_STATUS_CANCELED 5
#define ENUM_TRADE_ALLOC_STATUS_TRADE_ALLOC_STATUS_MAXIMUM_VALUE 5
#define ENUM_TRADE_ALLOC_STATUS_TRADE_ALLOC_STATUS_MINIMUM_VALUE 0

/*
 * Trade Manager Status Values
 */ 
#define ENUM_TRADE_MANAGER_STATUS_UNAVAILABLE 0
#define ENUM_TRADE_MANAGER_STATUS_AVAILABLE 1
#define ENUM_TRADE_MANAGER_STATUS_TRADE_MANAGER_STATUS_MAXIMUM_VALUE 1
#define ENUM_TRADE_MANAGER_STATUS_TRADE_MANAGER_STATUS_MINIMUM_VALUE 0

/*
 * Trade Publish Indicator Values
 */ 
#define ENUM_TRADE_PUBLISH_INDICATOR_DEFERRED_PUBLICATION 2
#define ENUM_TRADE_PUBLISH_INDICATOR_PUBLISHED 3
#define ENUM_TRADE_PUBLISH_INDICATOR_TRADE_PUBLISH_INDICATOR_MAXIMUM_VALUE 3
#define ENUM_TRADE_PUBLISH_INDICATOR_TRADE_PUBLISH_INDICATOR_MINIMUM_VALUE 0

/*
 * Trade Report Type Values
 */ 
#define ENUM_TRADE_REPORT_TYPE_SUBMIT 0
#define ENUM_TRADE_REPORT_TYPE_ACCEPT 2
#define ENUM_TRADE_REPORT_TYPE_DECLINE 3
#define ENUM_TRADE_REPORT_TYPE_NO_WAS_REPLACED 5
#define ENUM_TRADE_REPORT_TYPE_TRADE_REPORT_CANCEL 6
#define ENUM_TRADE_REPORT_TYPE_TRADE_BREAK 7
#define ENUM_TRADE_REPORT_TYPE_ALLEGED_NEW 11
#define ENUM_TRADE_REPORT_TYPE_ALLEGED_NO_WAS 13
#define ENUM_TRADE_REPORT_TYPE_TRADE_REPORT_TYPE_MAXIMUM_VALUE 13
#define ENUM_TRADE_REPORT_TYPE_TRADE_REPORT_TYPE_MINIMUM_VALUE 0

/*
 * Trading Capacity Values
 */ 
#define ENUM_TRADING_CAPACITY_CUSTOMER 1
#define ENUM_TRADING_CAPACITY_PRINCIPAL 5
#define ENUM_TRADING_CAPACITY_MARKET_MAKER 6
#define ENUM_TRADING_CAPACITY_SYSTEMATIC_INTERNALISER 8
#define ENUM_TRADING_CAPACITY_RISKLESS_PRINCIPAL 9
#define ENUM_TRADING_CAPACITY_TRADING_CAPACITY_MAXIMUM_VALUE 9
#define ENUM_TRADING_CAPACITY_TRADING_CAPACITY_MINIMUM_VALUE 1

/*
 * Trading Session Sub Id Values
 */ 
#define ENUM_TRADING_SESSION_SUB_ID_OPENINGAUCTION 2
#define ENUM_TRADING_SESSION_SUB_ID_CLOSINGAUCTION 4
#define ENUM_TRADING_SESSION_SUB_ID_INTRADAY_AUCTION 6
#define ENUM_TRADING_SESSION_SUB_ID_ANY_AUCTION 8
#define ENUM_TRADING_SESSION_SUB_ID_TRADING_SESSION_SUB_ID_MAXIMUM_VALUE 8
#define ENUM_TRADING_SESSION_SUB_ID_TRADING_SESSION_SUB_ID_MINIMUM_VALUE 1

/*
 * Transaction Delay Indicator Values
 */ 
#define ENUM_TRANSACTION_DELAY_INDICATOR_NOTDELAYED 0
#define ENUM_TRANSACTION_DELAY_INDICATOR_DELAYED 1
#define ENUM_TRANSACTION_DELAY_INDICATOR_TRANSACTION_DELAY_INDICATOR_MAXIMUM_VALUE 1
#define ENUM_TRANSACTION_DELAY_INDICATOR_TRANSACTION_DELAY_INDICATOR_MINIMUM_VALUE 0

/*
 * Transfer Reason Values
 */ 
#define ENUM_TRANSFER_REASON_OWNER 1
#define ENUM_TRANSFER_REASON_CLEARER 2
#define ENUM_TRANSFER_REASON_TRANSFER_REASON_MAXIMUM_VALUE 5
#define ENUM_TRANSFER_REASON_TRANSFER_REASON_MINIMUM_VALUE 1

/*
 * Trd Rpt Status Values
 */ 
#define ENUM_TRD_RPT_STATUS_ACCEPTED 0
#define ENUM_TRD_RPT_STATUS_REJECTED 1
#define ENUM_TRD_RPT_STATUS_CANCELLED 2
#define ENUM_TRD_RPT_STATUS_PENDING_NEW 4
#define ENUM_TRD_RPT_STATUS_TERMINATED 7
#define ENUM_TRD_RPT_STATUS_DEEMED_VERIFIED 9
#define ENUM_TRD_RPT_STATUS_TRD_RPT_STATUS_MAXIMUM_VALUE 9
#define ENUM_TRD_RPT_STATUS_TRD_RPT_STATUS_MINIMUM_VALUE 0

/*
 * Trd Type Values
 */ 
#define ENUM_TRD_TYPE_OTC 54
#define ENUM_TRD_TYPE_LIS 1005
#define ENUM_TRD_TYPE_ENLIGHT 1006
#define ENUM_TRD_TYPE_TRD_TYPE_MAXIMUM_VALUE 1010
#define ENUM_TRD_TYPE_TRD_TYPE_MINIMUM_VALUE 1

/*
 * Triggered Values
 */ 
#define ENUM_TRIGGERED_NOTTRIGGERED 0
#define ENUM_TRIGGERED_TRIGGERED_STOP 1
#define ENUM_TRIGGERED_TRIGGERED_OCO 2
#define ENUM_TRIGGERED_TRIGGERED_MAXIMUM_VALUE 2
#define ENUM_TRIGGERED_TRIGGERED_MINIMUM_VALUE 0

/*
 * User Status Values
 */ 
#define ENUM_USER_STATUS_USERFORCEDLOGOUT 7
#define ENUM_USER_STATUS_USERSTOPPED 10
#define ENUM_USER_STATUS_USERRELEASED 11
#define ENUM_USER_STATUS_USER_STATUS_MAXIMUM_VALUE 11
#define ENUM_USER_STATUS_USER_STATUS_MINIMUM_VALUE 7

/*
 * Value Check Type Quantity Values
 */ 
#define ENUM_VALUE_CHECK_TYPE_QUANTITY_DONOTCHECK 0
#define ENUM_VALUE_CHECK_TYPE_QUANTITY_CHECK 1
#define ENUM_VALUE_CHECK_TYPE_QUANTITY_VALUE_CHECK_TYPE_QUANTITY_MAXIMUM_VALUE 1
#define ENUM_VALUE_CHECK_TYPE_QUANTITY_VALUE_CHECK_TYPE_QUANTITY_MINIMUM_VALUE 0

/*
 * Value Check Type Value Values
 */ 
#define ENUM_VALUE_CHECK_TYPE_VALUE_DONOTCHECK 0
#define ENUM_VALUE_CHECK_TYPE_VALUE_CHECK 1
#define ENUM_VALUE_CHECK_TYPE_VALUE_VALUE_CHECK_TYPE_VALUE_MAXIMUM_VALUE 1
#define ENUM_VALUE_CHECK_TYPE_VALUE_VALUE_CHECK_TYPE_VALUE_MINIMUM_VALUE 0


/*******************************************************************************
 * Structs
 *******************************************************************************/

#pragma pack(push, 1)

/*
 * Structure: Xetra En Light Target Parties Comp
 */ 
typedef struct {
    uint32_t TargetPartyIdExecutingTrader;
    char TargetPartyExecutingFirm[5];
    char TargetPartyExecutingTrader[6];
    char Pad1[1];
} XetraEnLightTargetPartiesCompT;

/*
 * Structure: Request Header Comp
 */ 
typedef struct {
    uint32_t MsgSeqNum;
    uint32_t SenderSubId;
} RequestHeaderCompT;

/*
 * Structure: Xetra En Light Update Negotiation Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    uint64_t BidPx;
    uint64_t OfferPx;
    uint64_t OrderQty;
    int32_t MarketSegmentId;
    uint32_t NegotiationId;
    uint32_t SettlDate;
    uint8_t NoTargetPartyIDs;
    uint8_t NumberOfRespDisclosureInstruction;
    uint8_t Side;
    uint8_t QuoteCancelType;
    char PartyExecutingFirm[5];
    char PartyExecutingTrader[6];
    char FreeText5[132];
    char Pad1[1];
} XetraEnLightUpdateNegotiationRequestT;

/*
 * Structure: Rbc Header Comp
 */ 
typedef struct {
    uint64_t SendingTime;
    uint64_t ApplSeqNum;
    uint32_t ApplSubId;
    uint16_t PartitionId;
    uint8_t ApplResendFlag;
    uint8_t ApplId;
    uint8_t LastFragment;
    char Pad7[7];
} RbcHeaderCompT;

/*
 * Structure: Xetra En Light Status Broadcast
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderCompT RbcHeaderComp;
    uint32_t TradeDate;
    uint8_t TradSesEvent;
    char Pad3[3];
} XetraEnLightStatusBroadcastT;

/*
 * Structure: Xetra En Light Quoting Status Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    int32_t MarketSegmentId;
    uint32_t NegotiationId;
    uint8_t QuotingStatus;
    char PartyExecutingFirm[5];
    char PartyExecutingTrader[6];
    char Pad4[4];
} XetraEnLightQuotingStatusRequestT;

/*
 * Structure: Response Header Comp
 */ 
typedef struct {
    uint64_t RequestTime;
    uint64_t SendingTime;
    uint32_t MsgSeqNum;
    char Pad4[4];
} ResponseHeaderCompT;

/*
 * Structure: Xetra En Light Quote Response
 */ 
typedef struct {
    char Pad2[2];
    ResponseHeaderCompT ResponseHeaderComp;
    uint64_t QuoteId;
    uint32_t NegotiationId;
    char QuoteReqId[20];
} XetraEnLightQuoteResponseT;

/*
 * Structure: Srqs Quote Entry Grp Comp
 */ 
typedef struct {
    uint64_t TransactTime;
    uint64_t QuoteId;
    uint64_t SecondaryQuoteId;
    uint64_t BidPx;
    uint64_t BidSize;
    uint64_t OfferPx;
    uint64_t OfferSize;
    uint32_t PartyIdExecutingTrader;
    uint8_t QuotingStatus;
    char PartyExecutingFirm[5];
    char PartyExecutingTrader[6];
    char PartyEnteringTrader[6];
    char Pad2[2];
} SrqsQuoteEntryGrpCompT;

/*
 * Structure: Xetra En Light Quote Requester Notification
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderCompT RbcHeaderComp;
    uint64_t TransactTime;
    uint32_t NegotiationId;
    uint32_t TradeId;
    char QuoteReqId[20];
    uint8_t NoQuoteEntries;
    char Pad3[3];
} XetraEnLightQuoteRequesterNotificationT;

/*
 * Structure: Xetra En Light Quote Notification
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderCompT RbcHeaderComp;
    uint64_t TransactTime;
    uint64_t QuoteId;
    uint64_t SecondaryQuoteId;
    uint64_t BidPx;
    uint64_t BidSize;
    uint64_t OfferPx;
    uint64_t OfferSize;
    uint32_t NegotiationId;
    uint8_t TradingCapacity;
    uint8_t QuotingStatus;
    uint8_t QuoteEventReason;
    char PartyExecutingFirm[5];
    char PartyExecutingTrader[6];
    char PartyEnteringTrader[6];
    char QuoteReqId[20];
    char FreeText1[12];
    char FreeText2[12];
    char FreeText4[16];
    char Pad4[4];
} XetraEnLightQuoteNotificationT;

/*
 * Structure: Xetra En Light Open Negotiation Requester Notification
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderCompT RbcHeaderComp;
    uint64_t TransactTime;
    int64_t SecurityId;
    uint64_t BidPx;
    uint64_t OfferPx;
    uint64_t OrderQty;
    uint64_t LastPx;
    uint64_t LastQty;
    uint64_t ExpireTime;
    uint32_t NegotiationId;
    int32_t MarketSegmentId;
    uint32_t NumberOfRespondents;
    uint32_t SettlDate;
    uint8_t QuoteStatus;
    uint8_t NoTargetPartyIDs;
    uint8_t Side;
    uint8_t NumberOfRespDisclosureInstruction;
    uint8_t RespondentType;
    char PartyExecutingFirm[5];
    char PartyExecutingTrader[6];
    char PartyEnteringTrader[6];
    char FirmNegotiationId[20];
    char FreeText5[132];
    char Pad2[2];
} XetraEnLightOpenNegotiationRequesterNotificationT;

/*
 * Structure: Xetra En Light Open Negotiation Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    int64_t SecurityId;
    uint64_t BidPx;
    uint64_t OfferPx;
    uint64_t OrderQty;
    uint64_t ValidUntilTime;
    int32_t MarketSegmentId;
    uint32_t SettlDate;
    uint8_t NoTargetPartyIDs;
    uint8_t NumberOfRespDisclosureInstruction;
    uint8_t Side;
    uint8_t ValueCheckTypeValue;
    uint8_t ValueCheckTypeQuantity;
    uint8_t RespondentType;
    char PartyExecutingFirm[5];
    char PartyExecutingTrader[6];
    char FreeText5[132];
    char QuoteReqId[20];
    char Pad7[7];
} XetraEnLightOpenNegotiationRequestT;

/*
 * Structure: Xetra En Light Open Negotiation Notification
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderCompT RbcHeaderComp;
    uint64_t TransactTime;
    uint64_t NegotiationStartTime;
    int64_t SecurityId;
    uint64_t BidPx;
    uint64_t OfferPx;
    uint64_t LeavesQty;
    uint64_t ExpireTime;
    uint32_t NegotiationId;
    int32_t MarketSegmentId;
    uint32_t NumberOfRespondents;
    uint32_t SettlDate;
    uint8_t QuoteStatus;
    uint8_t Side;
    uint8_t RespondentType;
    char PartyExecutingFirm[5];
    char PartyExecutingTrader[6];
    char PartyEnteringTrader[6];
    char TargetPartyExecutingFirm[5];
    char TargetPartyExecutingTrader[6];
    char FirmNegotiationId[20];
    char FreeText5[132];
    char Pad1[1];
} XetraEnLightOpenNegotiationNotificationT;

/*
 * Structure: Xetra En Light Negotiation Status Notification
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderCompT RbcHeaderComp;
    uint64_t TransactTime;
    uint32_t NegotiationId;
    uint8_t QuoteStatus;
    char FirmNegotiationId[20];
    char Pad7[7];
} XetraEnLightNegotiationStatusNotificationT;

/*
 * Structure: Xetra En Light Negotiation Requester Notification
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderCompT RbcHeaderComp;
    uint64_t TransactTime;
    uint64_t TrdRegTsExecutionTime;
    uint64_t BidPx;
    uint64_t OfferPx;
    uint64_t OrderQty;
    uint64_t LastPx;
    uint64_t LeavesQty;
    uint64_t LastQty;
    uint32_t NegotiationId;
    uint32_t NumberOfRespondents;
    uint32_t SettlDate;
    uint8_t QuoteStatus;
    uint8_t NoTargetPartyIDs;
    uint8_t NumberOfRespDisclosureInstruction;
    uint8_t Side;
    char PartyExecutingFirm[5];
    char PartyExecutingTrader[6];
    char PartyEnteringTrader[6];
    char FirmNegotiationId[20];
    char FreeText5[132];
    char Pad7[7];
} XetraEnLightNegotiationRequesterNotificationT;

/*
 * Structure: Xetra En Light Negotiation Notification
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderCompT RbcHeaderComp;
    uint64_t TransactTime;
    uint64_t BidPx;
    uint64_t OfferPx;
    uint64_t LeavesQty;
    uint32_t NegotiationId;
    uint32_t NumberOfRespondents;
    uint32_t SettlDate;
    uint8_t QuoteStatus;
    uint8_t Side;
    char PartyExecutingFirm[5];
    char PartyExecutingTrader[6];
    char PartyEnteringTrader[6];
    char TargetPartyExecutingFirm[5];
    char TargetPartyExecutingTrader[6];
    char FirmNegotiationId[20];
    char FreeText5[132];
    char Pad6[6];
} XetraEnLightNegotiationNotificationT;

/*
 * Structure: Xetra En Light Hit Quote Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    uint64_t QuoteId;
    uint64_t OrderQty;
    uint64_t Price;
    uint64_t PartyIdClientId;
    uint64_t PartyIdInvestmentDecisionMaker;
    uint64_t ExecutingTrader;
    int32_t MarketSegmentId;
    uint32_t NegotiationId;
    uint8_t Side;
    uint8_t ValueCheckTypeQuantity;
    uint8_t ValueCheckTypeValue;
    uint8_t TradingCapacity;
    uint8_t OrderAttributeLiquidityProvision;
    uint8_t ExecutingTraderQualifier;
    uint8_t AllocMethod;
    uint8_t PartyIdInvestmentDecisionMakerQualifier;
    char PartyExecutingFirm[5];
    char PartyExecutingTrader[6];
    char FirmTradeId[20];
    char FreeText1[12];
    char FreeText2[12];
    char FreeText4[16];
    char Pad1[1];
} XetraEnLightHitQuoteRequestT;

/*
 * Structure: Xetra En Light Enter Quote Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    uint64_t BidPx;
    uint64_t OfferPx;
    uint64_t BidSize;
    uint64_t OfferSize;
    uint64_t PartyIdClientId;
    uint64_t PartyIdInvestmentDecisionMaker;
    uint64_t ExecutingTrader;
    int32_t MarketSegmentId;
    uint32_t NegotiationId;
    uint8_t ValueCheckTypeQuantity;
    uint8_t ValueCheckTypeValue;
    uint8_t TradingCapacity;
    uint8_t OrderAttributeLiquidityProvision;
    uint8_t ExecutingTraderQualifier;
    uint8_t PartyIdInvestmentDecisionMakerQualifier;
    char PartyExecutingFirm[5];
    char PartyExecutingTrader[6];
    char FreeText1[12];
    char FreeText2[12];
    char FreeText4[16];
    char Pad7[7];
} XetraEnLightEnterQuoteRequestT;

/*
 * Structure: Xetra En Light Deal Response
 */ 
typedef struct {
    char Pad2[2];
    ResponseHeaderCompT ResponseHeaderComp;
    int64_t SecurityId;
    uint64_t QuoteId;
    uint32_t NegotiationId;
    uint32_t TradeId;
    uint32_t SecondaryTradeId;
    char FirmTradeId[20];
    char FirmNegotiationId[20];
    char Pad4[4];
} XetraEnLightDealResponseT;

/*
 * Structure: Order Book Item Grp Comp
 */ 
typedef struct {
    uint64_t BestBidPx;
    uint64_t BestBidSize;
    uint64_t BestOfferPx;
    uint64_t BestOfferSize;
    uint8_t MdBookType;
    uint8_t MdSubBookType;
    char Pad6[6];
} OrderBookItemGrpCompT;

/*
 * Structure: Xetra En Light Create Deal Notification
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderCompT RbcHeaderComp;
    uint64_t TransactTime;
    uint64_t LastPx;
    uint64_t LastQty;
    uint64_t QuoteId;
    int64_t SecurityId;
    uint64_t PartyIdClientId;
    uint64_t PartyIdInvestmentDecisionMaker;
    uint64_t ExecutingTrader;
    uint32_t NegotiationId;
    uint32_t TradeId;
    uint32_t SettlDate;
    uint8_t TradingCapacity;
    uint8_t TrdRptStatus;
    char MessageEventSource;
    uint8_t Side;
    uint8_t AllocMethod;
    uint8_t NoOrderBookItems;
    uint8_t OrderAttributeLiquidityProvision;
    uint8_t ExecutingTraderQualifier;
    uint8_t PartyIdInvestmentDecisionMakerQualifier;
    char RootPartyExecutingFirm[5];
    char RootPartyExecutingTrader[6];
    char RootPartyEnteringTrader[6];
    char TargetPartyExecutingFirm[5];
    char TargetPartyExecutingTrader[6];
    char FirmTradeId[20];
    char FirmNegotiationId[20];
    char FreeText1[12];
    char FreeText2[12];
    char FreeText4[16];
    char Pad7[7];
} XetraEnLightCreateDealNotificationT;

/*
 * Structure: User Logout Response
 */ 
typedef struct {
    char Pad2[2];
    ResponseHeaderCompT ResponseHeaderComp;
} UserLogoutResponseT;

/*
 * Structure: User Logout Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    uint32_t Username;
    char Pad4[4];
} UserLogoutRequestT;

/*
 * Structure: User Login Response
 */ 
typedef struct {
    char Pad2[2];
    ResponseHeaderCompT ResponseHeaderComp;
} UserLoginResponseT;

/*
 * Structure: User Login Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    uint32_t Username;
    char Password[32];
    char Pad4[4];
} UserLoginRequestT;

/*
 * Structure: Unsubscribe Response
 */ 
typedef struct {
    char Pad2[2];
    ResponseHeaderCompT ResponseHeaderComp;
} UnsubscribeResponseT;

/*
 * Structure: Unsubscribe Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    uint32_t RefApplSubId;
    char Pad4[4];
} UnsubscribeRequestT;

/*
 * Structure: Rbc Header Me Comp
 */ 
typedef struct {
    uint64_t TrdRegTsTimeOut;
    uint64_t NotificationIn;
    uint64_t SendingTime;
    uint32_t ApplSubId;
    uint16_t PartitionId;
    char ApplMsgId[16];
    uint8_t ApplId;
    uint8_t ApplResendFlag;
    uint8_t LastFragment;
    char Pad7[7];
} RbcHeaderMeCompT;

/*
 * Structure: Trailing Stop Update Notification
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderMeCompT RbcHeaderMeComp;
    uint64_t OrderId;
    uint64_t ClOrdId;
    uint64_t OrigClOrdId;
    int64_t SecurityId;
    uint64_t ExecId;
    uint64_t StopPx;
    uint64_t OrderQty;
    uint32_t OrderIdSfx;
    int32_t MarketSegmentId;
    uint16_t ExecRestatementReason;
    char OrdStatus;
    char ExecType;
    uint8_t Side;
    char FixClOrdId[20];
    char Pad7[7];
} TrailingStopUpdateNotificationT;

/*
 * Structure: Trading Session Status Broadcast
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderMeCompT RbcHeaderMeComp;
    int32_t MarketSegmentId;
    uint32_t TradeDate;
    uint8_t TradSesEvent;
    char RefApplLastMsgId[16];
    char Pad7[7];
} TradingSessionStatusBroadcastT;

/*
 * Structure: Trade Broadcast
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderCompT RbcHeaderComp;
    int64_t SecurityId;
    uint64_t Price;
    uint64_t LastPx;
    uint64_t LastQty;
    uint64_t SettlCurrAmt;
    uint64_t SettlCurrFxRate;
    uint64_t TransactTime;
    uint64_t OrderId;
    uint64_t ClOrdId;
    uint64_t LeavesQty;
    uint64_t CumQty;
    uint64_t SideGrossTradeAmt;
    uint64_t AccruedInteresAmt;
    uint64_t CouponRate;
    uint64_t RootPartyIdClientId;
    uint64_t ExecutingTrader;
    uint64_t RootPartyIdInvestmentDecisionMaker;
    uint32_t TradeId;
    uint32_t OrigTradeId;
    uint32_t RootPartyIdExecutingUnit;
    uint32_t RootPartyIdSessionId;
    uint32_t RootPartyIdExecutingTrader;
    uint32_t RootPartyIdSettlementUnit;
    uint32_t RootPartyIdClearingUnit;
    uint32_t RootPartyIdContraUnit;
    uint32_t RootPartyIdContraSettlementUnit;
    uint32_t OrderIdSfx;
    int32_t MarketSegmentId;
    uint32_t SideTradeId;
    uint32_t SideTradeReportId;
    uint32_t TradeNumber;
    uint32_t MatchDate;
    uint32_t SettlDate;
    uint32_t TrdMatchId;
    uint32_t NumDaysInterest;
    uint16_t LastMkt;
    uint8_t TradeReportType;
    uint8_t TransferReason;
    uint8_t MatchType;
    uint8_t MatchSubType;
    uint8_t Side;
    uint8_t SideLiquidityInd;
    uint8_t DeliveryType;
    uint8_t TradingCapacity;
    uint8_t LastCouponDeviationIndicator;
    uint8_t RefinancingEligibilityIndicator;
    uint8_t OrderAttributeLiquidityProvision;
    uint8_t ExecutingTraderQualifier;
    uint8_t RootPartyIdInvestmentDecisionMakerQualifier;
    char Account[2];
    char SettlCurrency[3];
    char Currency[3];
    char FreeText1[12];
    char FreeText2[12];
    char FreeText4[16];
    char OrderCategory;
    uint8_t OrdType;
    char RootPartyExecutingFirm[5];
    char RootPartyExecutingTrader[6];
    char RootPartyClearingFirm[5];
    char RootPartyExecutingFirmKvNumber[4];
    char RootPartySettlementAccount[35];
    char RootPartySettlementLocation[3];
    char RootPartySettlementFirm[5];
    char RootPartyContraFirm[5];
    char RootPartyContraSettlementFirm[5];
    char RootPartyContraFirmKvNumber[4];
    char RootPartyContraSettlementAccount[35];
    char RootPartyContraSettlementLocation[3];
    char RegulatoryTradeId[52];
    char RootPartyIdExecutionVenue[4];
    char Pad4[4];
} TradeBroadcastT;

/*
 * Structure: Notif Header Comp
 */ 
typedef struct {
    uint64_t SendingTime;
} NotifHeaderCompT;

/*
 * Structure: Throttle Update Notification
 */ 
typedef struct {
    char Pad2[2];
    NotifHeaderCompT NotifHeaderComp;
    int64_t ThrottleTimeInterval;
    uint32_t ThrottleNoMsgs;
    uint32_t ThrottleDisconnectLimit;
} ThrottleUpdateNotificationT;

/*
 * Structure: Tm Trading Session Status Broadcast
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderCompT RbcHeaderComp;
    uint8_t TradSesEvent;
    char Pad7[7];
} TmTradingSessionStatusBroadcastT;

/*
 * Structure: Tes Trading Session Status Broadcast
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderCompT RbcHeaderComp;
    uint32_t TradeDate;
    uint8_t TradSesEvent;
    char Pad3[3];
} TesTradingSessionStatusBroadcastT;

/*
 * Structure: Tes Trade Broadcast
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderCompT RbcHeaderComp;
    int64_t SecurityId;
    uint64_t LastPx;
    uint64_t LastQty;
    uint64_t TransactTime;
    uint64_t SettlCurrAmt;
    uint64_t SideGrossTradeAmt;
    uint64_t SettlCurrFxRate;
    uint64_t AccruedInteresAmt;
    uint64_t CouponRate;
    uint64_t RootPartyIdClientId;
    uint64_t ExecutingTrader;
    uint64_t RootPartyIdInvestmentDecisionMaker;
    uint32_t PackageId;
    int32_t MarketSegmentId;
    uint32_t TradeId;
    uint32_t TradeDate;
    uint32_t SideTradeId;
    uint32_t RootPartyIdSessionId;
    uint32_t RootPartyIdSettlementUnit;
    uint32_t RootPartyIdContraUnit;
    uint32_t RootPartyIdContraSettlementUnit;
    uint32_t OrigTradeId;
    uint32_t RootPartyIdExecutingUnit;
    uint32_t RootPartyIdExecutingTrader;
    uint32_t RootPartyIdClearingUnit;
    uint32_t SettlDate;
    uint32_t NumDaysInterest;
    uint32_t NegotiationId;
    uint32_t SrqsRelatedTradeId;
    uint16_t TrdType;
    uint16_t LastMkt;
    uint8_t Side;
    uint8_t TradingCapacity;
    uint8_t TradeReportType;
    uint8_t TransferReason;
    uint8_t TradePublishIndicator;
    uint8_t LastCouponDeviationIndicator;
    uint8_t RefinancingEligibilityIndicator;
    uint8_t OrderAttributeLiquidityProvision;
    uint8_t ExecutingTraderQualifier;
    uint8_t RootPartyIdInvestmentDecisionMakerQualifier;
    char Account[2];
    char FreeText1[12];
    char FreeText2[12];
    char FreeText4[16];
    char SettlCurrency[3];
    char RootPartyExecutingFirm[5];
    char RootPartyExecutingTrader[6];
    char RootPartyClearingFirm[5];
    char RootPartyClearingOrganization[4];
    char RootPartyExecutingFirmKvNumber[4];
    char RootPartySettlementAccount[35];
    char RootPartySettlementLocation[3];
    char RootPartySettlementFirm[5];
    char RootPartyContraFirm[5];
    char RootPartyContraSettlementFirm[5];
    char RootPartyContraFirmKvNumber[4];
    char RootPartyContraSettlementAccount[35];
    char RootPartyContraSettlementLocation[3];
    char RootPartyIdExecutionVenue[4];
    char RegulatoryTradeId[52];
    char Pad2[2];
} TesTradeBroadcastT;

/*
 * Structure: Tes Response
 */ 
typedef struct {
    char Pad2[2];
    ResponseHeaderCompT ResponseHeaderComp;
    uint32_t TesExecId;
    char TradeReportId[20];
} TesResponseT;

/*
 * Structure: Tes Execution Broadcast
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderCompT RbcHeaderComp;
    uint64_t TransactTime;
    int32_t MarketSegmentId;
    uint32_t PackageId;
    uint32_t TesExecId;
    uint32_t AllocId;
    uint16_t TrdType;
    uint8_t TradeReportType;
    uint8_t Side;
    char MessageEventSource;
    char Pad3[3];
} TesExecutionBroadcastT;

/*
 * Structure: Tes Delete Broadcast
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderCompT RbcHeaderComp;
    uint64_t TransactTime;
    int32_t MarketSegmentId;
    uint32_t PackageId;
    uint32_t TesExecId;
    uint16_t TrdType;
    uint8_t DeleteReason;
    uint8_t TradeReportType;
    char MessageEventSource;
    char TradeReportId[20];
    char Pad3[3];
} TesDeleteBroadcastT;

/*
 * Structure: Side Alloc Grp Bc Comp
 */ 
typedef struct {
    uint64_t AllocQty;
    uint32_t IndividualAllocId;
    char PartyExecutingFirm[5];
    char PartyExecutingTrader[6];
    uint8_t Side;
    uint8_t TradeAllocStatus;
    char Pad7[7];
} SideAllocGrpBcCompT;

/*
 * Structure: Tes Broadcast
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderCompT RbcHeaderComp;
    int64_t SecurityId;
    uint64_t LastPx;
    uint64_t TransactTime;
    uint64_t TransBkdTime;
    uint64_t SettlCurrFxRate;
    int32_t MarketSegmentId;
    uint32_t PackageId;
    uint32_t TesExecId;
    uint32_t SettlDate;
    uint16_t TrdType;
    uint8_t TradeReportType;
    uint8_t NoSideAllocs;
    char MessageEventSource;
    char TradeReportText[20];
    char TradeReportId[20];
    char RootPartyExecutingFirm[5];
    char RootPartyExecutingTrader[6];
} TesBroadcastT;

/*
 * Structure: Tes Approve Broadcast
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderCompT RbcHeaderComp;
    int64_t SecurityId;
    uint64_t LastPx;
    uint64_t AllocQty;
    uint64_t TransactTime;
    uint64_t TransBkdTime;
    uint64_t SettlCurrFxRate;
    int32_t MarketSegmentId;
    uint32_t PackageId;
    uint32_t TesExecId;
    uint32_t AllocId;
    uint32_t SettlDate;
    uint16_t TrdType;
    uint8_t Side;
    uint8_t ValueCheckTypeValue;
    uint8_t ValueCheckTypeQuantity;
    uint8_t TradeReportType;
    uint8_t TradingCapacity;
    uint8_t TradeAllocStatus;
    char MessageEventSource;
    char TradeReportId[20];
    char PartyExecutingFirm[5];
    char PartyExecutingTrader[6];
    uint8_t PartyIdEnteringFirm;
    char PartyEnteringTrader[6];
    char RootPartyExecutingFirm[5];
    char RootPartyExecutingTrader[6];
    char FreeText1[12];
    char FreeText2[12];
    char FreeText4[16];
    char Pad2[2];
} TesApproveBroadcastT;

/*
 * Structure: Subscribe Response
 */ 
typedef struct {
    char Pad2[2];
    ResponseHeaderCompT ResponseHeaderComp;
    uint32_t ApplSubId;
    char Pad4[4];
} SubscribeResponseT;

/*
 * Structure: Subscribe Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    uint32_t SubscriptionScope;
    uint8_t RefApplId;
    char Pad3[3];
} SubscribeRequestT;

/*
 * Structure: Nrbc Header Comp
 */ 
typedef struct {
    uint64_t SendingTime;
    uint32_t ApplSubId;
    uint8_t ApplId;
    uint8_t LastFragment;
    char Pad2[2];
} NrbcHeaderCompT;

/*
 * Structure: Service Availability Market Broadcast
 */ 
typedef struct {
    char Pad2[2];
    NrbcHeaderCompT NrbcHeaderComp;
    uint32_t SelectiveRequestForQuoteServiceTradeDate;
    uint8_t SelectiveRequestForQuoteServiceStatus;
    char Pad3[3];
} ServiceAvailabilityMarketBroadcastT;

/*
 * Structure: Service Availability Broadcast
 */ 
typedef struct {
    char Pad2[2];
    NrbcHeaderCompT NrbcHeaderComp;
    uint32_t MatchingEngineTradeDate;
    uint32_t TradeManagerTradeDate;
    uint32_t ApplSeqTradeDate;
    uint32_t T7EntryServiceTradeDate;
    uint32_t T7EntryServiceRtmTradeDate;
    uint16_t PartitionId;
    uint8_t MatchingEngineStatus;
    uint8_t TradeManagerStatus;
    uint8_t ApplSeqStatus;
    uint8_t T7EntryServiceStatus;
    uint8_t T7EntryServiceRtmStatus;
    char Pad5[5];
} ServiceAvailabilityBroadcastT;

/*
 * Structure: Retransmit Response
 */ 
typedef struct {
    char Pad2[2];
    ResponseHeaderCompT ResponseHeaderComp;
    uint64_t ApplEndSeqNum;
    uint64_t RefApplLastSeqNum;
    uint16_t ApplTotalMessageCount;
    char Pad6[6];
} RetransmitResponseT;

/*
 * Structure: Retransmit Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    uint64_t ApplBegSeqNum;
    uint64_t ApplEndSeqNum;
    uint16_t PartitionId;
    uint8_t RefApplId;
    char Pad5[5];
} RetransmitRequestT;

/*
 * Structure: Retransmit Me Message Response
 */ 
typedef struct {
    char Pad2[2];
    ResponseHeaderCompT ResponseHeaderComp;
    uint16_t ApplTotalMessageCount;
    char ApplEndMsgId[16];
    char RefApplLastMsgId[16];
    char Pad6[6];
} RetransmitMeMessageResponseT;

/*
 * Structure: Retransmit Me Message Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    uint32_t SubscriptionScope;
    uint16_t PartitionId;
    uint8_t RefApplId;
    char ApplBegMsgId[16];
    char ApplEndMsgId[16];
    char Pad1[1];
} RetransmitMeMessageRequestT;

/*
 * Structure: Nr Response Header Me Comp
 */ 
typedef struct {
    uint64_t RequestTime;
    uint64_t TrdRegTsTimeIn;
    uint64_t TrdRegTsTimeOut;
    uint64_t ResponseIn;
    uint64_t SendingTime;
    uint32_t MsgSeqNum;
    uint8_t LastFragment;
    char Pad3[3];
} NrResponseHeaderMeCompT;

/*
 * Structure: Reject
 */ 
typedef struct {
    char Pad2[2];
    NrResponseHeaderMeCompT NrResponseHeaderMeComp;
    uint32_t SessionRejectReason;
    uint16_t VarTextLen;
    uint8_t SessionStatus;
    char Pad1[1];
} RejectT;

/*
 * Structure: Rfq Response
 */ 
typedef struct {
    char Pad2[2];
    NrResponseHeaderMeCompT NrResponseHeaderMeComp;
    uint64_t ExecId;
} RfqResponseT;

/*
 * Structure: Rfq Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    int64_t SecurityId;
    uint64_t OrderQty;
    int32_t MarketSegmentId;
    uint8_t RfqPublishIndicator;
    uint8_t RfqRequesterDisclosureInstruction;
    uint8_t Side;
    char Pad1[1];
} RfqRequestT;

/*
 * Structure: Rfq Broadcast
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderMeCompT RbcHeaderMeComp;
    int64_t SecurityId;
    uint64_t ExecId;
    uint64_t OrderQty;
    int32_t MarketSegmentId;
    uint8_t Side;
    char PartyExecutingFirm[5];
    char Pad6[6];
} RfqBroadcastT;

/*
 * Structure: Quote Event Grp Comp
 */ 
typedef struct {
    int64_t SecurityId;
    uint64_t QuoteEventPx;
    uint64_t QuoteEventQty;
    uint64_t QuoteMsgId;
    uint32_t QuoteEventMatchId;
    int32_t QuoteEventExecId;
    uint8_t QuoteEventType;
    uint8_t QuoteEventSide;
    uint8_t QuoteEventLiquidityInd;
    uint8_t QuoteEventReason;
    char Pad4[4];
} QuoteEventGrpCompT;

/*
 * Structure: Quote Execution Report
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderMeCompT RbcHeaderMeComp;
    uint64_t ExecId;
    int32_t MarketSegmentId;
    uint8_t NoQuoteEvents;
    char Pad3[3];
} QuoteExecutionReportT;

/*
 * Structure: Not Affected Securities Grp Comp
 */ 
typedef struct {
    uint64_t NotAffectedSecurityId;
} NotAffectedSecuritiesGrpCompT;

/*
 * Structure: Quote Activation Response
 */ 
typedef struct {
    char Pad2[2];
    NrResponseHeaderMeCompT NrResponseHeaderMeComp;
    uint64_t MassActionReportId;
    uint16_t NoNotAffectedSecurities;
    char Pad6[6];
} QuoteActivationResponseT;

/*
 * Structure: Quote Activation Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    uint64_t PartyIdInvestmentDecisionMaker;
    uint64_t ExecutingTrader;
    int32_t MarketSegmentId;
    uint32_t TargetPartyIdSessionId;
    uint8_t MassActionType;
    uint8_t PartyIdInvestmentDecisionMakerQualifier;
    uint8_t ExecutingTraderQualifier;
    char Pad5[5];
} QuoteActivationRequestT;

/*
 * Structure: Quote Activation Notification
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderMeCompT RbcHeaderMeComp;
    uint64_t MassActionReportId;
    int32_t MarketSegmentId;
    uint32_t PartyIdEnteringTrader;
    uint16_t NoNotAffectedSecurities;
    uint8_t PartyIdEnteringFirm;
    uint8_t MassActionType;
    uint8_t MassActionReason;
    char Pad3[3];
} QuoteActivationNotificationT;

/*
 * Structure: Party Entitlements Update Report
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderCompT RbcHeaderComp;
    uint64_t TransactTime;
    uint32_t TradeDate;
    uint32_t PartyDetailIdExecutingUnit;
    uint32_t RequestingPartyIdExecutingSystem;
    uint16_t MarketId;
    char ListUpdateAction;
    char RequestingPartyEnteringFirm[9];
    char RequestingPartyClearingFirm[9];
    uint8_t PartyDetailStatus;
    char Pad6[6];
} PartyEntitlementsUpdateReportT;

/*
 * Structure: Party Action Report
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderCompT RbcHeaderComp;
    uint64_t TransactTime;
    uint32_t TradeDate;
    uint32_t RequestingPartyIdExecutingTrader;
    uint32_t PartyIdExecutingUnit;
    uint32_t PartyIdExecutingTrader;
    uint32_t RequestingPartyIdExecutingSystem;
    uint16_t MarketId;
    uint8_t PartyActionType;
    uint8_t RequestingPartyIdEnteringFirm;
} PartyActionReportT;

/*
 * Structure: Fills Grp Comp
 */ 
typedef struct {
    uint64_t FillPx;
    uint64_t FillQty;
    uint32_t FillMatchId;
    int32_t FillExecId;
    uint8_t FillLiquidityInd;
    char Pad7[7];
} FillsGrpCompT;

/*
 * Structure: Response Header Me Comp
 */ 
typedef struct {
    uint64_t RequestTime;
    uint64_t TrdRegTsTimeIn;
    uint64_t TrdRegTsTimeOut;
    uint64_t ResponseIn;
    uint64_t SendingTime;
    uint32_t MsgSeqNum;
    uint16_t PartitionId;
    uint8_t ApplId;
    char ApplMsgId[16];
    uint8_t LastFragment;
} ResponseHeaderMeCompT;

/*
 * Structure: Order Exec Response
 */ 
typedef struct {
    char Pad2[2];
    ResponseHeaderMeCompT ResponseHeaderMeComp;
    uint64_t OrderId;
    uint64_t ClOrdId;
    uint64_t OrigClOrdId;
    int64_t SecurityId;
    uint64_t ExecId;
    uint64_t TrdRegTsEntryTime;
    uint64_t TrdRegTsTimePriority;
    uint64_t LeavesQty;
    uint64_t CumQty;
    uint64_t CxlQty;
    uint64_t DisplayQty;
    int32_t MarketSegmentId;
    uint32_t OrderIdSfx;
    uint16_t ExecRestatementReason;
    uint8_t Side;
    char OrdStatus;
    char ExecType;
    uint8_t MatchType;
    uint8_t Triggered;
    uint8_t CrossedIndicator;
    uint8_t TransactionDelayIndicator;
    uint8_t NoFills;
    char Pad6[6];
} OrderExecResponseT;

/*
 * Structure: Order Exec Report Broadcast
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderMeCompT RbcHeaderMeComp;
    uint64_t OrderId;
    uint64_t ClOrdId;
    uint64_t OrigClOrdId;
    int64_t SecurityId;
    uint64_t ExecId;
    uint64_t TrdRegTsEntryTime;
    uint64_t TrdRegTsTimePriority;
    uint64_t Price;
    uint64_t LeavesQty;
    uint64_t CumQty;
    uint64_t CxlQty;
    uint64_t OrderQty;
    uint64_t DisplayQty;
    uint64_t DisplayLowQty;
    uint64_t DisplayHighQty;
    uint64_t StopPx;
    uint64_t VolumeDiscoveryPrice;
    uint64_t PegOffsetValueAbs;
    uint64_t PegOffsetValuePct;
    int32_t MarketSegmentId;
    uint32_t OrderIdSfx;
    uint32_t ExpireDate;
    uint32_t MatchInstCrossId;
    uint32_t PartyIdExecutingUnit;
    uint32_t PartyIdSessionId;
    uint32_t PartyIdExecutingTrader;
    uint32_t PartyIdEnteringTrader;
    uint16_t ExecRestatementReason;
    uint8_t PartyIdEnteringFirm;
    char OrdStatus;
    char ExecType;
    uint8_t MatchType;
    uint8_t Side;
    uint8_t OrdType;
    uint8_t TradingCapacity;
    uint8_t TimeInForce;
    uint8_t ExecInst;
    uint8_t TradingSessionSubId;
    uint8_t ApplSeqIndicator;
    uint8_t ExDestinationType;
    char FreeText1[12];
    char FreeText2[12];
    char FreeText4[16];
    char FixClOrdId[20];
    uint8_t NoFills;
    uint8_t Triggered;
    uint8_t CrossedIndicator;
    char Pad3[3];
} OrderExecReportBroadcastT;

/*
 * Structure: Order Exec Notification
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderMeCompT RbcHeaderMeComp;
    uint64_t OrderId;
    uint64_t ClOrdId;
    uint64_t OrigClOrdId;
    int64_t SecurityId;
    uint64_t ExecId;
    uint64_t LeavesQty;
    uint64_t CumQty;
    uint64_t CxlQty;
    uint64_t DisplayQty;
    int32_t MarketSegmentId;
    uint32_t OrderIdSfx;
    uint16_t ExecRestatementReason;
    uint8_t Side;
    char OrdStatus;
    char ExecType;
    uint8_t MatchType;
    uint8_t Triggered;
    uint8_t CrossedIndicator;
    char FixClOrdId[20];
    uint8_t NoFills;
    char Pad3[3];
} OrderExecNotificationT;

/*
 * Structure: News Broadcast
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderCompT RbcHeaderComp;
    uint64_t OrigTime;
    uint16_t VarTextLen;
    char Headline[256];
    char Pad6[6];
} NewsBroadcastT;

/*
 * Structure: New Order Single Short Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    int64_t SecurityId;
    uint64_t Price;
    uint64_t OrderQty;
    uint64_t ClOrdId;
    uint64_t PartyIdClientId;
    uint64_t PartyIdInvestmentDecisionMaker;
    uint64_t ExecutingTrader;
    uint32_t MatchInstCrossId;
    uint16_t EnrichmentRuleId;
    uint8_t Side;
    uint8_t ApplSeqIndicator;
    uint8_t PriceValidityCheckType;
    uint8_t ValueCheckTypeValue;
    uint8_t ValueCheckTypeQuantity;
    uint8_t OrderAttributeLiquidityProvision;
    uint8_t TimeInForce;
    uint8_t ExecInst;
    uint8_t TradingCapacity;
    uint8_t ExDestinationType;
    uint8_t PartyIdInvestmentDecisionMakerQualifier;
    uint8_t ExecutingTraderQualifier;
    char Pad6[6];
} NewOrderSingleShortRequestT;

/*
 * Structure: New Order Single Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    uint64_t Price;
    uint64_t OrderQty;
    uint64_t DisplayQty;
    uint64_t DisplayLowQty;
    uint64_t DisplayHighQty;
    uint64_t StopPx;
    uint64_t VolumeDiscoveryPrice;
    uint64_t PegOffsetValueAbs;
    uint64_t PegOffsetValuePct;
    uint64_t ClOrdId;
    int64_t SecurityId;
    uint64_t PartyIdClientId;
    uint64_t PartyIdInvestmentDecisionMaker;
    uint64_t ExecutingTrader;
    uint32_t ExpireDate;
    int32_t MarketSegmentId;
    uint32_t MatchInstCrossId;
    uint8_t ApplSeqIndicator;
    uint8_t Side;
    uint8_t OrdType;
    uint8_t PriceValidityCheckType;
    uint8_t ValueCheckTypeValue;
    uint8_t ValueCheckTypeQuantity;
    uint8_t OrderAttributeLiquidityProvision;
    uint8_t TimeInForce;
    uint8_t ExecInst;
    uint8_t TradingSessionSubId;
    uint8_t TradingCapacity;
    uint8_t ExDestinationType;
    uint8_t PartyIdInvestmentDecisionMakerQualifier;
    uint8_t ExecutingTraderQualifier;
    char FreeText1[12];
    char FreeText2[12];
    char FreeText4[16];
    char FixClOrdId[20];
    char Pad2[2];
} NewOrderSingleRequestT;

/*
 * Structure: New Order Response
 */ 
typedef struct {
    char Pad2[2];
    ResponseHeaderMeCompT ResponseHeaderMeComp;
    uint64_t OrderId;
    uint64_t ClOrdId;
    int64_t SecurityId;
    uint64_t ExecId;
    uint64_t TrdRegTsEntryTime;
    uint64_t TrdRegTsTimePriority;
    uint32_t OrderIdSfx;
    char OrdStatus;
    char ExecType;
    uint16_t ExecRestatementReason;
    uint8_t CrossedIndicator;
    uint8_t Triggered;
    uint8_t TransactionDelayIndicator;
    char Pad5[5];
} NewOrderResponseT;

/*
 * Structure: New Order Nr Response
 */ 
typedef struct {
    char Pad2[2];
    NrResponseHeaderMeCompT NrResponseHeaderMeComp;
    uint64_t OrderId;
    uint64_t ClOrdId;
    int64_t SecurityId;
    uint64_t ExecId;
    uint32_t OrderIdSfx;
    char OrdStatus;
    char ExecType;
    uint16_t ExecRestatementReason;
    uint8_t CrossedIndicator;
    uint8_t Triggered;
    uint8_t TransactionDelayIndicator;
    char Pad5[5];
} NewOrderNrResponseT;

/*
 * Structure: Side Alloc Grp Comp
 */ 
typedef struct {
    uint64_t AllocQty;
    uint32_t IndividualAllocId;
    uint8_t Side;
    char PartyExecutingFirm[5];
    char PartyExecutingTrader[6];
} SideAllocGrpCompT;

/*
 * Structure: Modify Tes Trade Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    uint64_t LastPx;
    uint64_t TransBkdTime;
    int32_t MarketSegmentId;
    uint32_t PackageId;
    uint32_t TesExecId;
    uint32_t SettlDate;
    uint16_t TrdType;
    uint8_t TradeReportType;
    uint8_t NoSideAllocs;
    char TradeReportText[20];
    char TradeReportId[20];
    char Pad4[4];
} ModifyTesTradeRequestT;

/*
 * Structure: Modify Order Single Short Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    uint64_t ClOrdId;
    uint64_t OrigClOrdId;
    int64_t SecurityId;
    uint64_t Price;
    uint64_t OrderQty;
    uint64_t PartyIdClientId;
    uint64_t PartyIdInvestmentDecisionMaker;
    uint64_t ExecutingTrader;
    uint32_t MatchInstCrossId;
    uint16_t EnrichmentRuleId;
    uint8_t Side;
    uint8_t PriceValidityCheckType;
    uint8_t ValueCheckTypeValue;
    uint8_t ValueCheckTypeQuantity;
    uint8_t OrderAttributeLiquidityProvision;
    uint8_t TimeInForce;
    uint8_t ApplSeqIndicator;
    uint8_t ExecInst;
    uint8_t TradingCapacity;
    uint8_t ExDestinationType;
    uint8_t PartyIdInvestmentDecisionMakerQualifier;
    uint8_t ExecutingTraderQualifier;
    char Pad6[6];
} ModifyOrderSingleShortRequestT;

/*
 * Structure: Modify Order Single Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    uint64_t OrderId;
    uint64_t ClOrdId;
    uint64_t OrigClOrdId;
    int64_t SecurityId;
    uint64_t Price;
    uint64_t OrderQty;
    uint64_t DisplayQty;
    uint64_t DisplayLowQty;
    uint64_t DisplayHighQty;
    uint64_t StopPx;
    uint64_t VolumeDiscoveryPrice;
    uint64_t PegOffsetValueAbs;
    uint64_t PegOffsetValuePct;
    uint64_t PartyIdClientId;
    uint64_t PartyIdInvestmentDecisionMaker;
    uint64_t ExecutingTrader;
    uint32_t ExpireDate;
    int32_t MarketSegmentId;
    uint32_t MatchInstCrossId;
    uint32_t TargetPartyIdSessionId;
    uint8_t ApplSeqIndicator;
    uint8_t Side;
    uint8_t OrdType;
    uint8_t PriceValidityCheckType;
    uint8_t ValueCheckTypeValue;
    uint8_t ValueCheckTypeQuantity;
    uint8_t OrderAttributeLiquidityProvision;
    uint8_t TimeInForce;
    uint8_t ExecInst;
    uint8_t TradingSessionSubId;
    uint8_t StopPxIndicator;
    uint8_t TradingCapacity;
    uint8_t ExDestinationType;
    uint8_t PartyIdInvestmentDecisionMakerQualifier;
    uint8_t ExecutingTraderQualifier;
    uint8_t OwnershipIndicator;
    char FreeText1[12];
    char FreeText2[12];
    char FreeText4[16];
    char FixClOrdId[20];
    char Pad4[4];
} ModifyOrderSingleRequestT;

/*
 * Structure: Modify Order Response
 */ 
typedef struct {
    char Pad2[2];
    ResponseHeaderMeCompT ResponseHeaderMeComp;
    uint64_t OrderId;
    uint64_t ClOrdId;
    uint64_t OrigClOrdId;
    int64_t SecurityId;
    uint64_t ExecId;
    uint64_t StopPx;
    uint64_t LeavesQty;
    uint64_t CumQty;
    uint64_t CxlQty;
    uint64_t DisplayQty;
    uint64_t TrdRegTsTimePriority;
    uint32_t OrderIdSfx;
    char OrdStatus;
    char ExecType;
    uint16_t ExecRestatementReason;
    uint8_t CrossedIndicator;
    uint8_t Triggered;
    uint8_t TransactionDelayIndicator;
    char Pad5[5];
} ModifyOrderResponseT;

/*
 * Structure: Modify Order Nr Response
 */ 
typedef struct {
    char Pad2[2];
    NrResponseHeaderMeCompT NrResponseHeaderMeComp;
    uint64_t OrderId;
    uint64_t ClOrdId;
    uint64_t OrigClOrdId;
    int64_t SecurityId;
    uint64_t ExecId;
    uint64_t StopPx;
    uint64_t LeavesQty;
    uint64_t CumQty;
    uint64_t CxlQty;
    uint64_t DisplayQty;
    uint32_t OrderIdSfx;
    char OrdStatus;
    char ExecType;
    uint16_t ExecRestatementReason;
    uint8_t CrossedIndicator;
    uint8_t Triggered;
    uint8_t TransactionDelayIndicator;
    char Pad5[5];
} ModifyOrderNrResponseT;

/*
 * Structure: Quote Entry Ack Grp Comp
 */ 
typedef struct {
    int64_t SecurityId;
    uint64_t BidCxlSize;
    uint64_t OfferCxlSize;
    uint32_t QuoteEntryRejectReason;
    uint8_t QuoteEntryStatus;
    char Pad3[3];
} QuoteEntryAckGrpCompT;

/*
 * Structure: Mass Quote Response
 */ 
typedef struct {
    char Pad2[2];
    NrResponseHeaderMeCompT NrResponseHeaderMeComp;
    uint64_t QuoteId;
    uint64_t QuoteResponseId;
    int32_t MarketSegmentId;
    uint8_t NoQuoteEntries;
    char Pad3[3];
} MassQuoteResponseT;

/*
 * Structure: Quote Entry Grp Comp
 */ 
typedef struct {
    int64_t SecurityId;
    uint64_t BidPx;
    uint64_t BidSize;
    uint64_t OfferPx;
    uint64_t OfferSize;
} QuoteEntryGrpCompT;

/*
 * Structure: Mass Quote Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    uint64_t QuoteId;
    uint64_t PartyIdInvestmentDecisionMaker;
    uint64_t ExecutingTrader;
    int32_t MarketSegmentId;
    uint32_t MatchInstCrossId;
    uint16_t EnrichmentRuleId;
    uint8_t PriceValidityCheckType;
    uint8_t ValueCheckTypeValue;
    uint8_t ValueCheckTypeQuantity;
    uint8_t QuoteSizeType;
    uint8_t QuoteType;
    uint8_t OrderAttributeLiquidityProvision;
    uint8_t NoQuoteEntries;
    uint8_t PartyIdInvestmentDecisionMakerQualifier;
    uint8_t ExecutingTraderQualifier;
    char Pad5[5];
} MassQuoteRequestT;

/*
 * Structure: Logout Response
 */ 
typedef struct {
    char Pad2[2];
    ResponseHeaderCompT ResponseHeaderComp;
} LogoutResponseT;

/*
 * Structure: Logout Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
} LogoutRequestT;

/*
 * Structure: Logon Response
 */ 
typedef struct {
    char Pad2[2];
    ResponseHeaderCompT ResponseHeaderComp;
    int64_t ThrottleTimeInterval;
    uint32_t ThrottleNoMsgs;
    uint32_t ThrottleDisconnectLimit;
    uint32_t HeartBtInt;
    uint32_t SessionInstanceId;
    uint16_t MarketId;
    uint8_t TradSesMode;
    char DefaultCstmApplVerId[30];
    char DefaultCstmApplVerSubId[5];
    char Pad2[2];
} LogonResponseT;

/*
 * Structure: Logon Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    uint32_t HeartBtInt;
    uint32_t PartyIdSessionId;
    char DefaultCstmApplVerId[30];
    char Password[32];
    char ApplUsageOrders;
    char ApplUsageQuotes;
    char OrderRoutingIndicator;
    char FixEngineName[30];
    char FixEngineVersion[30];
    char FixEngineVendor[30];
    char ApplicationSystemName[30];
    char ApplicationSystemVersion[30];
    char ApplicationSystemVendor[30];
    char Pad3[3];
} LogonRequestT;

/*
 * Structure: Legal Notification Broadcast
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderCompT RbcHeaderComp;
    uint64_t TransactTime;
    uint16_t VarTextLen;
    uint8_t UserStatus;
    char Pad5[5];
} LegalNotificationBroadcastT;

/*
 * Structure: Issuer Security State Change Response
 */ 
typedef struct {
    char Pad2[2];
    NrResponseHeaderMeCompT NrResponseHeaderMeComp;
    uint64_t SecurityStatusReportId;
} IssuerSecurityStateChangeResponseT;

/*
 * Structure: Security Status Event Grp Comp
 */ 
typedef struct {
    uint64_t EventPx;
    uint32_t EventDate;
    uint8_t EventType;
    char Pad3[3];
} SecurityStatusEventGrpCompT;

/*
 * Structure: Issuer Security State Change Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    int64_t SecurityId;
    uint64_t TransactTime;
    int32_t MarketSegmentId;
    uint8_t NoEvents;
    uint8_t SecurityStatus;
    uint8_t SoldOutIndicator;
    char Pad1[1];
} IssuerSecurityStateChangeRequestT;

/*
 * Structure: Issuer Notification
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderMeCompT RbcHeaderMeComp;
    int64_t SecurityId;
    uint64_t TransactTime;
    uint64_t LastPx;
    uint64_t PotentialExecVolume;
    uint64_t LastQty;
    uint64_t ImbalanceQty;
    int32_t MarketSegmentId;
    uint32_t PartyIdSessionId;
    uint8_t SecurityTradingStatus;
    char Pad7[7];
} IssuerNotificationT;

/*
 * Structure: Party Details Grp Comp
 */ 
typedef struct {
    uint32_t PartyDetailIdExecutingTrader;
    char PartyDetailExecutingTrader[6];
    uint8_t PartyDetailRoleQualifier;
    uint8_t PartyDetailStatus;
    char PartyDetailDeskId[3];
    char Pad1[1];
} PartyDetailsGrpCompT;

/*
 * Structure: Inquire User Response
 */ 
typedef struct {
    char Pad2[2];
    ResponseHeaderCompT ResponseHeaderComp;
    char LastEntityProcessed[16];
    uint16_t NoPartyDetails;
    char Pad6[6];
} InquireUserResponseT;

/*
 * Structure: Inquire User Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    char LastEntityProcessed[16];
} InquireUserRequestT;

/*
 * Structure: Sessions Grp Comp
 */ 
typedef struct {
    uint32_t PartyIdSessionId;
    uint8_t SessionMode;
    uint8_t SessionSubMode;
    char Pad2[2];
} SessionsGrpCompT;

/*
 * Structure: Inquire Session List Response
 */ 
typedef struct {
    char Pad2[2];
    ResponseHeaderCompT ResponseHeaderComp;
    uint16_t NoSessions;
    char Pad6[6];
} InquireSessionListResponseT;

/*
 * Structure: Inquire Session List Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
} InquireSessionListRequestT;

/*
 * Structure: Enrichment Rules Grp Comp
 */ 
typedef struct {
    uint16_t EnrichmentRuleId;
    char FreeText1[12];
    char FreeText2[12];
    char FreeText4[16];
    char Pad6[6];
} EnrichmentRulesGrpCompT;

/*
 * Structure: Inquire Enrichment Rule Id List Response
 */ 
typedef struct {
    char Pad2[2];
    ResponseHeaderCompT ResponseHeaderComp;
    char LastEntityProcessed[16];
    uint16_t NoEnrichmentRules;
    char Pad6[6];
} InquireEnrichmentRuleIdListResponseT;

/*
 * Structure: Inquire Enrichment Rule Id List Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    char LastEntityProcessed[16];
} InquireEnrichmentRuleIdListRequestT;

/*
 * Structure: Heartbeat Notification
 */ 
typedef struct {
    char Pad2[2];
    NotifHeaderCompT NotifHeaderComp;
} HeartbeatNotificationT;

/*
 * Structure: Heartbeat
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
} HeartbeatT;

/*
 * Structure: Forced User Logout Notification
 */ 
typedef struct {
    char Pad2[2];
    NotifHeaderCompT NotifHeaderComp;
    uint8_t UserStatus;
    char Pad3[3];
    uint32_t Username;
    uint16_t VarTextLen;
    char Pad6[6];
} ForcedUserLogoutNotificationT;

/*
 * Structure: Forced Logout Notification
 */ 
typedef struct {
    char Pad2[2];
    NotifHeaderCompT NotifHeaderComp;
    uint16_t VarTextLen;
    char Pad6[6];
} ForcedLogoutNotificationT;

/*
 * Structure: Extended Deletion Report
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderMeCompT RbcHeaderMeComp;
    uint64_t OrderId;
    uint64_t ClOrdId;
    uint64_t OrigClOrdId;
    int64_t SecurityId;
    uint64_t ExecId;
    uint64_t TrdRegTsEntryTime;
    uint64_t Price;
    uint64_t LeavesQty;
    uint64_t CumQty;
    uint64_t CxlQty;
    uint64_t OrderQty;
    uint64_t DisplayQty;
    uint64_t DisplayLowQty;
    uint64_t DisplayHighQty;
    uint64_t StopPx;
    uint64_t VolumeDiscoveryPrice;
    uint64_t PegOffsetValueAbs;
    uint64_t PegOffsetValuePct;
    int32_t MarketSegmentId;
    uint32_t OrderIdSfx;
    uint32_t ExpireDate;
    uint32_t MatchInstCrossId;
    uint32_t PartyIdExecutingUnit;
    uint32_t PartyIdSessionId;
    uint32_t PartyIdExecutingTrader;
    uint32_t PartyIdEnteringTrader;
    uint16_t ExecRestatementReason;
    char OrdStatus;
    char ExecType;
    uint8_t Side;
    uint8_t OrdType;
    uint8_t TradingCapacity;
    uint8_t TimeInForce;
    uint8_t ExecInst;
    uint8_t TradingSessionSubId;
    uint8_t ApplSeqIndicator;
    uint8_t ExDestinationType;
    char FreeText1[12];
    char FreeText2[12];
    char FreeText4[16];
    char FixClOrdId[20];
    uint8_t Triggered;
    char Pad7[7];
} ExtendedDeletionReportT;

/*
 * Structure: Enter Tes Trade Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    int64_t SecurityId;
    uint64_t LastPx;
    uint64_t TransBkdTime;
    uint64_t SettlCurrFxRate;
    int32_t MarketSegmentId;
    uint32_t SettlDate;
    uint16_t TrdType;
    uint8_t TradeReportType;
    uint8_t NoSideAllocs;
    char TradeReportText[20];
    char TradeReportId[20];
    char Pad4[4];
} EnterTesTradeRequestT;

/*
 * Structure: Enter Best Quote Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    uint64_t QuoteId;
    int64_t SecurityId;
    uint64_t BidPx;
    uint64_t BidSize;
    uint64_t ReservedBidSize;
    uint64_t OfferPx;
    uint64_t OfferSize;
    uint64_t ReservedOfferSize;
    uint64_t PegOffsetValueBidPx;
    uint64_t PegOffsetValueOfferPx;
    uint64_t PartyIdInvestmentDecisionMaker;
    uint64_t ExecutingTrader;
    int32_t MarketSegmentId;
    uint16_t EnrichmentRuleId;
    uint8_t OrderAttributeLiquidityProvision;
    uint8_t ValueCheckTypeQuantity;
    uint8_t PartyIdInvestmentDecisionMakerQualifier;
    uint8_t ExecutingTraderQualifier;
    char Pad6[6];
} EnterBestQuoteRequestT;

/*
 * Structure: Delete Tes Trade Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    uint32_t PackageId;
    int32_t MarketSegmentId;
    uint32_t TesExecId;
    uint16_t TrdType;
    uint8_t TradeReportType;
    char TradeReportId[20];
    char Pad5[5];
} DeleteTesTradeRequestT;

/*
 * Structure: Delete Order Single Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    uint64_t OrderId;
    uint64_t ClOrdId;
    uint64_t OrigClOrdId;
    int64_t SecurityId;
    uint64_t PartyIdInvestmentDecisionMaker;
    uint64_t ExecutingTrader;
    int32_t MarketSegmentId;
    uint32_t TargetPartyIdSessionId;
    uint8_t PartyIdInvestmentDecisionMakerQualifier;
    uint8_t ExecutingTraderQualifier;
    char FixClOrdId[20];
    char Pad2[2];
} DeleteOrderSingleRequestT;

/*
 * Structure: Delete Order Response
 */ 
typedef struct {
    char Pad2[2];
    ResponseHeaderMeCompT ResponseHeaderMeComp;
    uint64_t OrderId;
    uint64_t ClOrdId;
    uint64_t OrigClOrdId;
    int64_t SecurityId;
    uint64_t ExecId;
    uint64_t CumQty;
    uint64_t CxlQty;
    uint32_t OrderIdSfx;
    char OrdStatus;
    char ExecType;
    uint16_t ExecRestatementReason;
    uint8_t TransactionDelayIndicator;
    char Pad7[7];
} DeleteOrderResponseT;

/*
 * Structure: Delete Order Nr Response
 */ 
typedef struct {
    char Pad2[2];
    NrResponseHeaderMeCompT NrResponseHeaderMeComp;
    uint64_t OrderId;
    uint64_t ClOrdId;
    uint64_t OrigClOrdId;
    int64_t SecurityId;
    uint64_t ExecId;
    uint64_t CumQty;
    uint64_t CxlQty;
    uint32_t OrderIdSfx;
    char OrdStatus;
    char ExecType;
    uint16_t ExecRestatementReason;
    uint8_t TransactionDelayIndicator;
    char Pad7[7];
} DeleteOrderNrResponseT;

/*
 * Structure: Delete Order Broadcast
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderMeCompT RbcHeaderMeComp;
    uint64_t OrderId;
    uint64_t ClOrdId;
    uint64_t OrigClOrdId;
    int64_t SecurityId;
    uint64_t ExecId;
    uint64_t CumQty;
    uint64_t CxlQty;
    uint32_t OrderIdSfx;
    int32_t MarketSegmentId;
    uint32_t PartyIdEnteringTrader;
    uint32_t PartyIdSessionId;
    uint16_t ExecRestatementReason;
    uint8_t PartyIdEnteringFirm;
    char OrdStatus;
    char ExecType;
    uint8_t Side;
    char FixClOrdId[20];
    char Pad6[6];
} DeleteOrderBroadcastT;

/*
 * Structure: Delete All Quote Response
 */ 
typedef struct {
    char Pad2[2];
    NrResponseHeaderMeCompT NrResponseHeaderMeComp;
    uint64_t MassActionReportId;
    uint16_t NoNotAffectedSecurities;
    char Pad6[6];
} DeleteAllQuoteResponseT;

/*
 * Structure: Delete All Quote Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    uint64_t PartyIdInvestmentDecisionMaker;
    uint64_t ExecutingTrader;
    int32_t MarketSegmentId;
    uint32_t TargetPartyIdSessionId;
    uint8_t PartyIdInvestmentDecisionMakerQualifier;
    uint8_t ExecutingTraderQualifier;
    char Pad6[6];
} DeleteAllQuoteRequestT;

/*
 * Structure: Delete All Quote Broadcast
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderMeCompT RbcHeaderMeComp;
    uint64_t MassActionReportId;
    int64_t SecurityId;
    int32_t MarketSegmentId;
    uint32_t TargetPartyIdSessionId;
    uint32_t PartyIdEnteringTrader;
    uint32_t TargetPartyIdExecutingTrader;
    uint16_t NoNotAffectedSecurities;
    uint8_t MassActionReason;
    uint8_t PartyIdEnteringFirm;
    char TargetPartyIdDeskId[3];
    char Pad1[1];
} DeleteAllQuoteBroadcastT;

/*
 * Structure: Affected Order Requests Grp Comp
 */ 
typedef struct {
    uint32_t AffectedOrderRequestId;
    char Pad4[4];
} AffectedOrderRequestsGrpCompT;

/*
 * Structure: Affected Ord Grp Comp
 */ 
typedef struct {
    uint64_t AffectedOrderId;
    uint64_t AffectedOrigClOrdId;
} AffectedOrdGrpCompT;

/*
 * Structure: Not Affected Orders Grp Comp
 */ 
typedef struct {
    uint64_t NotAffectedOrderId;
    uint64_t NotAffOrigClOrdId;
} NotAffectedOrdersGrpCompT;

/*
 * Structure: Delete All Order Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    int64_t SecurityId;
    uint64_t Price;
    uint64_t PartyIdInvestmentDecisionMaker;
    uint64_t ExecutingTrader;
    int32_t MarketSegmentId;
    uint32_t TargetPartyIdSessionId;
    uint32_t TargetPartyIdExecutingTrader;
    uint8_t Side;
    uint8_t PartyIdInvestmentDecisionMakerQualifier;
    uint8_t ExecutingTraderQualifier;
    char Pad1[1];
} DeleteAllOrderRequestT;

/*
 * Structure: Delete All Order Quote Event Broadcast
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderMeCompT RbcHeaderMeComp;
    uint64_t MassActionReportId;
    int64_t SecurityId;
    int32_t MarketSegmentId;
    uint8_t MassActionReason;
    uint8_t ExecInst;
    char Pad2[2];
} DeleteAllOrderQuoteEventBroadcastT;

/*
 * Structure: Delete All Order Nr Response
 */ 
typedef struct {
    char Pad2[2];
    NrResponseHeaderMeCompT NrResponseHeaderMeComp;
    uint64_t MassActionReportId;
} DeleteAllOrderNrResponseT;

/*
 * Structure: Cross Request Response
 */ 
typedef struct {
    char Pad2[2];
    NrResponseHeaderMeCompT NrResponseHeaderMeComp;
    uint64_t ExecId;
} CrossRequestResponseT;

/*
 * Structure: Cross Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    int64_t SecurityId;
    uint64_t OrderQty;
    int32_t MarketSegmentId;
    char Pad4[4];
} CrossRequestT;

/*
 * Structure: Broadcast Error Notification
 */ 
typedef struct {
    char Pad2[2];
    NotifHeaderCompT NotifHeaderComp;
    uint32_t ApplIdStatus;
    uint32_t RefApplSubId;
    uint16_t VarTextLen;
    uint8_t RefApplId;
    uint8_t SessionStatus;
    char Pad4[4];
} BroadcastErrorNotificationT;

/*
 * Structure: Best Quote Response
 */ 
typedef struct {
    char Pad2[2];
    NrResponseHeaderMeCompT NrResponseHeaderMeComp;
    uint64_t QuoteId;
    uint64_t QuoteResponseId;
    int64_t SecurityId;
    uint64_t BidCxlSize;
    uint64_t OfferCxlSize;
    int32_t MarketSegmentId;
    char Pad4[4];
} BestQuoteResponseT;

/*
 * Structure: Best Quote Execution Report
 */ 
typedef struct {
    char Pad2[2];
    RbcHeaderMeCompT RbcHeaderMeComp;
    uint64_t ExecId;
    uint64_t QuoteMsgId;
    int64_t SecurityId;
    uint64_t QuoteEventPx;
    uint64_t QuoteEventQty;
    uint64_t ReservedSize;
    int32_t MarketSegmentId;
    uint32_t QuoteEventMatchId;
    int32_t QuoteEventExecId;
    uint8_t QuoteEventType;
    uint8_t QuoteEventSide;
    char Pad2[2];
} BestQuoteExecutionReportT;

/*
 * Structure: Approve Tes Trade Request
 */ 
typedef struct {
    char NetworkMsgId[8];
    char Pad2[2];
    RequestHeaderCompT RequestHeaderComp;
    uint64_t PartyIdClientId;
    uint64_t PartyIdInvestmentDecisionMaker;
    uint64_t ExecutingTrader;
    uint64_t AllocQty;
    uint32_t PackageId;
    uint32_t AllocId;
    uint32_t TesExecId;
    int32_t MarketSegmentId;
    uint16_t TrdType;
    uint8_t TradingCapacity;
    uint8_t TradeReportType;
    uint8_t Side;
    uint8_t ValueCheckTypeValue;
    uint8_t ValueCheckTypeQuantity;
    uint8_t OrderAttributeLiquidityProvision;
    uint8_t PartyIdInvestmentDecisionMakerQualifier;
    uint8_t ExecutingTraderQualifier;
    char TradeReportId[20];
    char PartyExecutingFirm[5];
    char PartyExecutingTrader[6];
    char FreeText1[12];
    char FreeText2[12];
    char FreeText4[16];
    char Pad7[7];
} ApproveTesTradeRequestT;

/*
 * Structure: Message Header
 */ 
typedef struct {
    uint32_t BodyLen;
    uint16_t TemplateId;
} MessageHeaderT;

/*
 * Structure: Message
 */ 
typedef struct {
    MessageHeaderT MessageHeader;
} MessageT;

/*
 * Structure: Packet
 */ 
typedef struct {
} PacketT;

#pragma pack(pop)

/*******************************************************************************

Protocol:
   Organization: Eurex Exchange
   Version: 7.1
   Date: Monday, May 27, 2019
   Specification: T7_Enhanced_Trading_Interface_-_Manual_v.1.3.pdf

Source:
   Generator: 1.0.0.0
   Compiler: 2.0
   License: MIT No Attribution License
   Authors: Omi Developers

This file was generated by the Open Markets Initiative (Omi).

Information relating to Omi:
https://github.com/Open-Markets-Initiative/Directory

*******************************************************************************/
