/*******************************************************************************
 * C Structs For Euronext Optiq Sbe MarketDataGateway 3.0 Binary Model
 *******************************************************************************/

/*******************************************************************************
 * Enum Values
 *******************************************************************************/

/*
 * Action Type Values
 */ 
#define ENUM_ACTION_TYPE_NEW_ORDER 1
#define ENUM_ACTION_TYPE_DELETION_OF_IDENTIFIED_ORDER 2
#define ENUM_ACTION_TYPE_DELETION_OF_ALL_ORDERS_BY_SIDE 3
#define ENUM_ACTION_TYPE_MODIFICATION_OF_EXISTING_ORDER_WITHOUT_LOSS_OF_PRIORITY 4
#define ENUM_ACTION_TYPE_RETRANSMISSION_OF_ALL_ORDERS 5
#define ENUM_ACTION_TYPE_MODIFICATION_OF_EXISTING_ORDER_WITH_LOSS_OF_PRIORITY 6
#define ENUM_ACTION_TYPE_RFQ_ANSWERCREATION 7
#define ENUM_ACTION_TYPE_RFQ_ANSWERDELETION 8

/*
 * Block Trade Code Values
 */ 
#define ENUM_BLOCK_TRADE_CODE_BLOCK_TRADE 'B'
#define ENUM_BLOCK_TRADE_CODE_REGULARTRADEOR_NEGOTIATEDDEAL 'N'
#define ENUM_BLOCK_TRADE_CODE_UNDEFINED '-'
#define ENUM_BLOCK_TRADE_CODE_NO_VALUE '0'

/*
 * Book State Values
 */ 
#define ENUM_BOOK_STATE_INACCESSIBLE 1
#define ENUM_BOOK_STATE_CLOSED 2
#define ENUM_BOOK_STATE_CALL 3
#define ENUM_BOOK_STATE_UNCROSSING 4
#define ENUM_BOOK_STATE_CONTINUOUS 5
#define ENUM_BOOK_STATE_HALTED 6
#define ENUM_BOOK_STATE_CONTINUOUS_UNCROSSING 7
#define ENUM_BOOK_STATE_SUSPENDED 8
#define ENUM_BOOK_STATE_RESERVED 9
#define ENUM_BOOK_STATE_NO_VALUE 255

/*
 * Change Type Values
 */ 
#define ENUM_CHANGE_TYPE_STATUS_CHANGES 0
#define ENUM_CHANGE_TYPE_SCHEDULED_EVENT_NOTIFICATION 1
#define ENUM_CHANGE_TYPE_STATUS_CHANGEAND_SCHEDULED_EVENT_NOTIFICATION 2

/*
 * Contract Trading Type Values
 */ 
#define ENUM_CONTRACT_TRADING_TYPE_TRADEDASANOUTRIGHT 1
#define ENUM_CONTRACT_TRADING_TYPE_NOTTRADEDBUTLISTEDINCONTRACTDATA_TRADERSMAYSUBSCRIBETO 2
#define ENUM_CONTRACT_TRADING_TYPE_TRADEDASASIMPLEINTERCOMMODITYSPREAD 3
#define ENUM_CONTRACT_TRADING_TYPE_TRADEDASANINTERCOMMODITYSPREAD 4

/*
 * Contract Type Values
 */ 
#define ENUM_CONTRACT_TYPE_FUTURE 'F'
#define ENUM_CONTRACT_TYPE_OPTION 'O'
#define ENUM_CONTRACT_TYPE_UNDERLYING 'U'
#define ENUM_CONTRACT_TYPE_NO_VALUE '0'

/*
 * Derivatives Instrument Type Values
 */ 
#define ENUM_DERIVATIVES_INSTRUMENT_TYPE_CALL_OPTION 0
#define ENUM_DERIVATIVES_INSTRUMENT_TYPE_PUT_OPTION 1
#define ENUM_DERIVATIVES_INSTRUMENT_TYPE_STRATEGY 2
#define ENUM_DERIVATIVES_INSTRUMENT_TYPE_INDIVIDUAL_FUTURE 3
#define ENUM_DERIVATIVES_INSTRUMENT_TYPE_UNDERLYING 4
#define ENUM_DERIVATIVES_INSTRUMENT_TYPE_NO_VALUE 255

/*
 * Derivatives Market Model Values
 */ 
#define ENUM_DERIVATIVES_MARKET_MODEL_NO_SYNTHETIC_QUOTE 0
#define ENUM_DERIVATIVES_MARKET_MODEL_SPONTANEOUS_IMPLIED_MATCHING 1
#define ENUM_DERIVATIVES_MARKET_MODEL_EVENT_DRIVEN_IMPLIED_MATCHING 2
#define ENUM_DERIVATIVES_MARKET_MODEL_NO_VALUE 255

/*
 * Dynamic Collar Logic Values
 */ 
#define ENUM_DYNAMIC_COLLAR_LOGIC_NOT_ACTIVE 0
#define ENUM_DYNAMIC_COLLAR_LOGIC_NO_HALTWITH_REJECT 2
#define ENUM_DYNAMIC_COLLAR_LOGIC_HALTWITH_ACCEPTATION 3
#define ENUM_DYNAMIC_COLLAR_LOGIC_NO_VALUE 255

/*
 * Effective Date Indicator Values
 */ 
#define ENUM_EFFECTIVE_DATE_INDICATOR_SELLERDECLARATIONISRECEIVEDONTHECURTRADINGSESSIONDAY 0
#define ENUM_EFFECTIVE_DATE_INDICATOR_SELLERDECLARATIONRECEIVEDBEFORETHECURTRADINGSESSIONDAY 1
#define ENUM_EFFECTIVE_DATE_INDICATOR_NO_VALUE 255

/*
 * Efficient Mmt Agency Cross Trade Indicator Values
 */ 
#define ENUM_EFFICIENT_MMT_AGENCY_CROSS_TRADE_INDICATOR_ACTX 'X'
#define ENUM_EFFICIENT_MMT_AGENCY_CROSS_TRADE_INDICATOR_NO_AGENCY_CROSS_TRADE '-'
#define ENUM_EFFICIENT_MMT_AGENCY_CROSS_TRADE_INDICATOR_NO_VALUE '0'

/*
 * Efficient Mmt Algorithmic Indicator Values
 */ 
#define ENUM_EFFICIENT_MMT_ALGORITHMIC_INDICATOR_ALGO 'H'
#define ENUM_EFFICIENT_MMT_ALGORITHMIC_INDICATOR_NO_ALGORITHMIC_TRADE '-'
#define ENUM_EFFICIENT_MMT_ALGORITHMIC_INDICATOR_NO_VALUE '0'

/*
 * Efficient Mmt Benchmark Indicator Values
 */ 
#define ENUM_EFFICIENT_MMT_BENCHMARK_INDICATOR_BENC 'B'
#define ENUM_EFFICIENT_MMT_BENCHMARK_INDICATOR_RFPT 'S'
#define ENUM_EFFICIENT_MMT_BENCHMARK_INDICATOR_NO_BENCHMARKOR_REFERENCE_PRICE_TRADE '-'
#define ENUM_EFFICIENT_MMT_BENCHMARK_INDICATOR_NO_VALUE '0'

/*
 * Efficient Mmt Contributionto Price Values
 */ 
#define ENUM_EFFICIENT_MMT_CONTRIBUTIONTO_PRICE_TNCP 'J'
#define ENUM_EFFICIENT_MMT_CONTRIBUTIONTO_PRICE_PNDG 'N'
#define ENUM_EFFICIENT_MMT_CONTRIBUTIONTO_PRICE_PLAIN_VANILLA_TRADE 'P'
#define ENUM_EFFICIENT_MMT_CONTRIBUTIONTO_PRICE_NPFT 'T'
#define ENUM_EFFICIENT_MMT_CONTRIBUTIONTO_PRICE_NO_VALUE '0'

/*
 * Efficient Mmt Duplicative Indicator Values
 */ 
#define ENUM_EFFICIENT_MMT_DUPLICATIVE_INDICATOR_DUPL '1'
#define ENUM_EFFICIENT_MMT_DUPLICATIVE_INDICATOR_UNIQUE_TRADE_REPORT '-'
#define ENUM_EFFICIENT_MMT_DUPLICATIVE_INDICATOR_NO_VALUE '0'

/*
 * Efficient Mmt Market Mechanism Values
 */ 
#define ENUM_EFFICIENT_MMT_MARKET_MECHANISM_CENTRAL_LIMIT_ORDER_BOOK 1
#define ENUM_EFFICIENT_MMT_MARKET_MECHANISM_QUOTE_DRIVEN_MARKET 2
#define ENUM_EFFICIENT_MMT_MARKET_MECHANISM_DARK_ORDER_BOOK 3
#define ENUM_EFFICIENT_MMT_MARKET_MECHANISM_OFF_BOOKINCLUDING_VOICEOR_MESSAGING_TRADING 4
#define ENUM_EFFICIENT_MMT_MARKET_MECHANISM_PERIODIC_AUCTIONEQUAL_UNCROSSING 5
#define ENUM_EFFICIENT_MMT_MARKET_MECHANISM_REQUESTFOR_QUOTES 6
#define ENUM_EFFICIENT_MMT_MARKET_MECHANISM_OTHER 7
#define ENUM_EFFICIENT_MMT_MARKET_MECHANISM_NO_VALUE 255

/*
 * Efficient Mmt Modification Indicator Values
 */ 
#define ENUM_EFFICIENT_MMT_MODIFICATION_INDICATOR_AMND 'A'
#define ENUM_EFFICIENT_MMT_MODIFICATION_INDICATOR_CANC 'C'
#define ENUM_EFFICIENT_MMT_MODIFICATION_INDICATOR_NEW_TRADE '-'
#define ENUM_EFFICIENT_MMT_MODIFICATION_INDICATOR_NO_VALUE '0'

/*
 * Efficient Mmt Negotiation Indicator Values
 */ 
#define ENUM_EFFICIENT_MMT_NEGOTIATION_INDICATOR_NLIQ '1'
#define ENUM_EFFICIENT_MMT_NEGOTIATION_INDICATOR_OILQ '2'
#define ENUM_EFFICIENT_MMT_NEGOTIATION_INDICATOR_PRIC '3'
#define ENUM_EFFICIENT_MMT_NEGOTIATION_INDICATOR_ILQD '4'
#define ENUM_EFFICIENT_MMT_NEGOTIATION_INDICATOR_SIZE '5'
#define ENUM_EFFICIENT_MMT_NEGOTIATION_INDICATOR_ILQDSIZE '6'
#define ENUM_EFFICIENT_MMT_NEGOTIATION_INDICATOR_NEGOTIATED_TRADE 'N'
#define ENUM_EFFICIENT_MMT_NEGOTIATION_INDICATOR_NO_NEGOTIATED_TRADE '-'
#define ENUM_EFFICIENT_MMT_NEGOTIATION_INDICATOR_NO_VALUE '0'

/*
 * Efficient Mmt Off Book Automated Indicator Values
 */ 
#define ENUM_EFFICIENT_MMT_OFF_BOOK_AUTOMATED_INDICATOR_OFF_BOOK_NON_AUTOMATED 'M'
#define ENUM_EFFICIENT_MMT_OFF_BOOK_AUTOMATED_INDICATOR_OFF_BOOK_AUTOMATED 'Q'
#define ENUM_EFFICIENT_MMT_OFF_BOOK_AUTOMATED_INDICATOR_UNSPECIFIEDORDOESNOTAPPLY '-'
#define ENUM_EFFICIENT_MMT_OFF_BOOK_AUTOMATED_INDICATOR_NO_VALUE '0'

/*
 * Efficient Mmt Post Trade Deferral Values
 */ 
#define ENUM_EFFICIENT_MMT_POST_TRADE_DEFERRAL_LMTF '1'
#define ENUM_EFFICIENT_MMT_POST_TRADE_DEFERRAL_DATF '2'
#define ENUM_EFFICIENT_MMT_POST_TRADE_DEFERRAL_VOLO '3'
#define ENUM_EFFICIENT_MMT_POST_TRADE_DEFERRAL_FWAF '4'
#define ENUM_EFFICIENT_MMT_POST_TRADE_DEFERRAL_IDAF '5'
#define ENUM_EFFICIENT_MMT_POST_TRADE_DEFERRAL_VOLW '6'
#define ENUM_EFFICIENT_MMT_POST_TRADE_DEFERRAL_FULF '7'
#define ENUM_EFFICIENT_MMT_POST_TRADE_DEFERRAL_FULA '8'
#define ENUM_EFFICIENT_MMT_POST_TRADE_DEFERRAL_FULV '9'
#define ENUM_EFFICIENT_MMT_POST_TRADE_DEFERRAL_FULJ 'V'
#define ENUM_EFFICIENT_MMT_POST_TRADE_DEFERRAL_COAF 'W'
#define ENUM_EFFICIENT_MMT_POST_TRADE_DEFERRAL_NOT_APPLICABLE '-'
#define ENUM_EFFICIENT_MMT_POST_TRADE_DEFERRAL_NO_VALUE '0'

/*
 * Efficient Mmt Publication Mode Values
 */ 
#define ENUM_EFFICIENT_MMT_PUBLICATION_MODE_NON_IMMEDIATE_PUBLICATION '1'
#define ENUM_EFFICIENT_MMT_PUBLICATION_MODE_LRGS '2'
#define ENUM_EFFICIENT_MMT_PUBLICATION_MODE_ILQD '3'
#define ENUM_EFFICIENT_MMT_PUBLICATION_MODE_SIZE '4'
#define ENUM_EFFICIENT_MMT_PUBLICATION_MODE_ILQDSIZE '5'
#define ENUM_EFFICIENT_MMT_PUBLICATION_MODE_ILQDLRGS '6'
#define ENUM_EFFICIENT_MMT_PUBLICATION_MODE_IMMEDIATE_PUBLICATION '-'
#define ENUM_EFFICIENT_MMT_PUBLICATION_MODE_NO_VALUE '0'

/*
 * Efficient Mmt Special Dividend Indicator Values
 */ 
#define ENUM_EFFICIENT_MMT_SPECIAL_DIVIDEND_INDICATOR_SDIV 'E'
#define ENUM_EFFICIENT_MMT_SPECIAL_DIVIDEND_INDICATOR_NO_SPECIAL_DIVIDEND_TRADE '-'
#define ENUM_EFFICIENT_MMT_SPECIAL_DIVIDEND_INDICATOR_NO_VALUE '0'

/*
 * Efficient Mmt Trading Mode Values
 */ 
#define ENUM_EFFICIENT_MMT_TRADING_MODE_UNDEFINED_AUCTIONEQUAL_UNCROSSING '1'
#define ENUM_EFFICIENT_MMT_TRADING_MODE_CONTINUOUS_TRADING '2'
#define ENUM_EFFICIENT_MMT_TRADING_MODE_AT_MARKET_CLOSE_TRADING '3'
#define ENUM_EFFICIENT_MMT_TRADING_MODE_OUTOF_MAIN_SESSION_TRADING '4'
#define ENUM_EFFICIENT_MMT_TRADING_MODE_TRADE_REPORTING_ON_EXCHANGE '5'
#define ENUM_EFFICIENT_MMT_TRADING_MODE_TRADE_REPORTING_OFF_EXCHANGE '6'
#define ENUM_EFFICIENT_MMT_TRADING_MODE_TRADE_REPORTING_SYSTEMATIC_INTERNALISER '7'
#define ENUM_EFFICIENT_MMT_TRADING_MODE_SCHEDULED_INTRADAY_AUCTIONEQUAL_UNCROSSING 'I'
#define ENUM_EFFICIENT_MMT_TRADING_MODE_SCHEDULED_CLOSING_AUCTIONEQUAL_UNCROSSING 'K'
#define ENUM_EFFICIENT_MMT_TRADING_MODE_SCHEDULED_OPENING_AUCTIONEQUAL_UNCROSSING 'O'
#define ENUM_EFFICIENT_MMT_TRADING_MODE_UNSCHEDULED_AUCTIONEQUAL_UNCROSSING 'U'
#define ENUM_EFFICIENT_MMT_TRADING_MODE_NO_VALUE '0'

/*
 * Efficient Mmt Transaction Category Values
 */ 
#define ENUM_EFFICIENT_MMT_TRANSACTION_CATEGORY_DARK_TRADE 'D'
#define ENUM_EFFICIENT_MMT_TRANSACTION_CATEGORY_RPRI 'R'
#define ENUM_EFFICIENT_MMT_TRANSACTION_CATEGORY_XFPH 'Y'
#define ENUM_EFFICIENT_MMT_TRANSACTION_CATEGORY_TPAC 'Z'
#define ENUM_EFFICIENT_MMT_TRANSACTION_CATEGORY_NONEAPPLY '-'
#define ENUM_EFFICIENT_MMT_TRANSACTION_CATEGORY_NO_VALUE '0'

/*
 * Emm Values
 */ 
#define ENUM_EMM_CASHAND_DERIVATIVE_CENTRAL_ORDER_BOOK 1
#define ENUM_EMM_NAV_TRADING_FACILITY 2
#define ENUM_EMM_DERIVATIVES_WHOLESALES 4
#define ENUM_EMM_CASH_ON_EXCHANGE_OFFBOOK 5
#define ENUM_EMM_EURONEXTOFFEXCHANGETRADEREPORTS 6
#define ENUM_EMM_DERIVATIVES_ON_EXCHANGE_OFFBOOK 7
#define ENUM_EMM_ETFMTFNAV_CENTRAL_ORDER_BOOK 8
#define ENUM_EMM_LISTEDNOTTRADED 9
#define ENUM_EMM_DELTA_NEUTRAL_CONTINGENCY_LEG 15
#define ENUM_EMM_NOT_APPLICABLE 99
#define ENUM_EMM_NO_VALUE 255

/*
 * Exchange Code Values
 */ 
#define ENUM_EXCHANGE_CODE_AMSTERDAM_EQUITY_DERIVATIVES 'A'
#define ENUM_EXCHANGE_CODE_BRUSSELS_EQUITY_DERIVATIVES 'B'
#define ENUM_EXCHANGE_CODE_PARIS_EQUITY_UNDERLYINGS 'C'
#define ENUM_EXCHANGE_CODE_BRUSSELS_CASH_UNDERLYINGS 'D'
#define ENUM_EXCHANGE_CODE_BRUSSELS_INDEX_DERIVATIVES 'F'
#define ENUM_EXCHANGE_CODE_AMSTERDAM_CASH_UNDERLYINGS 'G'
#define ENUM_EXCHANGE_CODE_LISBON_CASH_UNDERLYINGS 'H'
#define ENUM_EXCHANGE_CODE_PARIS_INDEX_DERIVATIVES 'J'
#define ENUM_EXCHANGE_CODE_AMSTERDAM_INDEX_DERIVATIVES 'K'
#define ENUM_EXCHANGE_CODE_LISBON_INDEX_DERIVATIVES 'M'
#define ENUM_EXCHANGE_CODE_PARIS_EQUITY_DERIVATIVES 'P'
#define ENUM_EXCHANGE_CODE_AMSTERDAM_COMMODITIES_DERIVATIVES 'R'
#define ENUM_EXCHANGE_CODE_LISBON_EQUITY_DERIVATIVES 'S'
#define ENUM_EXCHANGE_CODE_PARIS_COMMODITIES_DERIVATIVES 'Y'
#define ENUM_EXCHANGE_CODE_AMSTERDAM_CURRENCY_DERIVATIVES 'Z'

/*
 * Exer Style Values
 */ 
#define ENUM_EXER_STYLE_EUROPEAN 0
#define ENUM_EXER_STYLE_AMERICAN 1
#define ENUM_EXER_STYLE_ASIAN 2
#define ENUM_EXER_STYLE_BERMUDAN 3
#define ENUM_EXER_STYLE_OTHER 4
#define ENUM_EXER_STYLE_NO_VALUE 255

/*
 * Expiry Cycle Type Values
 */ 
#define ENUM_EXPIRY_CYCLE_TYPE_DAILY 1
#define ENUM_EXPIRY_CYCLE_TYPE_WEEKLY 2
#define ENUM_EXPIRY_CYCLE_TYPE_MONTHLY 3
#define ENUM_EXPIRY_CYCLE_TYPE_NO_VALUE 255

/*
 * Guarantee Indicator Values
 */ 
#define ENUM_GUARANTEE_INDICATOR_THISINSTRUMENTISNOTGUARANTEED 0
#define ENUM_GUARANTEE_INDICATOR_THISINSTRUMENTISGUARANTEED 1
#define ENUM_GUARANTEE_INDICATOR_THISINSTRUMENTISNOTCLEARABLE 2
#define ENUM_GUARANTEE_INDICATOR_GUARANTEED_CLEARED_BORROWING_LENDING_SERVICE 8
#define ENUM_GUARANTEE_INDICATOR_NO_VALUE 255

/*
 * Imbalance Qty Side Values
 */ 
#define ENUM_IMBALANCE_QTY_SIDE_NOIMBALANCE 0
#define ENUM_IMBALANCE_QTY_SIDE_BUY 1
#define ENUM_IMBALANCE_QTY_SIDE_SELL 2
#define ENUM_IMBALANCE_QTY_SIDE_NO_VALUE 255

/*
 * Index Level Type Values
 */ 
#define ENUM_INDEX_LEVEL_TYPE_INDICATIVE_INDEX 0
#define ENUM_INDEX_LEVEL_TYPE_OFFICIAL_OPENING_INDEX 1
#define ENUM_INDEX_LEVEL_TYPE_REAL_TIME_INDEX 2
#define ENUM_INDEX_LEVEL_TYPE_AUTOMATIC_INDICATIVE_INDEX 3
#define ENUM_INDEX_LEVEL_TYPE_PRELIMINARY_REFERENCE_INDEX 4
#define ENUM_INDEX_LEVEL_TYPE_CLOSING_REFERENCE_INDEX 5
#define ENUM_INDEX_LEVEL_TYPE_CONFIRMED_REFERENCE_INDEX 6
#define ENUM_INDEX_LEVEL_TYPE_OPTIONS_LIQUIDATION_INDEX 7

/*
 * Index Price Code Values
 */ 
#define ENUM_INDEX_PRICE_CODE_ONLY_INDEX 0
#define ENUM_INDEX_PRICE_CODE_INDEXAND_SESSION_HIGH 1
#define ENUM_INDEX_PRICE_CODE_INDEXAND_SESSION_LOW 2
#define ENUM_INDEX_PRICE_CODE_INDEXAND_SESSION_HIGHAND_LOWTYPICALLYFIRSTPRICE 3
#define ENUM_INDEX_PRICE_CODE_ONLY_SESSION_HIGH 4
#define ENUM_INDEX_PRICE_CODE_ONLY_SESSION_LOW 5
#define ENUM_INDEX_PRICE_CODE_PREVIOUS_DAY_CLOSE 6

/*
 * Inst Unit Exp Values
 */ 
#define ENUM_INST_UNIT_EXP_UNITS 1
#define ENUM_INST_UNIT_EXP_PERCENTAGEOF_NOMINAL_EXCLUDING_ACCRUED_INTEREST_CLEAN 2
#define ENUM_INST_UNIT_EXP_BASIS_POINTS 3
#define ENUM_INST_UNIT_EXP_PERCENTAGEOF_NOMINAL_INCLUDING_ACCRUED_INTEREST_DIRTY 5
#define ENUM_INST_UNIT_EXP_KILOGRAMS 8
#define ENUM_INST_UNIT_EXP_OUNCES 9
#define ENUM_INST_UNIT_EXP_NO_VALUE 255

/*
 * Instrument State Values
 */ 
#define ENUM_INSTRUMENT_STATE_SCHEDULED 1
#define ENUM_INSTRUMENT_STATE_SUSPENDEDDUETO_UNDERLYING 2
#define ENUM_INSTRUMENT_STATE_SUSPENDED_KOBI 3
#define ENUM_INSTRUMENT_STATE_SUSPENDED_KOBE 4
#define ENUM_INSTRUMENT_STATE_SUSPENDED_NEW_LISTING 5
#define ENUM_INSTRUMENT_STATE_SUSPENDEDBY_MO 6
#define ENUM_INSTRUMENT_STATE_SUSPENDED_TECHNICAL 7
#define ENUM_INSTRUMENT_STATE_RESERVED_DYNAMIC_COLLARS 8
#define ENUM_INSTRUMENT_STATE_RESERVED_STATIC_COLLARS 9
#define ENUM_INSTRUMENT_STATE_RESERVED_WAITING_FOR_LP 10
#define ENUM_INSTRUMENT_STATE_RESERVED_LP_LIMIT 11
#define ENUM_INSTRUMENT_STATE_INSTRUMENT_DELETION 12
#define ENUM_INSTRUMENT_STATE_SUSPENDED_WAITINGFOR_BBO 13
#define ENUM_INSTRUMENT_STATE_SUSPENDED_WAITINGFOR_TRADABLE_STATE 14
#define ENUM_INSTRUMENT_STATE_RANDOM_UNCROSSING_PERIOD 15
#define ENUM_INSTRUMENT_STATE_EXPIRED 16
#define ENUM_INSTRUMENT_STATE_UNCROSSING 17
#define ENUM_INSTRUMENT_STATE_RESERVEDDUETO_LEG 18
#define ENUM_INSTRUMENT_STATE_SUSPENDEDDUETO_LEG 19
#define ENUM_INSTRUMENT_STATE_NO_VALUE 255

/*
 * Leg Buy Sell Values
 */ 
#define ENUM_LEG_BUY_SELL_BUY 'B'
#define ENUM_LEG_BUY_SELL_SELL 'S'

/*
 * Market Model Values
 */ 
#define ENUM_MARKET_MODEL_ORDER_DRIVEN 1
#define ENUM_MARKET_MODEL_QUOTE_DRIVEN 2
#define ENUM_MARKET_MODEL_IPO 3
#define ENUM_MARKET_MODEL_PRIMARY_MARKET 4
#define ENUM_MARKET_MODEL_RFQ 5
#define ENUM_MARKET_MODEL_CONDITIONAL_UNCROSSING 6
#define ENUM_MARKET_MODEL_NO_VALUE 255

/*
 * Message Price Notation Values
 */ 
#define ENUM_MESSAGE_PRICE_NOTATION_PRICE 1
#define ENUM_MESSAGE_PRICE_NOTATION_SPREADINBASISPOINTS 2
#define ENUM_MESSAGE_PRICE_NOTATION_SPREAD 3
#define ENUM_MESSAGE_PRICE_NOTATION_NO_VALUE 255

/*
 * Mmt Market Mechanism Values
 */ 
#define ENUM_MMT_MARKET_MECHANISM_CENTRAL_LIMIT_ORDER_BOOK 1
#define ENUM_MMT_MARKET_MECHANISM_QUOTE_DRIVEN_MARKET 2
#define ENUM_MMT_MARKET_MECHANISM_DARK_ORDER_BOOK 3
#define ENUM_MMT_MARKET_MECHANISM_OFF_BOOKINCLUDING_VOICEOR_MESSAGING_TRADING 4
#define ENUM_MMT_MARKET_MECHANISM_PERIODIC_AUCTIONEQUAL_UNCROSSING 5
#define ENUM_MMT_MARKET_MECHANISM_REQUESTFOR_QUOTES 6
#define ENUM_MMT_MARKET_MECHANISM_NO_VALUE 255

/*
 * Mmt Off Book Automated Indicator Values
 */ 
#define ENUM_MMT_OFF_BOOK_AUTOMATED_INDICATOR_OFF_BOOK_NON_AUTOMATED 'M'
#define ENUM_MMT_OFF_BOOK_AUTOMATED_INDICATOR_OFF_BOOK_AUTOMATED 'Q'
#define ENUM_MMT_OFF_BOOK_AUTOMATED_INDICATOR_UNSPECIFIEDORDOESNOTAPPLY '-'
#define ENUM_MMT_OFF_BOOK_AUTOMATED_INDICATOR_NO_VALUE '0'

/*
 * Mmt Trading Mode Values
 */ 
#define ENUM_MMT_TRADING_MODE_UNDEFINED_AUCTIONEQUAL_UNCROSSING '1'
#define ENUM_MMT_TRADING_MODE_CONTINUOUS_TRADING '2'
#define ENUM_MMT_TRADING_MODE_AT_MARKET_CLOSE_TRADING '3'
#define ENUM_MMT_TRADING_MODE_OUTOF_MAIN_SESSION_TRADING '4'
#define ENUM_MMT_TRADING_MODE_TRADE_REPORTING_ON_EXCHANGE '5'
#define ENUM_MMT_TRADING_MODE_TRADE_REPORTING_OFF_EXCHANGE '6'
#define ENUM_MMT_TRADING_MODE_TRADE_REPORTING_SYSTEMATIC_INTERNALISER '7'
#define ENUM_MMT_TRADING_MODE_SCHEDULED_INTRADAY_AUCTIONEQUAL_UNCROSSING 'I'
#define ENUM_MMT_TRADING_MODE_SCHEDULED_CLOSING_AUCTIONEQUAL_UNCROSSING 'K'
#define ENUM_MMT_TRADING_MODE_SCHEDULED_OPENING_AUCTIONEQUAL_UNCROSSING 'O'
#define ENUM_MMT_TRADING_MODE_UNSCHEDULED_AUCTIONEQUAL_UNCROSSING 'U'
#define ENUM_MMT_TRADING_MODE_NO_VALUE '0'

/*
 * Option Type Values
 */ 
#define ENUM_OPTION_TYPE_CALL 1
#define ENUM_OPTION_TYPE_PUT 2
#define ENUM_OPTION_TYPE_NO_VALUE 255

/*
 * Optiq Segment Values
 */ 
#define ENUM_OPTIQ_SEGMENT_EQUITIES 1
#define ENUM_OPTIQ_SEGMENT_FUNDS 2
#define ENUM_OPTIQ_SEGMENT_FIXED_INCOME 3
#define ENUM_OPTIQ_SEGMENT_WARRANTSAND_CERTIFICATES 4
#define ENUM_OPTIQ_SEGMENT_BOURSEDE_LUXEMBOURG 5
#define ENUM_OPTIQ_SEGMENT_OPTIONS 6
#define ENUM_OPTIQ_SEGMENT_FUTURES 7
#define ENUM_OPTIQ_SEGMENT_COMMODITIES 8
#define ENUM_OPTIQ_SEGMENT_INDICES 9
#define ENUM_OPTIQ_SEGMENT_TRADE_REPORTINGAND_PUBLICATION 10
#define ENUM_OPTIQ_SEGMENT_BLOCK 14
#define ENUM_OPTIQ_SEGMENT_INDEX_DERIVATIVES 11
#define ENUM_OPTIQ_SEGMENT_EQUITY_DERIVATIVES 12
#define ENUM_OPTIQ_SEGMENT_FINANCIAL_DERIVATIVES 13
#define ENUM_OPTIQ_SEGMENT_FOREX 15

/*
 * Order Entry Qualifier Values
 */ 
#define ENUM_ORDER_ENTRY_QUALIFIER_ORDER_ENTRY_CANCEL_MODIFY_DISABLED 0
#define ENUM_ORDER_ENTRY_QUALIFIER_ORDER_ENTRY_CANCEL_MODIFY_ENABLED 1
#define ENUM_ORDER_ENTRY_QUALIFIER_CANCELAND_MODIFY_ONLY 2
#define ENUM_ORDER_ENTRY_QUALIFIER_CANCEL_ONLY 3
#define ENUM_ORDER_ENTRY_QUALIFIER_NO_VALUE 255

/*
 * Order Side Values
 */ 
#define ENUM_ORDER_SIDE_BUY 1
#define ENUM_ORDER_SIDE_SELL 2
#define ENUM_ORDER_SIDE_CROSS 3
#define ENUM_ORDER_SIDE_NO_VALUE 255

/*
 * Order Type Values
 */ 
#define ENUM_ORDER_TYPE_MARKET 1
#define ENUM_ORDER_TYPE_LIMIT 2
#define ENUM_ORDER_TYPE_STOPMARKETOR_STOPMARKETONQUOTE 3
#define ENUM_ORDER_TYPE_STOPLIMITOR_STOPLIMITONQUOTE 4
#define ENUM_ORDER_TYPE_PRIMARY_PEG 5
#define ENUM_ORDER_TYPE_MARKETTOLIMIT 6
#define ENUM_ORDER_TYPE_MARKET_PEG 7
#define ENUM_ORDER_TYPE_MID_POINT_PEG 8
#define ENUM_ORDER_TYPE_AVERAGE_PRICE 9
#define ENUM_ORDER_TYPE_ICEBERG 10
#define ENUM_ORDER_TYPE_NO_VALUE 255

/*
 * Phase Id Values
 */ 
#define ENUM_PHASE_ID_INACCESSIBLE 1
#define ENUM_PHASE_ID_CLOSED 2
#define ENUM_PHASE_ID_CALL 3
#define ENUM_PHASE_ID_UNCROSSING 4
#define ENUM_PHASE_ID_CONTINUOUS 5
#define ENUM_PHASE_ID_CONTINUOUS_UNCROSSING 7

/*
 * Price Limits Values
 */ 
#define ENUM_PRICE_LIMITS_PRICE_LIMITS_ENABLED_NORMAL 1
#define ENUM_PRICE_LIMITS_PRICE_LIMITS_ENABLED_WIDE 2
#define ENUM_PRICE_LIMITS_PRICE_LIMITS_ENABLED_WIDEST 3
#define ENUM_PRICE_LIMITS_PRICE_LIMITS_DISABLED 4
#define ENUM_PRICE_LIMITS_NO_VALUE 255

/*
 * Price Type Values
 */ 
#define ENUM_PRICE_TYPE_OFFICIAL_DAILY 2
#define ENUM_PRICE_TYPE_OFFICIAL_MARKET_CLOSE 4
#define ENUM_PRICE_TYPE_OFFICIAL_EXPIRY 6
#define ENUM_PRICE_TYPE_PROVISIONAL_INTRADAY 7
#define ENUM_PRICE_TYPE_OFFICIAL_INTRADAY 8
#define ENUM_PRICE_TYPE_OFFICIAL_YDSP 9
#define ENUM_PRICE_TYPE_NA_VFORTHEINSTRUMENTSELIGIBLETOTHE_NAV_TRADING_FACILITY 10
#define ENUM_PRICE_TYPE_ADJUSTED_CLOSING_PRICE 12
#define ENUM_PRICE_TYPE_SUBSCRIPTION_PRICE 13
#define ENUM_PRICE_TYPE_INDICATIVE_MATCHING_PRICE 14
#define ENUM_PRICE_TYPE_MIN_PRICE_OUTOF_SESSION_TRADES 19
#define ENUM_PRICE_TYPE_MAX_PRICE_OUTOF_SESSION_TRADES 20
#define ENUM_PRICE_TYPE_MIN_PRICE_OUTOF_SESSION_BLOCK_TRADES 21
#define ENUM_PRICE_TYPE_MAX_PRICE_OUTOF_SESSION_BLOCK_TRADES 22
#define ENUM_PRICE_TYPE_VALUATION_PRICE 23
#define ENUM_PRICE_TYPE_FUND_SUBSCRIPTION 24
#define ENUM_PRICE_TYPE_FUND_REDEMPTION 25
#define ENUM_PRICE_TYPE_UNCROSSING_PRICE 26
#define ENUM_PRICE_TYPE_LAST_TRADED_PRICE 27
#define ENUM_PRICE_TYPE_AIP 28
#define ENUM_PRICE_TYPE_NET_ASSET_VALUE 30
#define ENUM_PRICE_TYPE_EXTERNAL_REFERENCE_PRICE 31

/*
 * Pricing Algorithm Values
 */ 
#define ENUM_PRICING_ALGORITHM_STANDARD 0
#define ENUM_PRICING_ALGORITHM_TOTAL_RETURN_FUTURE 1
#define ENUM_PRICING_ALGORITHM_MARKET_ON_CLOSE 2

/*
 * Quote Spread Multiplier Values
 */ 
#define ENUM_QUOTE_SPREAD_MULTIPLIER_QUOTE_SPREAD_MULTIPLIER_1 1
#define ENUM_QUOTE_SPREAD_MULTIPLIER_QUOTE_SPREAD_MULTIPLIER_2 2
#define ENUM_QUOTE_SPREAD_MULTIPLIER_QUOTE_SPREAD_MULTIPLIER_3 3
#define ENUM_QUOTE_SPREAD_MULTIPLIER_NO_VALUE 255

/*
 * Quote Update Type Values
 */ 
#define ENUM_QUOTE_UPDATE_TYPE_BEST_BID 1
#define ENUM_QUOTE_UPDATE_TYPE_BEST_OFFER 2
#define ENUM_QUOTE_UPDATE_TYPE_CANCEL_BID 5
#define ENUM_QUOTE_UPDATE_TYPE_CANCEL_OFFER 6

/*
 * Reference Price Origin In Continuous Values
 */ 
#define ENUM_REFERENCE_PRICE_ORIGIN_IN_CONTINUOUS_INTERNAL 1
#define ENUM_REFERENCE_PRICE_ORIGIN_IN_CONTINUOUS_EXTERNAL 2
#define ENUM_REFERENCE_PRICE_ORIGIN_IN_CONTINUOUS_EXTERNAL_BBO 3
#define ENUM_REFERENCE_PRICE_ORIGIN_IN_CONTINUOUS_OPENING_CALL_PRICE 4
#define ENUM_REFERENCE_PRICE_ORIGIN_IN_CONTINUOUS_MID_BB_OOR_FAIR_VALUE 5
#define ENUM_REFERENCE_PRICE_ORIGIN_IN_CONTINUOUS_FAIR_VALUE 6
#define ENUM_REFERENCE_PRICE_ORIGIN_IN_CONTINUOUS_FUTURE_MARKET_PRICE 7
#define ENUM_REFERENCE_PRICE_ORIGIN_IN_CONTINUOUS_NO_VALUE 255

/*
 * Reference Price Origin In Opening Call Values
 */ 
#define ENUM_REFERENCE_PRICE_ORIGIN_IN_OPENING_CALL_INTERNAL 1
#define ENUM_REFERENCE_PRICE_ORIGIN_IN_OPENING_CALL_EXTERNAL 2
#define ENUM_REFERENCE_PRICE_ORIGIN_IN_OPENING_CALL_EXTERNAL_BBO 3
#define ENUM_REFERENCE_PRICE_ORIGIN_IN_OPENING_CALL_OPENING_CALL_PRICE 4
#define ENUM_REFERENCE_PRICE_ORIGIN_IN_OPENING_CALL_MID_BB_OOR_FAIR_VALUE 5
#define ENUM_REFERENCE_PRICE_ORIGIN_IN_OPENING_CALL_FAIR_VALUE 6
#define ENUM_REFERENCE_PRICE_ORIGIN_IN_OPENING_CALL_FUTURE_MARKET_PRICE 7
#define ENUM_REFERENCE_PRICE_ORIGIN_IN_OPENING_CALL_NO_VALUE 255

/*
 * Reference Price Origin In Trading Interruption Values
 */ 
#define ENUM_REFERENCE_PRICE_ORIGIN_IN_TRADING_INTERRUPTION_INTERNAL 1
#define ENUM_REFERENCE_PRICE_ORIGIN_IN_TRADING_INTERRUPTION_EXTERNAL 2
#define ENUM_REFERENCE_PRICE_ORIGIN_IN_TRADING_INTERRUPTION_EXTERNAL_BBO 3
#define ENUM_REFERENCE_PRICE_ORIGIN_IN_TRADING_INTERRUPTION_OPENING_CALL_PRICE 4
#define ENUM_REFERENCE_PRICE_ORIGIN_IN_TRADING_INTERRUPTION_MID_BB_OOR_FAIR_VALUE 5
#define ENUM_REFERENCE_PRICE_ORIGIN_IN_TRADING_INTERRUPTION_FAIR_VALUE 6
#define ENUM_REFERENCE_PRICE_ORIGIN_IN_TRADING_INTERRUPTION_FUTURE_MARKET_PRICE 7
#define ENUM_REFERENCE_PRICE_ORIGIN_IN_TRADING_INTERRUPTION_NO_VALUE 255

/*
 * Repo Indicator Values
 */ 
#define ENUM_REPO_INDICATOR_INSTRNEITHERELIGIBLEFOR_SR_DOR_LOANAND_LENDING_MKT 0
#define ENUM_REPO_INDICATOR_INSTRELIGIBLEFOR_SR_DANDFOR_LOANAND_LENDING_MARKET 1
#define ENUM_REPO_INDICATOR_INSTRELIGIBLEFORTHE_SR_DLONGONLY 2
#define ENUM_REPO_INDICATOR_INSTRELIGIBLEFOR_LOANAND_LENDING_MKTANDFOR_SR_DLONGONLY 3
#define ENUM_REPO_INDICATOR_EASYTOBORROW_INSTRELIGIBLEFOR_SR_DANDFOR_LOANAND_LENDING_MKT 4
#define ENUM_REPO_INDICATOR_INSTRELIGIBLEFORTHE_LOANAND_LENDING_MARKET 5
#define ENUM_REPO_INDICATOR_NONSIGNIFICANT 8
#define ENUM_REPO_INDICATOR_NO_VALUE 255

/*
 * Scheduled Event Values
 */ 
#define ENUM_SCHEDULED_EVENT_CANCEL_PREVIOUSLY_SCHEDULED_EVENT 0
#define ENUM_SCHEDULED_EVENT_REOPENING 1
#define ENUM_SCHEDULED_EVENT_RESUMPTIONOFTRADING 3
#define ENUM_SCHEDULED_EVENT_CLOSED 4
#define ENUM_SCHEDULED_EVENT_EXPIRY 5
#define ENUM_SCHEDULED_EVENT_WHOLESALE_LARGEIN_SCALE_LI_STRADESOPENEXTENSION 6
#define ENUM_SCHEDULED_EVENT_WHOLESALE_BASISTRADESOPENEXTENSION 7
#define ENUM_SCHEDULED_EVENT_WHOLESALE_AGAINST_ACTUALSTRADESOPENEXTENSION 8
#define ENUM_SCHEDULED_EVENT_WHOLESALE_LARGEIN_SCALE_LI_S_PACKAGETRADESOPENEXTENSION 9
#define ENUM_SCHEDULED_EVENT_WHOLESALE_EXCHANGE_FOR_SWAPSTRADESOPENEXTENSION 10
#define ENUM_SCHEDULED_EVENT_WHOLESALE_TRADES_OPEN_EXTENSION 11
#define ENUM_SCHEDULED_EVENT_SUSPENSION 12
#define ENUM_SCHEDULED_EVENT_COLLARS_NORMAL 13
#define ENUM_SCHEDULED_EVENT_COLLARS_WIDE 14
#define ENUM_SCHEDULED_EVENT_PRE_EXPIRY 15
#define ENUM_SCHEDULED_EVENT_NO_VALUE 255

/*
 * Session Values
 */ 
#define ENUM_SESSION_SESSION_0 0
#define ENUM_SESSION_SESSION_1 1
#define ENUM_SESSION_SESSION_2 2
#define ENUM_SESSION_SESSION_3 3
#define ENUM_SESSION_SESSION_4 4
#define ENUM_SESSION_SESSION_5 5
#define ENUM_SESSION_SESSION_6 6
#define ENUM_SESSION_SESSION_7 7
#define ENUM_SESSION_SESSION_8 8
#define ENUM_SESSION_SESSION_9 9

/*
 * Stats Update Type Values
 */ 
#define ENUM_STATS_UPDATE_TYPE_DAILY_HIGH 5
#define ENUM_STATS_UPDATE_TYPE_DAILY_LOW 6
#define ENUM_STATS_UPDATE_TYPE_YEARLY_HIGH 7
#define ENUM_STATS_UPDATE_TYPE_YEARLY_LOW 8
#define ENUM_STATS_UPDATE_TYPE_LIFETIME_HIGH 9
#define ENUM_STATS_UPDATE_TYPE_LIFETIME_LOW 10
#define ENUM_STATS_UPDATE_TYPE_VARIATION_LAST_PRICE 14
#define ENUM_STATS_UPDATE_TYPE_OPEN_PRICE 15
#define ENUM_STATS_UPDATE_TYPE_TRADE_COUNT 16
#define ENUM_STATS_UPDATE_TYPE_LAST_TRADED_PRICE 17
#define ENUM_STATS_UPDATE_TYPE_PERCENT_VARIATION_PREVIOUS_CLOSE 18
#define ENUM_STATS_UPDATE_TYPE_OFF_BOOK_CUMUL_QTY 19
#define ENUM_STATS_UPDATE_TYPE_ON_BOOK_AUCTION_CUMUL_QTY 21
#define ENUM_STATS_UPDATE_TYPE_ON_BOOK_CONTINUOUS_CUMUL_QTY 22
#define ENUM_STATS_UPDATE_TYPE_ONAND_OFF_BOOK_CUMUL_QTY 23

/*
 * Status Reason Values
 */ 
#define ENUM_STATUS_REASON_SCHEDULED 0
#define ENUM_STATUS_REASON_COLLARS_BREACH 4
#define ENUM_STATUS_REASON_AUTOMATIC_REOPENING 7
#define ENUM_STATUS_REASON_NO_LIQUIDITY_PROVIDER 8
#define ENUM_STATUS_REASON_KNOCK_INBY_ISSUER 11
#define ENUM_STATUS_REASON_KNOCK_OUTBY_EXCHANGE 12
#define ENUM_STATUS_REASON_KNOCK_OUTBY_ISSUER 13
#define ENUM_STATUS_REASON_ACTIONBY_MARKET_OPERATIONS 15
#define ENUM_STATUS_REASON_WAITINGFOR_TRADABLE_STATE 16
#define ENUM_STATUS_REASON_NEW_LISTING 20
#define ENUM_STATUS_REASON_DUETO_UNDERLYING 21
#define ENUM_STATUS_REASON_OUTSIDEOF_L_PQUOTES 22
#define ENUM_STATUS_REASON_TECHNICAL 23
#define ENUM_STATUS_REASON_DUETO_LEG 24
#define ENUM_STATUS_REASON_NO_VALUE 255

/*
 * Strategy Code Values
 */ 
#define ENUM_STRATEGY_CODE_JELLY_ROLL 'A'
#define ENUM_STRATEGY_CODE_BUTTERFLY 'B'
#define ENUM_STRATEGY_CODE_CALLOR_PUT_CABINET 'C'
#define ENUM_STRATEGY_CODE_SPREAD 'D'
#define ENUM_STRATEGY_CODE_CALENDAR_SPREAD 'E'
#define ENUM_STRATEGY_CODE_DIAGONAL_CALENDAR_SPREAD 'F'
#define ENUM_STRATEGY_CODE_GUTS 'G'
#define ENUM_STRATEGY_CODE_TWOBY_ONE_RATIO_SPREAD 'H'
#define ENUM_STRATEGY_CODE_IRON_BUTTERFLY 'I'
#define ENUM_STRATEGY_CODE_COMBO 'J'
#define ENUM_STRATEGY_CODE_STRANGLE 'K'
#define ENUM_STRATEGY_CODE_LADDER 'L'
#define ENUM_STRATEGY_CODE_STRIP 'M'
#define ENUM_STRATEGY_CODE_STRADDLE_CALENDAR_SPREAD 'N'
#define ENUM_STRATEGY_CODE_PACK 'O'
#define ENUM_STRATEGY_CODE_DIAGONAL_STRADDLE_CALENDAR_SPREAD 'P'
#define ENUM_STRATEGY_CODE_SIMPLE_INTER_COMMODITY_SPREAD 'Q'
#define ENUM_STRATEGY_CODE_CONVERSION_REVERSAL 'R'
#define ENUM_STRATEGY_CODE_STRADDLE 'S'
#define ENUM_STRATEGY_CODE_VOLATILITY_TRADE 'V'
#define ENUM_STRATEGY_CODE_CONDOR 'W'
#define ENUM_STRATEGY_CODE_BOX 'X'
#define ENUM_STRATEGY_CODE_BUNDLE 'Y'
#define ENUM_STRATEGY_CODE_REDUCED_TICK_SPREAD 'Z'
#define ENUM_STRATEGY_CODE_LADDERVERSUS_UNDERLYING 'a'
#define ENUM_STRATEGY_CODE_BUTTERFLYVERSUS_UNDERLYING 'b'
#define ENUM_STRATEGY_CODE_CALL_SPREADVERSUS_PUTVERSUS_UNDERLYING 'c'
#define ENUM_STRATEGY_CODE_CALLOR_PUT_SPREADVERSUS_UNDERLYING 'd'
#define ENUM_STRATEGY_CODE_CALLOR_PUT_CALENDAR_SPREADVERSUS_UNDERLYING 'e'
#define ENUM_STRATEGY_CODE_CALL_PUT_DIAGONAL_CALENDAR_SPREADVERSUS_UNDERLYING 'f'
#define ENUM_STRATEGY_CODE_GUTSVERSUS_UNDERLYING 'g'
#define ENUM_STRATEGY_CODE_TWOBY_ONE_CALLOR_PUT_RATIO_SPREADVERSUS_UNDERLYING 'h'
#define ENUM_STRATEGY_CODE_IRON_BUTTERFLYVERSUS_UNDERLYING 'i'
#define ENUM_STRATEGY_CODE_COMBOVERSUS_UNDERLYING 'j'
#define ENUM_STRATEGY_CODE_STRANGLEVERSUS_UNDERLYING 'k'
#define ENUM_STRATEGY_CODE_EXCHANGEFOR_PHYSICAL 'm'
#define ENUM_STRATEGY_CODE_STRADDLE_CALENDAR_SPREADVERSUS_UNDERLYING 'n'
#define ENUM_STRATEGY_CODE_PUT_SPREADVERSUS_CALLVERSUS_UNDERLYING 'p'
#define ENUM_STRATEGY_CODE_DIAGONAL_STRADDLE_CALENDAR_SPREADVERSUS_UNDERLYING 'q'
#define ENUM_STRATEGY_CODE_SYNTHETIC 'r'
#define ENUM_STRATEGY_CODE_STRADDLEVERSUS_UNDERLYING 's'
#define ENUM_STRATEGY_CODE_CONDORVERSUS_UNDERLYING 't'
#define ENUM_STRATEGY_CODE_BUY_WRITE 'u'
#define ENUM_STRATEGY_CODE_IRON_CONDORVERSUS_UNDERLYING 'v'
#define ENUM_STRATEGY_CODE_IRON_CONDOR 'w'
#define ENUM_STRATEGY_CODE_CALL_SPREADVERSUS_SELLA_PUT 'x'
#define ENUM_STRATEGY_CODE_PUT_SPREADVERSUS_SELLA_CALL 'y'
#define ENUM_STRATEGY_CODE_PUT_STRADDLEVERSUS_SELLA_CALLORA_PUT 'z'

/*
 * Strike Currency Indicator Values
 */ 
#define ENUM_STRIKE_CURRENCY_INDICATOR_CHANGERATENOTAPPLIEDTOTHESTRIKEPRICE 0
#define ENUM_STRIKE_CURRENCY_INDICATOR_CHANGERATEAPPLIEDTOTHESTRIKEPRICE 1
#define ENUM_STRIKE_CURRENCY_INDICATOR_NO_VALUE 255

/*
 * Tax Code Values
 */ 
#define ENUM_TAX_CODE_NOTELIGIBLETO_PEA_THESTOCKHASNEVERBEENA_MONORYSTOCK 0
#define ENUM_TAX_CODE_ELIGIBLETO_PEA 3
#define ENUM_TAX_CODE_NOTPROVIDED 9
#define ENUM_TAX_CODE_NO_VALUE 255

/*
 * Technical Notification Type Values
 */ 
#define ENUM_TECHNICAL_NOTIFICATION_TYPE_INSTRUMENT_BOOK_RETRANSMISSION_END 1
#define ENUM_TECHNICAL_NOTIFICATION_TYPE_TRADE_RETRANSMISSION_START 10
#define ENUM_TECHNICAL_NOTIFICATION_TYPE_TRADE_RETRANSMISSION_END 11

/*
 * Template Id Values
 */ 
#define ENUM_TEMPLATE_ID_START_OF_DAY_MESSAGE 1101
#define ENUM_TEMPLATE_ID_END_OF_DAY_MESSAGE 1102
#define ENUM_TEMPLATE_ID_HEALTH_STATUS_MESSAGE 1103
#define ENUM_TEMPLATE_ID_TECHNICAL_NOTIFICATION_MESSAGE 1106
#define ENUM_TEMPLATE_ID_MARKET_UPDATE_MESSAGE 1001
#define ENUM_TEMPLATE_ID_ORDER_UPDATE_MESSAGE 1002
#define ENUM_TEMPLATE_ID_PRICE_UPDATE_MESSAGE 1003
#define ENUM_TEMPLATE_ID_FULL_TRADE_INFORMATION_MESSAGE 1004
#define ENUM_TEMPLATE_ID_MARKET_STATUS_CHANGE_MESSAGE 1005
#define ENUM_TEMPLATE_ID_TIMETABLE_MESSAGE 1006
#define ENUM_TEMPLATE_ID_STANDING_DATA_MESSAGE 1007
#define ENUM_TEMPLATE_ID_REAL_TIME_INDEX_MESSAGE 1008
#define ENUM_TEMPLATE_ID_STATISTICS_MESSAGE 1009
#define ENUM_TEMPLATE_ID_INDEX_SUMMARY_MESSAGE 1011
#define ENUM_TEMPLATE_ID_STRATEGY_STANDING_DATA_MESSAGE 1012
#define ENUM_TEMPLATE_ID_CONTRACT_STANDING_DATA_MESSAGE 1013
#define ENUM_TEMPLATE_ID_OUTRIGHT_STANDING_DATA_MESSAGE 1014
#define ENUM_TEMPLATE_ID_LIS_PACKAGE_STRUCTURE_MESSAGE 1016
#define ENUM_TEMPLATE_ID_APA_QUOTES_MESSAGE 1026
#define ENUM_TEMPLATE_ID_APA_STANDING_DATA_MESSAGE 1027
#define ENUM_TEMPLATE_ID_APA_FULL_TRADE_INFORMATION_MESSAGE 1028
#define ENUM_TEMPLATE_ID_START_OF_SNAPSHOT_MESSAGE 2101
#define ENUM_TEMPLATE_ID_END_OF_SNAPSHOT_MESSAGE 2102

/*
 * Trade Type Values
 */ 
#define ENUM_TRADE_TYPE_CONVENTIONAL_TRADE 1
#define ENUM_TRADE_TYPE_LARGEIN_SCALE_LI_S_TRADE 2
#define ENUM_TRADE_TYPE_BASIS_TRADE 3
#define ENUM_TRADE_TYPE_LARGEIN_SCALE_LI_S_PACKAGE_TRADE 4
#define ENUM_TRADE_TYPE_GUARANTEED_CROSS_TRADE 5
#define ENUM_TRADE_TYPE_AGAINST_ACTUAL_TRADE 6
#define ENUM_TRADE_TYPE_ASSET_ALLOCATION_TRADE 7
#define ENUM_TRADE_TYPE_EXCHANGEFOR_SWAP_TRADE 9
#define ENUM_TRADE_TYPE_EXCHANGEFOR_PHYSICAL_TRADE_CASH_LEG 10
#define ENUM_TRADE_TYPE_STRATEGY_LEG_CONVENTIONAL_TRADE 11
#define ENUM_TRADE_TYPE_STRATEGY_LEG_LARGEIN_SCALE_LI_S_TRADE 12
#define ENUM_TRADE_TYPE_STRATEGY_LEG_BASIS_TRADE 13
#define ENUM_TRADE_TYPE_STRATEGY_LEG_GUARANTEED_CROSS_TRADE 14
#define ENUM_TRADE_TYPE_STRATEGY_LEG_AGAINST_ACTUAL_TRADE 15
#define ENUM_TRADE_TYPE_STRATEGY_LEG_ASSET_ALLOCATION_TRADE 16
#define ENUM_TRADE_TYPE_STRATEGY_LEG_EXCHANGE_FOR_SWAP_TRADE 18
#define ENUM_TRADE_TYPE_STRATEGY_LEG_EXCHANGE_FOR_PHYSICAL_TRADE 19
#define ENUM_TRADE_TYPE_BO_B_TRADE 20
#define ENUM_TRADE_TYPE_ATOM_X_TRADE 22
#define ENUM_TRADE_TYPE_TRADE_CANCELLATION 24
#define ENUM_TRADE_TYPE_OUTOF_MARKET_TRADE 25
#define ENUM_TRADE_TYPE_DELTA_NEUTRAL_TRADE_UNDERLYING_CASH_LEG 26
#define ENUM_TRADE_TYPE_MARKET_VWAP_OPERATION_TRADE 27
#define ENUM_TRADE_TYPE_EURONEXT_FUND_SERVICE_TRADE 28
#define ENUM_TRADE_TYPE_SECONDARY_LISTING_TRADE 29
#define ENUM_TRADE_TYPE_REQUESTFOR_CROSS_TRADE 30
#define ENUM_TRADE_TYPE_REQUESTFORCROSSSTRATEGY_LEG_TRADE 31
#define ENUM_TRADE_TYPE_TRADE_PUBLICATION 32
#define ENUM_TRADE_TYPE_DARK_TRADE 33
#define ENUM_TRADE_TYPE_DELTA_NEUTRAL_TRADE_UNDERLYING_FUTURE_LEG 34
#define ENUM_TRADE_TYPE_TOTAL_TRADED_VOLUME 36
#define ENUM_TRADE_TYPE_ETFMTFNAV_TRADEPRICEINBP 37
#define ENUM_TRADE_TYPE_ETFMTFNAV_DARK_TRADEPRICEINBP 38
#define ENUM_TRADE_TYPE_GUARANTEED_CROSS_NEGOTIATEDDEAL_NLIQ 39
#define ENUM_TRADE_TYPE_GUARANTEED_CROSS_NEGOTIATEDDEAL_OILQ 40
#define ENUM_TRADE_TYPE_LARGEIN_SCALE_TRADE 41
#define ENUM_TRADE_TYPE_LARGEIN_SCALE_TRADEINBASISPOINTS 42
#define ENUM_TRADE_TYPE_LARGEIN_SCALE_PACKAGE_TRADEINBASISPOINTS 43
#define ENUM_TRADE_TYPE_STRATEGY_LEG_LARGEIN_SCALE_TRADEINBASISPOINTS 44
#define ENUM_TRADE_TYPE_TRADE_REVERSAL 45
#define ENUM_TRADE_TYPE_CONVENTIONAL_TRADE_PROVISIONALPRICE 100
#define ENUM_TRADE_TYPE_LARGEIN_SCALE_LI_S_TRADE_PROVISIONALPRICE 101
#define ENUM_TRADE_TYPE_LARGEIN_SCALE_LI_S_PACKAGE_TRADE_PROVISIONALPRICE 102

/*
 * Trading Currency Indicator Values
 */ 
#define ENUM_TRADING_CURRENCY_INDICATOR_CHANGERATENOTAPPLIEDTOTHETRADEDPRICE 0
#define ENUM_TRADING_CURRENCY_INDICATOR_CHANGERATEAPPLIEDTOTHETRADEDPRICE 1
#define ENUM_TRADING_CURRENCY_INDICATOR_NO_VALUE 255

/*
 * Trading Period Values
 */ 
#define ENUM_TRADING_PERIOD_OPENING 1
#define ENUM_TRADING_PERIOD_STANDARD 2
#define ENUM_TRADING_PERIOD_CLOSING 3
#define ENUM_TRADING_PERIOD_NO_VALUE 255

/*
 * Trading Policy Values
 */ 
#define ENUM_TRADING_POLICY_PRICE_EXPLICIT_TIME 1
#define ENUM_TRADING_POLICY_PRICE_PRO_RATA 2
#define ENUM_TRADING_POLICY_NO_VALUE 255

/*
 * Trading Side Values
 */ 
#define ENUM_TRADING_SIDE_BID_ONLY 1
#define ENUM_TRADING_SIDE_OFFER_ONLY 2
#define ENUM_TRADING_SIDE_PAKO 3
#define ENUM_TRADING_SIDE_BOTH_SIDES 4
#define ENUM_TRADING_SIDE_NO_VALUE 255

/*
 * Transaction Type Values
 */ 
#define ENUM_TRANSACTION_TYPE_PLAIN_VANILLA_TRADE 1
#define ENUM_TRANSACTION_TYPE_DARK_TRADE 2
#define ENUM_TRANSACTION_TYPE_BENCHMARK_TRADE 3
#define ENUM_TRANSACTION_TYPE_TECHNICAL_TRADE 4
#define ENUM_TRANSACTION_TYPE_GIVEUP_GIVEIN_TRADE 5
#define ENUM_TRANSACTION_TYPE_EX_CUMDIVIDEND_TRADE 6
#define ENUM_TRANSACTION_TYPE_TRADE_WITH_CONDITION 7
#define ENUM_TRANSACTION_TYPE_SUMMARY_REPORT 15
#define ENUM_TRANSACTION_TYPE_NO_VALUE 255

/*
 * Transparency Indicator Values
 */ 
#define ENUM_TRANSPARENCY_INDICATOR_LIT_REGULAR_TRADE 0
#define ENUM_TRANSPARENCY_INDICATOR_DARK_TRADEAND_IMMEDIATE_PUBLICATION 1
#define ENUM_TRANSPARENCY_INDICATOR_DARK_TRADEAND_DEFERRED_PUBLICATION 2
#define ENUM_TRANSPARENCY_INDICATOR_NO_VALUE 255

/*
 * Type Of Market Admission Values
 */ 
#define ENUM_TYPE_OF_MARKET_ADMISSION_INSTRUMENTSTRADEDONTHEPRIMARYMARKET 'A'
#define ENUM_TYPE_OF_MARKET_ADMISSION_INSTRUMENTSTRADEDONTHESECONDARYMARKET 'B'
#define ENUM_TYPE_OF_MARKET_ADMISSION_INSTRUMENTSTRADEDONTHE_NEW_MARKET 'C'
#define ENUM_TYPE_OF_MARKET_ADMISSION_NONREGULATEDMARKETINSTRUMENTSTRADEDONTHEFREEMARKET 'D'
#define ENUM_TYPE_OF_MARKET_ADMISSION_NONREGULATEDMARKET_ALTERNEXT 'E'
#define ENUM_TYPE_OF_MARKET_ADMISSION_NONLISTED 'F'
#define ENUM_TYPE_OF_MARKET_ADMISSION_REGULATED_MARKET_NONEQUITIES 'G'
#define ENUM_TYPE_OF_MARKET_ADMISSION_REGULATED_MARKET_EQUITIES_SEGMENT_A 'H'
#define ENUM_TYPE_OF_MARKET_ADMISSION_REGULATED_MARKET_EQUITIES_SEGMENT_B 'I'
#define ENUM_TYPE_OF_MARKET_ADMISSION_REGULATED_MARKET_EQUITIES_SEGMENT_C 'J'
#define ENUM_TYPE_OF_MARKET_ADMISSION_REGULATED_MARKET_ALLSECURITIES_SPECIAL_SEGMENT 'K'
#define ENUM_TYPE_OF_MARKET_ADMISSION_REGULATED_MARKET_EQUITIES_OTHERINSTRUMENTS 'L'
#define ENUM_TYPE_OF_MARKET_ADMISSION_OPCVMSICOM_INONLISTED_FRENCH_INVESTMENT_FUNDS 'S'
#define ENUM_TYPE_OF_MARKET_ADMISSION_OFF_MARKET '6'
#define ENUM_TYPE_OF_MARKET_ADMISSION_GOLD_CURRENCIESAND_INDICES '7'
#define ENUM_TYPE_OF_MARKET_ADMISSION_FOREIGN '9'
#define ENUM_TYPE_OF_MARKET_ADMISSION_NO_VALUE '0'

/*
 * Underlying Subtype Values
 */ 
#define ENUM_UNDERLYING_SUBTYPE_BASKET 0
#define ENUM_UNDERLYING_SUBTYPE_DIVIDEND 1
#define ENUM_UNDERLYING_SUBTYPE_ETF 2
#define ENUM_UNDERLYING_SUBTYPE_SHARE 3
#define ENUM_UNDERLYING_SUBTYPE_DIVIDEND_INDEX 4
#define ENUM_UNDERLYING_SUBTYPE_EQUITY_INDEX 5
#define ENUM_UNDERLYING_SUBTYPE_TRF_INDEX 6
#define ENUM_UNDERLYING_SUBTYPE_VOLATILITY_INDEX 7
#define ENUM_UNDERLYING_SUBTYPE_FUTURE_ON_COMMODITIES 8
#define ENUM_UNDERLYING_SUBTYPE_FX_CROSS_RATES 9
#define ENUM_UNDERLYING_SUBTYPE_FX_EMERGING_MARKETS 10
#define ENUM_UNDERLYING_SUBTYPE_FX_MAJORS 11
#define ENUM_UNDERLYING_SUBTYPE_AGRICULTURAL 12
#define ENUM_UNDERLYING_SUBTYPE_ENVIRONMENTAL 13
#define ENUM_UNDERLYING_SUBTYPE_FREIGHT 14
#define ENUM_UNDERLYING_SUBTYPE_FERTILIZER 15
#define ENUM_UNDERLYING_SUBTYPE_INDUSTRIALPRODUCTS 16
#define ENUM_UNDERLYING_SUBTYPE_INFLATION 17
#define ENUM_UNDERLYING_SUBTYPE_MULTI_COMMODITY_EXOTIC 18
#define ENUM_UNDERLYING_SUBTYPE_METALS 19
#define ENUM_UNDERLYING_SUBTYPE_ENERGY 20
#define ENUM_UNDERLYING_SUBTYPE_OFFICIALECONOMICSTATISTICS 21
#define ENUM_UNDERLYING_SUBTYPE_OTHER_C10 22
#define ENUM_UNDERLYING_SUBTYPE_OTHER 23
#define ENUM_UNDERLYING_SUBTYPE_PAPER 24
#define ENUM_UNDERLYING_SUBTYPE_POLYPROPYLENE 25
#define ENUM_UNDERLYING_SUBTYPE_NO_VALUE 255

/*
 * Underlying Type Values
 */ 
#define ENUM_UNDERLYING_TYPE_COMMODITY 'C'
#define ENUM_UNDERLYING_TYPE_FUTURE 'F'
#define ENUM_UNDERLYING_TYPE_INDEX 'I'
#define ENUM_UNDERLYING_TYPE_STOCK 'S'
#define ENUM_UNDERLYING_TYPE_EXCHANGE_RATE 'X'

/*
 * Update Type Values
 */ 
#define ENUM_UPDATE_TYPE_BEST_BID 1
#define ENUM_UPDATE_TYPE_BEST_OFFER 2
#define ENUM_UPDATE_TYPE_NEW_BID 3
#define ENUM_UPDATE_TYPE_NEW_OFFER 4
#define ENUM_UPDATE_TYPE_UPDATED_BID 5
#define ENUM_UPDATE_TYPE_UPDATED_OFFER 6
#define ENUM_UPDATE_TYPE_TOTAL_TRADED_VOLUME 7
#define ENUM_UPDATE_TYPE_IMPLIED_BID 8
#define ENUM_UPDATE_TYPE_IMPLIED_OFFER 9
#define ENUM_UPDATE_TYPE_REQUESTFOR_QUOTE 10
#define ENUM_UPDATE_TYPE_REQUESTFOR_QUOTE_BID 11
#define ENUM_UPDATE_TYPE_REQUESTFOR_SIZE 12
#define ENUM_UPDATE_TYPE_REQUESTFOR_QUOTE_OFFER 13
#define ENUM_UPDATE_TYPE_HIGH_DYNAMIC_COLLAR 14
#define ENUM_UPDATE_TYPE_LOW_DYNAMIC_COLLAR 15
#define ENUM_UPDATE_TYPE_NEW_BID_RLP 16
#define ENUM_UPDATE_TYPE_NEW_OFFER_RLP 17
#define ENUM_UPDATE_TYPE_UPDATED_BID_RLP 18
#define ENUM_UPDATE_TYPE_UPDATED_OFFER_RLP 19
#define ENUM_UPDATE_TYPE_CONVENTIONAL_TRADE 24
#define ENUM_UPDATE_TYPE_REQUESTFOR_CROSS_RFC_QUEUED 25
#define ENUM_UPDATE_TYPE_REQUESTFOR_CROSS_RFC 26
#define ENUM_UPDATE_TYPE_LARGEIN_SCALE_LI_S_TRADE 27
#define ENUM_UPDATE_TYPE_BASIS_TRADE 28
#define ENUM_UPDATE_TYPE_LARGEIN_SCALE_LI_S_PACKAGE_TRADE 29
#define ENUM_UPDATE_TYPE_GUARANTEED_CROSS_TRADE 30
#define ENUM_UPDATE_TYPE_AGAINST_ACTUAL_TRADE 31
#define ENUM_UPDATE_TYPE_ASSET_ALLOCATION_TRADE 32
#define ENUM_UPDATE_TYPE_EXCHANGEFOR_SWAP_TRADE 34
#define ENUM_UPDATE_TYPE_DARK_TRADE 35
#define ENUM_UPDATE_TYPE_EXCHANGEFOR_PHYSICAL_TRADE_CASH_LEG 36
#define ENUM_UPDATE_TYPE_STRATEGY_LEG_CONVENTIONAL_TRADE 37
#define ENUM_UPDATE_TYPE_STRATEGY_LEG_LARGEIN_SCALE_LI_S_TRADE 38
#define ENUM_UPDATE_TYPE_STRATEGY_LEG_BASIS_TRADE 39
#define ENUM_UPDATE_TYPE_STRATEGY_LEG_GUARANTEED_CROSS_TRADE 40
#define ENUM_UPDATE_TYPE_STRATEGY_LEG_AGAINST_ACTUAL_TRADE 41
#define ENUM_UPDATE_TYPE_STRATEGY_LEG_ASSET_ALLOCATION_TRADE 42
#define ENUM_UPDATE_TYPE_STRATEGY_LEG_EXCHANGE_FOR_SWAP_TRADE 44
#define ENUM_UPDATE_TYPE_STRATEGY_LEG_EXCHANGE_FOR_PHYSICAL_TRADE 45
#define ENUM_UPDATE_TYPE_BO_B_TRADE 46
#define ENUM_UPDATE_TYPE_ATOM_X_TRADE 48
#define ENUM_UPDATE_TYPE_TRADE_CANCELLATION 50
#define ENUM_UPDATE_TYPE_OUTOF_MARKET_TRADE 51
#define ENUM_UPDATE_TYPE_DELTA_NEUTRAL_TRADE_UNDERLYING_CASH_LEG 52
#define ENUM_UPDATE_TYPE_DELTA_NEUTRAL_TRADE_UNDERLYING_FUTURE_LEG 53
#define ENUM_UPDATE_TYPE_EURONEXT_FUND_SERVICE_TRADE 54
#define ENUM_UPDATE_TYPE_SECONDARY_LISTING_TRADE 55
#define ENUM_UPDATE_TYPE_REQUESTFOR_CROSS_TRADE 56
#define ENUM_UPDATE_TYPE_REQUESTFOR_CROSS_STRATEGY_LEG_TRADE 57
#define ENUM_UPDATE_TYPE_NEW_BID_WITH_LIQUIDITY_PROVIDER 58
#define ENUM_UPDATE_TYPE_NEW_OFFER_WITH_LIQUIDITY_PROVIDER 59
#define ENUM_UPDATE_TYPE_UPDATED_BID_WITH_LIQUIDITY_PROVIDER 60
#define ENUM_UPDATE_TYPE_UPDATED_OFFER_WITH_LIQUIDITY_PROVIDER 61
#define ENUM_UPDATE_TYPE_LOW_STATIC_COLLAR 63
#define ENUM_UPDATE_TYPE_HIGH_STATIC_COLLAR 64
#define ENUM_UPDATE_TYPE_MARKET_VWAP_OPERATION_TRADE 65
#define ENUM_UPDATE_TYPE_REQUESTFOR_SIZE_BID 66
#define ENUM_UPDATE_TYPE_REQUESTFOR_SIZE_OFFER 67
#define ENUM_UPDATE_TYPE_LOW_LP_COLLAR 70
#define ENUM_UPDATE_TYPE_HIGH_LP_COLLAR 71
#define ENUM_UPDATE_TYPE_ETFMTFNAV_TRADEPRICEINBP 72
#define ENUM_UPDATE_TYPE_ETFMTFNAV_DARK_TRADEPRICEINBP 73
#define ENUM_UPDATE_TYPE_NEW_BIDON_WHOLESALE_RFC 74
#define ENUM_UPDATE_TYPE_NEW_OFFERON_WHOLESALE_RFC 75
#define ENUM_UPDATE_TYPE_UPDATED_BIDON_WHOLESALE_RFC 76
#define ENUM_UPDATE_TYPE_UPDATED_OFFERON_WHOLESALE_RFC 77
#define ENUM_UPDATE_TYPE_CLEAR_WHOLESALE_RFC 78
#define ENUM_UPDATE_TYPE_GUARANTEED_CROSS_NEGOTIATEDDEAL_NLIQ 79
#define ENUM_UPDATE_TYPE_GUARANTEED_CROSS_NEGOTIATEDDEAL_OILQ 80
#define ENUM_UPDATE_TYPE_LARGEIN_SCALE_TRADE 81
#define ENUM_UPDATE_TYPE_LARGEIN_SCALE_TRADEINBASISPOINTS 82
#define ENUM_UPDATE_TYPE_LARGEIN_SCALE_PACKAGE_TRADEINBASISPOINTS 83
#define ENUM_UPDATE_TYPE_STRATEGY_LEG_LARGEIN_SCALE_TRADEINBASISPOINTS 84
#define ENUM_UPDATE_TYPE_NEW_BID_RFQ_ANSWER 86
#define ENUM_UPDATE_TYPE_NEW_OFFER_RFQ_ANSWER 87
#define ENUM_UPDATE_TYPE_UPDATED_BID_RFQ_ANSWER 88
#define ENUM_UPDATE_TYPE_UPDATED_OFFER_RFQ_ANSWER 89
#define ENUM_UPDATE_TYPE_BID_EXECUTION_SUMMARY 90
#define ENUM_UPDATE_TYPE_AQS_EXPANSION_FACTOR 91
#define ENUM_UPDATE_TYPE_COLLARS_EXPANSION_FACTOR 92
#define ENUM_UPDATE_TYPE_COLLARS_ENABLED 93
#define ENUM_UPDATE_TYPE_COLLARS_DISABLED 94
#define ENUM_UPDATE_TYPE_DCRP_INTER_MONTH_SPREAD 95
#define ENUM_UPDATE_TYPE_FSP_REFERENCE_PRICE 96
#define ENUM_UPDATE_TYPE_OFFER_EXECUTION_SUMMARY 97
#define ENUM_UPDATE_TYPE_FSP_TRIGGERED 98
#define ENUM_UPDATE_TYPE_MID_POINT_BBO 99
#define ENUM_UPDATE_TYPE_CONVENTIONAL_TRADE_PROVISIONALPRICE 100
#define ENUM_UPDATE_TYPE_CLEAR_BOOK 254


/*******************************************************************************
 * Structs
 *******************************************************************************/

#pragma pack(push, 1)

/*
 * Structure: End Of Snapshot Message
 */ 
typedef struct {
    uint64_t LastMdSeqNum;
    uint64_t SnapshotTime;
} EndOfSnapshotMessageT;

/*
 * Structure: Start Of Snapshot Message
 */ 
typedef struct {
    uint64_t LastMdSeqNum;
    uint64_t SnapshotTime;
} StartOfSnapshotMessageT;

/*
 * Structure: Apa Full Trade Information Message
 */ 
typedef struct {
    uint64_t MdSeqNum;
    uint8_t RebroadcastIndicator;
    uint8_t Emm;
    uint64_t EventTime;
    char TradingDateTime[27];
    char PublicationDateTime[27];
    uint8_t TradeType;
    char MifidInstrumentIdType[4];
    char MifidInstrumentId[12];
    char MiFidTransactionId[52];
    char MifidPrice[20];
    char MifidQuantity[20];
    char MifidPriceNotation[4];
    char MifidCurrency[3];
    char MiFidQtyinMsrmtUnitNotation[25];
    char MifidQuantityMeasurementUnit[20];
    char MiFidNotionalAmount[20];
    char NotionalCurrency[3];
    char MiFidClearingFlag[5];
    uint8_t EfficientMmtMarketMechanism;
    char EfficientMmtTradingMode;
    char EfficientMmtTransactionCategory;
    char EfficientMmtNegotiationIndicator;
    char EfficientMmtAgencyCrossTradeIndicator;
    char EfficientMmtModificationIndicator;
    char EfficientMmtBenchmarkIndicator;
    char EfficientMmtSpecialDividendIndicator;
    char EfficientMmtOffBookAutomatedIndicator;
    char EfficientMmtContributiontoPrice;
    char EfficientMmtAlgorithmicIndicator;
    char EfficientMmtPublicationMode;
    char EfficientMmtPostTradeDeferral;
    char EfficientMmtDuplicativeIndicator;
    char TradeReference[30];
    uint64_t OriginalReportTimestamp;
    uint32_t PriceMultiplier;
    uint8_t PriceMultiplierDecimals;
    char Venue[11];
    char MiFidEmissionAllowanceType[4];
} ApaFullTradeInformationMessageT;

/*
 * Structure: Apa Standing Data Message
 */ 
typedef struct {
    uint64_t MdSeqNum;
    uint8_t RebroadcastIndicator;
    char MifidInstrumentIdType[4];
    char MifidInstrumentId[12];
    char FullInstrumentName[102];
    char Cfi[6];
    char NotionalCurrency[3];
    char SecondNotionalCurrency[3];
    uint32_t PriceMultiplier;
    uint8_t PriceMultiplierDecimals;
    char UnderlyingIsinCode[12];
    char UnderlyingIndexName[25];
    char UnderlyingIndexTerm[8];
    uint8_t OptionType;
    int64_t StrikePrice;
    uint8_t StrikePriceDecimals;
    uint8_t ExerStyle;
    char MaturityDate[8];
    char ExpiryDate[8];
    char SettlementMethod[1];
} ApaStandingDataMessageT;

/*
 * Structure: Apa Quotes Message
 */ 
typedef struct {
    uint64_t MdSeqNum;
    uint8_t RebroadcastIndicator;
    char MifidInstrumentIdType[4];
    char MifidInstrumentId[12];
    char Mic[4];
    char Currency[3];
    char LeiCode[20];
    uint64_t EventTime;
    uint8_t QuoteUpdateType;
    char MifidPrice[20];
    char MifidQuantity[20];
} ApaQuotesMessageT;

/*
 * Structure: Package Components Group
 */ 
typedef struct {
    uint32_t LegSymbolIndex;
    uint32_t LegRatio;
} PackageComponentsGroupT;

/*
 * Structure: Group Size Encoding
 */ 
typedef struct {
    uint8_t BlockLengthUint8;
    uint8_t NumInGroup;
} GroupSizeEncodingT;

/*
 * Structure: Package Components Groups
 */ 
typedef struct {
    GroupSizeEncodingT GroupSizeEncoding;
} PackageComponentsGroupsT;

/*
 * Structure: Lis Package Structure Message
 */ 
typedef struct {
    uint64_t MdSeqNum;
    uint8_t RebroadcastIndicator;
    uint8_t Emm;
    uint64_t EventTime;
    uint32_t ContractSymbolIndex;
    char MifidExecutionId[52];
    char StrategyCode;
} LisPackageStructureMessageT;

/*
 * Structure: Outright Rep Group
 */ 
typedef struct {
    uint8_t Emm;
} OutrightRepGroupT;

/*
 * Structure: Outright Rep Groups
 */ 
typedef struct {
    GroupSizeEncodingT GroupSizeEncoding;
} OutrightRepGroupsT;

/*
 * Structure: Outright Standing Data Message
 */ 
typedef struct {
    uint64_t MdSeqNum;
    uint8_t RebroadcastIndicator;
    uint32_t SymbolIndex;
    uint32_t ContractSymbolIndex;
    uint16_t InstrumentEventDate;
    char IsinCode[12];
    char Cfi[6];
    char MaturityDate[8];
    uint64_t LotSize;
    int64_t StrikePrice;
    uint16_t LastTradingDate;
    uint16_t DaysToExpiry;
    char DerivativesInstrumentTradingCode[18];
    uint8_t DerivativesInstrumentType;
    uint8_t ExpiryCycleType;
    char UnderlyingDerivativesInstrumentTradingCode[18];
    uint32_t UnderlyingSymbolIndex;
} OutrightStandingDataMessageT;

/*
 * Bitfield: Strategy Authorized
 */ 
typedef struct {
    uint64_t
    Reserved16 : 16,
    PutStraddleVersusSellACallOrAPut : 1,
    PutSpreadVersusSellACall : 1,
    CallSpreadVersusSellAPut : 1,
    IronCondor : 1,
    IronCondorVersusUnderlying : 1,
    BuyWrite : 1,
    CondorVersusUnderlying : 1,
    StraddleVersusUnderlying : 1,
    Synthetic : 1,
    DiagonalStraddleCalendarSpreadVersusUnderlying : 1,
    PutSpreadVersusCallVersusUnderlying : 1,
    StraddleCalendarSpreadVersusUnderlying : 1,
    ExchangeForPhysical : 1,
    StrangleVersusUnderlying : 1,
    ComboVersusUnderlying : 1,
    IronButterflyVersusUnderlying : 1,
    TwoByOneCallOrPutRatioSpreadVersusUnderlying : 1,
    GutsVersusUnderlying : 1,
    CallPutDiagonalCalendarSpreadVersusUnderlying : 1,
    CallOrPutCalendarSpreadVersusUnderlying : 1,
    CallOrPutSpreadVersusUnderlying : 1,
    CallSpreadVersusPutVersusUnderlying : 1,
    ButterflyVersusUnderlying : 1,
    LadderVersusUnderlying : 1,
    ReducedTickSpread : 1,
    Bundle : 1,
    Box : 1,
    Condor : 1,
    VolatilityTrade : 1,
    Straddle : 1,
    ConversionReversal : 1,
    SimpleInterCommoditySpread : 1,
    DiagonalStraddleCalendarSpread : 1,
    Pack : 1,
    StraddleCalendarSpread : 1,
    Strip : 1,
    Ladder : 1,
    Strangle : 1,
    Combo : 1,
    IronButterfly : 1,
    TwoByOneRatioSpread : 1,
    Guts : 1,
    DiagonalCalendarSpread : 1,
    CalendarSpread : 1,
    Spread : 1,
    CallOrPutCabinet : 1,
    Butterfly : 1,
    JellyRoll : 1;
} StrategyAuthorizedT;

/*
 * Structure: Contract Em M Properties Group
 */ 
typedef struct {
    uint8_t Emm;
    uint16_t TickSizeIndexId;
    uint16_t PatternId;
    uint64_t LotSize;
    StrategyAuthorizedT StrategyAuthorized;
    uint8_t DynamicCollarLogic;
    uint8_t CollarMaxUnhaltNb;
    uint32_t CollarUnhaltDelay;
} ContractEmMPropertiesGroupT;

/*
 * Structure: Contract Em M Properties Groups
 */ 
typedef struct {
    GroupSizeEncodingT GroupSizeEncoding;
} ContractEmMPropertiesGroupsT;

/*
 * Bitfield: Mm Protections
 */ 
typedef struct {
    uint8_t
    Reserved6 : 6,
    Volume : 1,
    Delta : 1;
} MmProtectionsT;

/*
 * Bitfield: Order Type Rules
 */ 
typedef struct {
    uint16_t
    Reserved10 : 10,
    TradeAtSettlement : 1,
    MarketOnOpenMoo : 1,
    StopLimit : 1,
    StopStopLoss : 1,
    Limit : 1,
    Market : 1;
} OrderTypeRulesT;

/*
 * Structure: Contract Standing Data Message
 */ 
typedef struct {
    uint64_t MdSeqNum;
    uint8_t RebroadcastIndicator;
    uint32_t SymbolIndex;
    uint8_t OptiqSegment;
    uint16_t PartitionId;
    uint16_t ContractEventDate;
    char ExchangeCode;
    uint8_t ExerStyle;
    char ContractName[60];
    char ContractType;
    char UnderlyingType;
    uint8_t PriceDecimals;
    uint8_t QuantityDecimals;
    uint8_t AmountDecimals;
    uint8_t RatioDecimals;
    char MainDepositary[5];
    char Mic[4];
    char CountryOfExchange[3];
    char ProductCode[4];
    char UnderlyingMic[4];
    char UnderlyingIsinCode[12];
    uint32_t UnderlyingExpiry;
    OrderTypeRulesT OrderTypeRules;
    char SettlementMethod[1];
    char TradingCurrency[3];
    uint8_t StrikePriceDecimalsRatio;
    MmProtectionsT MmProtections;
    uint8_t ContractTradingType;
    uint8_t InstUnitExp;
    uint8_t UnderlyingSubtype;
    char MotherStockIsin[12];
    uint64_t SettlementTickSize;
    uint64_t EdspTickSize;
    uint32_t UnderlyingSymbolIndex;
    uint8_t TradingPolicy;
    uint16_t ReferenceSpreadTableId;
    uint8_t DerivativesMarketModel;
    uint64_t TradingUnit;
    uint8_t ReferencePriceOriginInOpeningCall;
    uint8_t ReferencePriceOriginInContinuous;
    uint8_t ReferencePriceOriginInTradingInterruption;
    uint8_t CollarExpansionFactor;
    uint8_t MifidiiLiquidFlag;
    uint8_t PricingAlgorithm;
} ContractStandingDataMessageT;

/*
 * Structure: Strategy Standing Datarep 1 Group
 */ 
typedef struct {
    uint32_t LegSymbolIndex;
    int64_t LegPrice;
    uint32_t LegRatio;
    char LegBuySell;
} StrategyStandingDatarep1GroupT;

/*
 * Structure: Strategy Standing Datarep 1 Groups
 */ 
typedef struct {
    GroupSizeEncodingT GroupSizeEncoding;
} StrategyStandingDatarep1GroupsT;

/*
 * Structure: Strategy Standing Data Message
 */ 
typedef struct {
    uint64_t MdSeqNum;
    uint8_t RebroadcastIndicator;
    uint8_t Emm;
    uint32_t SymbolIndex;
    char DerivativesInstrumentTradingCode[18];
    char ExchangeCode;
    char MaturityDate[8];
    char StrategyCode;
    uint32_t ContractSymbolIndex;
    char Cfi[6];
} StrategyStandingDataMessageT;

/*
 * Structure: Index Summary Message
 */ 
typedef struct {
    uint64_t MdSeqNum;
    uint8_t RebroadcastIndicator;
    uint8_t Emm;
    uint64_t EventTime;
    uint32_t SymbolIndex;
    int64_t OpeningLevel;
    uint64_t OpeningTime;
    int64_t ConfirmedReferenceLevel;
    uint64_t ConfirmedReferenceTime;
    int64_t ClosingReferenceLevel;
    uint64_t ClosingReferenceTime;
    int64_t PrctVarfromPrevClose;
    int64_t HighLevel;
    uint64_t HighTime;
    int64_t LowLevel;
    uint64_t LowTime;
    int64_t LiquidationLevel;
    uint64_t LiquidationTime;
} IndexSummaryMessageT;

/*
 * Structure: New Stats Group
 */ 
typedef struct {
    uint8_t StatsUpdateType;
    int64_t StatsUpdateValue;
} NewStatsGroupT;

/*
 * Structure: New Stats Groups
 */ 
typedef struct {
    GroupSizeEncodingT GroupSizeEncoding;
} NewStatsGroupsT;

/*
 * Structure: Statistics Message
 */ 
typedef struct {
    uint64_t MdSeqNum;
    uint8_t RebroadcastIndicator;
    uint32_t SymbolIndex;
} StatisticsMessageT;

/*
 * Structure: Real Time Index Message
 */ 
typedef struct {
    uint64_t MdSeqNum;
    uint8_t RebroadcastIndicator;
    uint8_t Emm;
    uint64_t EventTime;
    uint32_t SymbolIndex;
    int64_t IndexLevel;
    uint64_t PctgOfCapitalization;
    int64_t PrctVarfromPrevClose;
    uint16_t NumTradedInstruments;
    uint8_t IndexLevelType;
    uint8_t IndexPriceCode;
} RealTimeIndexMessageT;

/*
 * Structure: Em M Pattern Rep Group
 */ 
typedef struct {
    uint8_t Emm;
    uint16_t PatternId;
    uint16_t TickSizeIndexId;
    uint8_t MarketModel;
    uint64_t LotSize;
    uint8_t InstUnitExp;
} EmMPatternRepGroupT;

/*
 * Structure: Em M Pattern Rep Groups
 */ 
typedef struct {
    GroupSizeEncodingT GroupSizeEncoding;
} EmMPatternRepGroupsT;

/*
 * Structure: Standing Data Message
 */ 
typedef struct {
    uint64_t MdSeqNum;
    uint8_t RebroadcastIndicator;
    uint32_t SymbolIndex;
    uint8_t OptiqSegment;
    uint16_t PartitionId;
    char FullInstrumentName[102];
    char InstrumentName[18];
    char InstrumentTradingCode[15];
    char InstrumentGroupCode[2];
    char IsinCode[12];
    uint8_t PriceDecimals;
    uint8_t QuantityDecimals;
    uint8_t AmountDecimals;
    uint8_t RatioDecimals;
    char Cfi[6];
    uint16_t InstrumentEventDate;
    int64_t StrikePrice;
    uint8_t DarkEligibility;
    uint64_t DarkLisThreshold;
    uint32_t DarkMinQuantity;
    uint16_t DateOfLastTrade;
    char DepositaryList[20];
    char MainDepositary[5];
    uint16_t FirstSettlementDate;
    uint8_t GuaranteeIndicator;
    char Icb[16];
    char IssuingCountry[3];
    int64_t LastAdjustedClosingPrice;
    uint64_t LotSize;
    char MaturityDate[8];
    uint8_t MaximumDecimalsInQuantity;
    char Mic[4];
    char MicList[20];
    char CountryOfExchange[3];
    char Mnemonic[5];
    char UnderlyingMic[4];
    char UnderlyingIsinCode[12];
    char TradingCurrency[3];
    uint32_t CurrencyCoefficient;
    uint8_t TradingCurrencyIndicator;
    uint8_t StrikeCurrencyIndicator;
    uint64_t NumberInstrumentCirculating;
    uint64_t ParValue;
    char QuantityNotation[3];
    uint8_t InstUnitExp;
    char SettlementDelay[2];
    char StrikeCurrency[3];
    uint8_t TaxCode;
    char TypeOfCorporateEvent[2];
    char TypeOfMarketAdmission;
    uint8_t RepoIndicator;
    int64_t IssuePrice;
    char NominalCurrency[3];
    uint8_t IssuePriceDecimals;
    uint8_t StrikePriceDecimals;
    uint8_t LiquidInstrumentIndicator;
    char MarketOfReferenceMic[4];
    char IcbCode[8];
    uint64_t ThresholdLisPostTrade60Mn;
    uint64_t ThresholdLisPostTrade120Mn;
    uint64_t ThresholdLisPostTradeEod;
} StandingDataMessageT;

/*
 * Bitfield: Phase Qualifier
 */ 
typedef struct {
    uint16_t
    Reserved10 : 10,
    WholesaleAllowed : 1,
    Suspended : 1,
    RandomUncrossing : 1,
    TradingAtLast : 1,
    CallBboOnly : 1,
    NoQualifier : 1;
} PhaseQualifierT;

/*
 * Structure: Timetables Group
 */ 
typedef struct {
    uint64_t PhaseTime;
    uint8_t PhaseId;
    PhaseQualifierT PhaseQualifier;
    uint8_t TradingPeriod;
    uint8_t OrderEntryQualifier;
    uint8_t Session;
    uint8_t ScheduledEvent;
} TimetablesGroupT;

/*
 * Structure: Timetables Groups
 */ 
typedef struct {
    GroupSizeEncodingT GroupSizeEncoding;
} TimetablesGroupsT;

/*
 * Structure: Timetable Message
 */ 
typedef struct {
    uint64_t MdSeqNum;
    uint8_t RebroadcastIndicator;
    uint8_t Emm;
    uint16_t PatternId;
    uint32_t SymbolIndex;
} TimetableMessageT;

/*
 * Structure: Market States Group
 */ 
typedef struct {
    uint8_t ChangeType;
    uint32_t SymbolIndex;
    uint64_t EventTime;
    uint8_t BookState;
    uint8_t StatusReason;
    PhaseQualifierT PhaseQualifier;
    uint8_t TradingPeriod;
    uint8_t TradingSide;
    uint8_t PriceLimits;
    uint8_t QuoteSpreadMultiplier;
    uint8_t OrderEntryQualifier;
    uint8_t Session;
    uint8_t ScheduledEvent;
    uint64_t ScheduledEventTime;
    uint8_t InstrumentState;
} MarketStatesGroupT;

/*
 * Structure: Market States Groups
 */ 
typedef struct {
    GroupSizeEncodingT GroupSizeEncoding;
} MarketStatesGroupsT;

/*
 * Structure: Market Status Change Message
 */ 
typedef struct {
    uint64_t MdSeqNum;
    uint8_t RebroadcastIndicator;
    uint8_t Emm;
} MarketStatusChangeMessageT;

/*
 * Structure: Not Used Group 1 Groups
 */ 
typedef struct {
    GroupSizeEncodingT GroupSizeEncoding;
} NotUsedGroup1GroupsT;

/*
 * Bitfield: Trade Qualifier
 */ 
typedef struct {
    uint8_t
    DeferredPublication : 1,
    NavTradeExpressedInPriceCurrency : 1,
    NavTradeExpressedInBps : 1,
    TradeCreationByMarketOperations : 1,
    AggressiveOrder : 1,
    PassiveOrder : 1,
    FirstTradePrice : 1,
    UncrossingTrade : 1;
} TradeQualifierT;

/*
 * Structure: Full Trade Information Message
 */ 
typedef struct {
    uint64_t MdSeqNum;
    uint8_t RebroadcastIndicator;
    uint8_t Emm;
    uint64_t EventTime;
    uint32_t SymbolIndex;
    char TradingDateTime[27];
    char PublicationDateTime[27];
    uint8_t TradeType;
    char MifidInstrumentIdType[4];
    char MifidInstrumentId[12];
    char MifidExecutionId[52];
    char MifidPrice[20];
    char MifidQuantity[20];
    char MifidPriceNotation[4];
    char MifidCurrency[3];
    char MiFidQtyinMsrmtUnitNotation[25];
    char MifidQuantityMeasurementUnit[20];
    char MiFidNotionalAmount[20];
    char NotionalCurrency[3];
    char MiFidClearingFlag[5];
    uint8_t MmtMarketMechanism;
    char MmtTradingMode;
    char MmtTransactionCategory[4];
    char MmtNegotiationIndicator[4];
    char MmtAgencyCrossTradeIndicator[4];
    char MmtModificationIndicator[4];
    char MmtBenchmarkIndicator[4];
    char MmtSpecialDividendIndicator[4];
    char MmtOffBookAutomatedIndicator;
    char MmtContributiontoPrice[4];
    char MmtAlgorithmicIndicator[4];
    char MmtPublicationMode[4];
    char MmtPostTradeDeferral[4];
    char MmtDuplicativeIndicator[4];
    TradeQualifierT TradeQualifier;
    uint8_t TransactionType;
    uint8_t EffectiveDateIndicator;
    char BlockTradeCode;
    char TradeReference[30];
    uint64_t OriginalReportTimestamp;
    uint8_t TransparencyIndicator;
    uint32_t CurrencyCoefficient;
    uint32_t PriceMultiplier;
    uint8_t PriceMultiplierDecimals;
    char Venue[11];
    uint32_t StartTimeVwap;
    uint32_t EndTimeVwap;
    char MiFidEmissionAllowanceType[4];
    char MarketOfReferenceMic[4];
    int64_t EvaluatedPrice;
    uint8_t MessagePriceNotation;
} FullTradeInformationMessageT;

/*
 * Structure: Prices Group
 */ 
typedef struct {
    uint8_t PriceType;
    uint32_t SymbolIndex;
    int64_t Price;
    uint64_t Quantity;
    uint64_t ImbalanceQty;
    uint8_t ImbalanceQtySide;
} PricesGroupT;

/*
 * Structure: Prices Groups
 */ 
typedef struct {
    GroupSizeEncodingT GroupSizeEncoding;
} PricesGroupsT;

/*
 * Structure: Price Update Message
 */ 
typedef struct {
    uint64_t MdSeqNum;
    uint8_t RebroadcastIndicator;
    uint8_t Emm;
    uint64_t EventTime;
} PriceUpdateMessageT;

/*
 * Structure: Orders Group
 */ 
typedef struct {
    uint32_t SymbolIndex;
    uint8_t ActionType;
    uint64_t OrderPriority;
    uint64_t PreviousPriority;
    uint8_t OrderType;
    int64_t OrderPx;
    uint8_t OrderSide;
    uint64_t OrderQuantity;
    int8_t PegOffset;
} OrdersGroupT;

/*
 * Structure: Orders Groups
 */ 
typedef struct {
    GroupSizeEncodingT GroupSizeEncoding;
} OrdersGroupsT;

/*
 * Structure: Order Update Message
 */ 
typedef struct {
    uint64_t MdSeqNum;
    uint8_t RebroadcastIndicator;
    uint8_t Emm;
    uint64_t EventTime;
} OrderUpdateMessageT;

/*
 * Structure: Updates Group
 */ 
typedef struct {
    uint8_t UpdateType;
    uint32_t SymbolIndex;
    uint16_t NumberOfOrders;
    int64_t Price;
    uint64_t Quantity;
} UpdatesGroupT;

/*
 * Structure: Updates Groups
 */ 
typedef struct {
    GroupSizeEncodingT GroupSizeEncoding;
} UpdatesGroupsT;

/*
 * Structure: Market Update Message
 */ 
typedef struct {
    uint64_t MdSeqNum;
    uint8_t RebroadcastIndicator;
    uint8_t Emm;
    uint64_t EventTime;
} MarketUpdateMessageT;

/*
 * Structure: Technical Notification Message
 */ 
typedef struct {
    uint64_t MdSeqNum;
    uint8_t TechnicalNotificationType;
    uint8_t RebroadcastIndicator;
    uint64_t RetransmissionStartTime;
    uint64_t RetransmissionEndTime;
    uint32_t SymbolIndex;
} TechnicalNotificationMessageT;

/*
 * Structure: Health Status Message
 */ 
typedef struct {
    uint64_t MdSeqNum;
    uint64_t EventTime;
} HealthStatusMessageT;

/*
 * Structure: End Of Day Message
 */ 
typedef struct {
    uint64_t MdSeqNum;
    uint16_t SessionTradingDay;
} EndOfDayMessageT;

/*
 * Structure: Start Of Day Message
 */ 
typedef struct {
    uint64_t MdSeqNum;
    uint16_t SessionTradingDay;
} StartOfDayMessageT;

/*
 * Structure: Message Header
 */ 
typedef struct {
    uint16_t BlockLengthUint16;
    uint16_t TemplateId;
    uint16_t SchemaId;
    uint16_t Version;
} MessageHeaderT;

/*
 * Structure: Message
 */ 
typedef struct {
    uint16_t Frame;
    MessageHeaderT MessageHeader;
} MessageT;

/*
 * Bitfield: Packet Flags
 */ 
typedef struct {
    uint16_t
    ReservedBits : 6,
    HasStatusMessage : 1,
    HasEndOfDaySnapshot : 1,
    HasStartOfDaySnapshot : 1,
    PsnHighWeight : 3,
    MdgRestartCount : 3,
    Compression : 1;
} PacketFlagsT;

/*
 * Structure: Market Data Packet Header
 */ 
typedef struct {
    uint64_t PacketTime;
    uint32_t PacketSequenceNumber;
    PacketFlagsT PacketFlags;
    uint16_t ChannelId;
} MarketDataPacketHeaderT;

/*
 * Structure: Packet
 */ 
typedef struct {
    MarketDataPacketHeaderT MarketDataPacketHeader;
} PacketT;

#pragma pack(pop)

/*******************************************************************************

Protocol:
   Organization: European New Exchange Technology
   Version: 3.0
   Date: Tuesday, September 3, 2019

Source:
   Generator: 1.0.0.0
   Compiler: 2.0
   License: MIT No Attribution License
   Authors: Omi Developers

This file was generated by the Open Markets Initiative (Omi).

Information relating to Omi:
https://github.com/Open-Markets-Initiative/Directory

*******************************************************************************/
