/*******************************************************************************
 * C Structs For Otc Markets Ats Headers 1.0 Binary Model
 *******************************************************************************/

/*******************************************************************************
 * Structs
 *******************************************************************************/

#pragma pack(push, 1)

/*
 * Structure: Message Header
 */ 
typedef struct {
    uint16_t MessageSize;
    uint8_t MessageType;
} MessageHeaderT;

/*
 * Structure: Message
 */ 
typedef struct {
    MessageHeaderT MessageHeader;
    char Payload[0];
} MessageT;

/*
 * Bitfield: Packet Flag
 */ 
typedef struct {
    uint8_t
    Test : 1,
    Replay : 1,
    ReservedPacketFlags : 4,
    SeqNumReset : 1,
    Heartbeat : 1;
} PacketFlagT;

/*
 * Structure: Packet Header
 */ 
typedef struct {
    uint16_t PacketSize;
    uint32_t SeqNum;
    PacketFlagT PacketFlag;
    uint8_t Messages;
    uint32_t PacketMilli;
} PacketHeaderT;

/*
 * Structure: Packet
 */ 
typedef struct {
    PacketHeaderT PacketHeader;
} PacketT;

#pragma pack(pop)

/*******************************************************************************

Protocol:
   Organization: Otc Markets
   Version: 1.0
   Date: Wednesday, December 11, 2019
   Specification: OTC Markets Multicast Data Feeds -v4.3.pdf

Source:
   Generator: 1.0.0.0
   Compiler: 2.0
   License: MIT No Attribution License
   Authors: Omi Developers

This file was generated by the Open Markets Initiative (Omi).

Information relating to Omi:
https://github.com/Open-Markets-Initiative/Directory

*******************************************************************************/
