/*******************************************************************************
 * C Structs For Lse Millennium Mitch UdpUnitHeader 1.0 Binary Model
 *******************************************************************************/

/*******************************************************************************
 * Structs
 *******************************************************************************/

#pragma pack(push, 1)

/*
 * Structure: Message Header
 */ 
typedef struct {
    uint8_t MessageLength;
    uint8_t MessageType;
} MessageHeaderT;

/*
 * Structure: Message
 */ 
typedef struct {
    MessageHeaderT MessageHeader;
    char Payload[0];
} MessageT;

/*
 * Structure: Unit Header
 */ 
typedef struct {
    uint16_t Length;
    uint8_t MessageCount;
    char MarketDataGroup[1];
    uint32_t SequenceNumber;
} UnitHeaderT;

/*
 * Structure: Packet
 */ 
typedef struct {
    UnitHeaderT UnitHeader;
} PacketT;

#pragma pack(pop)

/*******************************************************************************

Protocol:
   Organization: London Stock Exchange
   Version: 1.0
   Date: Monday, January 1, 2018
   Specification: mit303issue119.pdf

Source:
   Generator: 1.0.0.0
   Compiler: 2.0
   License: MIT No Attribution License
   Authors: Omi Developers

This file was generated by the Open Markets Initiative (Omi).

Information relating to Omi:
https://github.com/Open-Markets-Initiative/Directory

*******************************************************************************/
