/*******************************************************************************
 * C Structs For Iex Equities IexTp UdpHeader 1.0 Binary Model
 *******************************************************************************/

/*******************************************************************************
 * Structs
 *******************************************************************************/

#pragma pack(push, 1)

/*
 * Structure: Message Header
 */ 
typedef struct {
    uint16_t MessageLength;
    char MessageType[1];
} MessageHeaderT;

/*
 * Structure: Message
 */ 
typedef struct {
    MessageHeaderT MessageHeader;
} MessageT;

/*
 * Structure: Iex Tp Header
 */ 
typedef struct {
    uint8_t Version;
    char Reserved[1];
    uint16_t MessageProtocolId;
    uint32_t ChannelId;
    uint32_t SessionId;
    uint16_t PayloadLength;
    uint16_t MessageCount;
    uint64_t StreamOffset;
    uint64_t FirstMessageSequenceNumber;
    uint64_t SendTime;
} IexTpHeaderT;

/*
 * Structure: Packet
 */ 
typedef struct {
    IexTpHeaderT IexTpHeader;
} PacketT;

#pragma pack(pop)

/*******************************************************************************

Protocol:
   Organization: Investors Exchange
   Version: 1.0
   Date: Sunday, September 20, 2015
   Specification: IEX Transport Specification.pdf

Source:
   Generator: 1.0.0.0
   Compiler: 2.0
   License: MIT No Attribution License
   Authors: Omi Developers

This file was generated by the Open Markets Initiative (Omi).

Information relating to Omi:
https://github.com/Open-Markets-Initiative/Directory

*******************************************************************************/
