/*******************************************************************************
 * C Structs For Cme BrokerTec Sbe Ust 10.1 Binary Model
 *******************************************************************************/

/*******************************************************************************
 * Enum Values
 *******************************************************************************/

/*
 * Md Entry Type Values
 */ 
#define ENUM_MD_ENTRY_TYPE_BID '0'
#define ENUM_MD_ENTRY_TYPE_OFFER '1'
#define ENUM_MD_ENTRY_TYPE_TRADE '2'
#define ENUM_MD_ENTRY_TYPE_OPEN_PRICE '4'
#define ENUM_MD_ENTRY_TYPE_CLOSE_PRICE '5'
#define ENUM_MD_ENTRY_TYPE_HIGH_TRADE_PRICE '7'
#define ENUM_MD_ENTRY_TYPE_LOW_TRADE_PRICE '8'
#define ENUM_MD_ENTRY_TYPE_VWAP '9'
#define ENUM_MD_ENTRY_TYPE_IMPLIED_BID 'E'
#define ENUM_MD_ENTRY_TYPE_IMPLIED_OFFER 'F'
#define ENUM_MD_ENTRY_TYPE_BOOK_RESET 'J'

/*
 * Md Update Action Values
 */ 
#define ENUM_MD_UPDATE_ACTION_NEW 0
#define ENUM_MD_UPDATE_ACTION_UPDATE 1
#define ENUM_MD_UPDATE_ACTION_DELETE 2

/*
 * Template Id Values
 */ 
#define ENUM_TEMPLATE_ID_MD_INCREMENTAL_REFRESH_BTEC 405
#define ENUM_TEMPLATE_ID_ADMIN_HEARTBEAT 411


/*******************************************************************************
 * Structs
 *******************************************************************************/

#pragma pack(push, 1)

/*
 * Structure: Coupon Rate
 */ 
typedef struct {
    int32_t MantissaInt32;
    int8_t Exponent;
} CouponRateT;

/*
 * Structure: Md Entry Px
 */ 
typedef struct {
    int64_t MantissaInt64;
    int8_t Exponent;
} MdEntryPxT;

/*
 * Structure: M D Incremental Refresh Btec Group
 */ 
typedef struct {
    uint8_t MdUpdateAction;
    char MdEntryType;
    MdEntryPxT MdEntryPx;
    uint32_t MdEntrySize;
    uint8_t MdPriceLevel;
    uint32_t TradeVolume;
    char Symbol[20];
    uint16_t MaturityDate;
    char SecurityAltId[12];
    char SecurityAltIdSource[1];
    CouponRateT CouponRate;
    char TradeCondition[1];
    uint8_t PriceType;
} MDIncrementalRefreshBtecGroupT;

/*
 * Structure: Group Size
 */ 
typedef struct {
    uint16_t BlockLength;
    uint8_t NumInGroupUint8;
} GroupSizeT;

/*
 * Structure: M D Incremental Refresh Btec Groups
 */ 
typedef struct {
    GroupSizeT GroupSize;
} MDIncrementalRefreshBtecGroupsT;

/*
 * Structure: Md Incremental Refresh Btec
 */ 
typedef struct {
    uint16_t TradeDate;
    uint64_t TransactTime;
} MdIncrementalRefreshBtecT;

/*
 * Structure: Message Header
 */ 
typedef struct {
    uint16_t BlockLength;
    uint16_t TemplateId;
    uint16_t SchemaId;
    uint16_t Version;
} MessageHeaderT;

/*
 * Structure: Message
 */ 
typedef struct {
    uint16_t MessageSize;
    MessageHeaderT MessageHeader;
} MessageT;

/*
 * Structure: Binary Packet Header
 */ 
typedef struct {
    uint32_t MessageSequenceNumber;
    uint64_t SendingTime;
} BinaryPacketHeaderT;

/*
 * Structure: Packet
 */ 
typedef struct {
    BinaryPacketHeaderT BinaryPacketHeader;
} PacketT;

#pragma pack(pop)

/*******************************************************************************

Protocol:
   Organization: Chicago Mercantile Exchange
   Version: 10.1
   Date: Thursday, April 13, 2023

Source:
   Generator: 1.0.0.0
   Compiler: 2.0
   License: MIT No Attribution License
   Authors: Omi Developers

This file was generated by the Open Markets Initiative (Omi).

Information relating to Omi:
https://github.com/Open-Markets-Initiative/Directory

*******************************************************************************/
